import { supabase } from '@/integrations/supabase/client';
import { Patient, VitalSigns } from '@/types';

/* ============================================================
   Real Supabase-backed helpers (replaces previous mocks)
   ============================================================ */

/** Insert a patient. patient_code is auto-generated by a DB trigger if not provided. */
export async function registerPatient(payload: any) {
  const membershipType = payload.membershipType === 'temporary' ? 'temporary' : 'permanent';
  const insertRow = {
    patient_code: payload.patientId || null,
    membership_type: membershipType,
    membership_expires_at: payload.membershipExpiresAt || null,
    registration_reason: payload.registrationReason || null,
    first_name: payload.firstName,
    last_name: payload.lastName,
    date_of_birth: payload.dateOfBirth || null,
    gender: payload.gender || null,
    email: payload.email || null,
    phone: payload.phone || null,
    address: payload.address || null,
    city: payload.city || null,
    ghana_card_number: payload.ghanaCardNumber || null,
    blood_group: payload.bloodType || null,
    genotype: payload.genotype || null,
    allergies: payload.allergies || null,
    chronic_conditions: payload.chronicConditions || null,
    insurance_provider: payload.insuranceProvider || null,
    insurance_number: payload.policyNumber || null,
    insurance_group_number: payload.groupNumber || null,
    insurance_expiry: payload.insuranceExpiry || null,
    emergency_contact_name: payload.emergencyName || null,
    emergency_contact_phone: payload.emergencyPhone || null,
    emergency_contact_relation: payload.emergencyRelation || null,
  };
  const { data, error } = await supabase
    .from('patients')
    .insert(insertRow)
    .select()
    .single();
  if (error) throw error;
  return { success: true, patientId: data.patient_code, patient: data };
}

export async function searchPatients(query: string) {
  const q = query.trim();
  let req = supabase
    .from('patients')
    .select('id, patient_code, first_name, last_name, phone, ghana_card_number, status, insurance_provider, email, membership_type, membership_expires_at')
    .order('created_at', { ascending: false })
    .limit(50);

  if (q) req = req.or(`patient_code.ilike.%${q}%,first_name.ilike.%${q}%,last_name.ilike.%${q}%,phone.ilike.%${q}%,ghana_card_number.ilike.%${q}%,email.ilike.%${q}%`);
  const { data, error } = await req;
  if (error) { console.error('[searchPatients]', error); return []; }
  return (data ?? []).map((p) => ({
    id: p.id, patientId: p.patient_code, firstName: p.first_name, lastName: p.last_name,
    fullName: `${p.first_name} ${p.last_name}`, phone: p.phone, ghanaCardNumber: p.ghana_card_number,
    status: p.status, insuranceProvider: p.insurance_provider,
    membershipType: p.membership_type, membershipExpiresAt: p.membership_expires_at,
  }));
}

export async function getPatientById(id: string) { const { data } = await supabase.from('patients').select('*').eq('id', id).maybeSingle(); return data; }
export async function updatePatient(id: string, data: Partial<Patient>) { const { error } = await supabase.from('patients').update(data as any).eq('id', id); if (error) throw error; return { success: true }; }

/* ============================================================
   Document safety / analysis helpers
   ============================================================

   The previous implementation returned fabricated clinical findings such as blood
   groups, diagnoses and allergy statuses. Clinical analysis now remains advisory
   and data-derived.
   */
