import { supabase } from '@/integrations/supabase/client';
import { Patient, VitalSigns } from '@/types';

type PatientRegistrationPayload = {
  patientId?: string;
  membershipType?: 'permanent' | 'temporary';
  membershipExpiresAt?: string | null;
  registrationReason?: string;
  firstName: string;
  lastName: string;
  dateOfBirth?: string;
  gender?: string;
  email?: string;
  phone?: string;
  address?: string;
  city?: string;
  ghanaCardNumber?: string;
  bloodType?: string;
  genotype?: string;
  allergies?: string;
  chronicConditions?: string;
  insuranceProvider?: string;
  policyNumber?: string;
  groupNumber?: string;
  insuranceExpiry?: string;
  emergencyName?: string;
  emergencyPhone?: string;
  emergencyRelation?: string;
};

/** Insert a patient. patient_code may be generated by the database trigger. */
export async function registerPatient(payload: PatientRegistrationPayload) {
  const membershipType = payload.membershipType === 'temporary' ? 'temporary' : 'permanent';
  const insertRow = {
    patient_code: payload.patientId || null,
    membership_type: membershipType,
    membership_expires_at: payload.membershipExpiresAt || null,
    registration_reason: payload.registrationReason || null,
    first_name: payload.firstName,
    last_name: payload.lastName,
    date_of_birth: payload.dateOfBirth || null,
    gender: payload.gender || null,
    email: payload.email || null,
    phone: payload.phone || null,
    address: payload.address || null,
    city: payload.city || null,
    ghana_card_number: payload.ghanaCardNumber || null,
    blood_group: payload.bloodType || null,
    genotype: payload.genotype || null,
    allergies: payload.allergies || null,
    chronic_conditions: payload.chronicConditions || null,
    insurance_provider: payload.insuranceProvider || null,
    insurance_number: payload.policyNumber || null,
    insurance_group_number: payload.groupNumber || null,
    insurance_expiry: payload.insuranceExpiry || null,
    emergency_contact_name: payload.emergencyName || null,
    emergency_contact_phone: payload.emergencyPhone || null,
    emergency_contact_relation: payload.emergencyRelation || null,
  };
  const { data, error } = await supabase.from('patients').insert(insertRow).select().single();
  if (error) throw error;
  return { success: true, patientId: data.patient_code, patient: data };
}

function escapePatientSearchTerm(term: string) {
  return term
    .replace(/\\/g, '\\\\')
    .replace(/[%_]/g, '\\$&')
    .replace(/,/g, '\\,')
    .replace(/[()]/g, '\\$&');
}

export async function searchPatients(query: string) {
  const terms = query
    .trim()
    .split(/\s+/)
    .map(escapePatientSearchTerm)
    .filter(Boolean)
    .slice(0, 6);

  let req = supabase
    .from('patients')
    .select('id, patient_code, first_name, last_name, phone, ghana_card_number, status, insurance_provider, email, membership_type, membership_expires_at')
    .order('created_at', { ascending: false });

  if (terms.length > 0) {
    const searchableColumns = [
      'patient_code',
      'first_name',
      'last_name',
      'phone',
      'ghana_card_number',
      'email',
    ];
    const orGroups = terms.map((term) =>
      `or(${searchableColumns.map((column) => `${column}.ilike.%${term}%`).join(',')})`,
    );
    req = req.or(`and(${orGroups.join(',')})`);
  }

  const { data, error } = await req.limit(50);
  if (error) {
    console.error('[searchPatients]', error);
    return [];
  }
  return (data ?? []).map((p) => ({
    id: p.id,
    patientId: p.patient_code,
    firstName: p.first_name,
    lastName: p.last_name,
    fullName: `${p.first_name} ${p.last_name}`,
    phone: p.phone,
    ghanaCardNumber: p.ghana_card_number,
    status: p.status,
    insuranceProvider: p.insurance_provider,
    membershipType: p.membership_type,
    membershipExpiresAt: p.membership_expires_at,
  }));
}

export async function getPatientById(id: string) {
  const { data, error } = await supabase.from('patients').select('*').eq('id', id).maybeSingle();
  if (error) throw error;
  return data;
}

export async function updatePatient(id: string, data: Partial<Patient>) {
  const { error } = await supabase.from('patients').update(data as never).eq('id', id);
  if (error) throw error;
  return { success: true };
}

const MAX_DOCUMENT_SIZE_BYTES = 10 * 1024 * 1024;
const SUPPORTED_DOCUMENT_TYPES = new Set([
  'application/pdf',
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/tiff',
  'text/plain',
]);

async function sha256File(file: File): Promise<string> {
  const buffer = await file.arrayBuffer();
  const digest = await crypto.subtle.digest('SHA-256', buffer);
  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

export async function analyzeDocument(document: File) {
  if (!document || document.size === 0) return { success: false, findings: ['The selected document is empty and cannot be processed.'] };
  if (document.size > MAX_DOCUMENT_SIZE_BYTES) return { success: false, findings: ['The selected document exceeds the 10 MB upload limit.'] };
  const type = document.type || 'application/octet-stream';
  const fingerprint = await sha256File(document);
  const findings = [
    `Document accepted: ${document.name}`,
    `MIME type: ${type}`,
    `Size: ${(document.size / 1024).toFixed(1)} KB`,
    `SHA-256 fingerprint: ${fingerprint}`,
    SUPPORTED_DOCUMENT_TYPES.has(type)
      ? 'File integrity metadata generated successfully.'
      : 'The file type is not in the supported clinical-document set. Review before attaching it to the patient record.',
    'No diagnosis, medication-interaction assessment, or treatment recommendation was generated from this upload. Clinical OCR/AI extraction must be explicitly configured and reviewed by an authorized clinician.',
  ];
  return { success: true, findings, fingerprint };
}

export function registerPatientFromDocument(_document: File) {
  return Promise.resolve({ success: false, extracted: {}, message: 'Clinical document extraction requires a configured, access-controlled OCR service.' });
}

export function verifyGhanaCard(cardNumber: string) {
  return Promise.resolve({
    success: cardNumber.startsWith('GHA'),
    verified: false,
    authority: 'National Identification Authority Ghana',
    message: 'Format validation only. This does not verify the identity or authenticity of a Ghana Card.',
  });
}

export function evaluateTriagePriority(vitals: VitalSigns) {
  if (vitals.temperature >= 39 || vitals.oxygenSaturation <= 92 || vitals.heartRate >= 120 || vitals.bloodPressure.systolic >= 180) return 'Critical';
  if (vitals.temperature >= 38 || vitals.oxygenSaturation <= 94 || vitals.heartRate >= 100 || vitals.bloodPressure.systolic >= 160) return 'Urgent';
  return 'Moderate';
}
