import { supabase } from '@/integrations/supabase/client';
import { Patient, VitalSigns } from '@/types';

/* ============================================================
   Real Supabase-backed helpers (replaces previous mocks)
   ============================================================ */

/** Insert a patient. patient_code is auto-generated by a DB trigger if not provided. */
export async function registerPatient(payload: any) {
  const insertRow = {
    patient_code: payload.patientId || null,
    first_name: payload.firstName,
    last_name: payload.lastName,
    date_of_birth: payload.dateOfBirth || null,
    gender: payload.gender || null,
    email: payload.email || null,
    phone: payload.phone || null,
    address: payload.address || null,
    city: payload.city || null,
    ghana_card_number: payload.ghanaCardNumber || null,
    blood_group: payload.bloodType || null,
    genotype: payload.genotype || null,
    allergies: payload.allergies || null,
    chronic_conditions: payload.chronicConditions || null,
    insurance_provider: payload.insuranceProvider || null,
    insurance_number: payload.policyNumber || null,
    insurance_group_number: payload.groupNumber || null,
    insurance_expiry: payload.insuranceExpiry || null,
    emergency_contact_name: payload.emergencyName || null,
    emergency_contact_phone: payload.emergencyPhone || null,
    emergency_contact_relation: payload.emergencyRelation || null,
  };
  const { data, error } = await supabase
    .from('patients')
    .insert(insertRow)
    .select()
    .single();
  if (error) throw error;
  return { success: true, patientId: data.patient_code, patient: data };
}

export async function searchPatients(query: string) {
  const q = query.trim();
  let req = supabase
    .from('patients')
    .select('id, patient_code, first_name, last_name, phone, ghana_card_number, status, insurance_provider, email')
    .order('created_at', { ascending: false })
    .limit(50);

  if (q) {
    // OR across the most useful fields
    req = req.or(
      `patient_code.ilike.%${q}%,first_name.ilike.%${q}%,last_name.ilike.%${q}%,phone.ilike.%${q}%,ghana_card_number.ilike.%${q}%,email.ilike.%${q}%`,
    );
  }

  const { data, error } = await req;
  if (error) {
    console.error('[searchPatients]', error);
    return [];
  }
  return (data ?? []).map((p) => ({
    id: p.id,
    patientId: p.patient_code,
    firstName: p.first_name,
    lastName: p.last_name,
    fullName: `${p.first_name} ${p.last_name}`,
    phone: p.phone,
    ghanaCardNumber: p.ghana_card_number,
    status: p.status,
    insuranceProvider: p.insurance_provider,
  }));
}

export async function getPatientById(id: string) {
  const { data } = await supabase.from('patients').select('*').eq('id', id).maybeSingle();
  return data;
}

export async function updatePatient(id: string, data: Partial<Patient>) {
  const { error } = await supabase.from('patients').update(data as any).eq('id', id);
  if (error) throw error;
  return { success: true };
}

/* ============================================================
   Lightweight helpers still used by demo pages
   ============================================================ */

export function analyzeDocument(_document: File) {
  return Promise.resolve({
    success: true,
    findings: [
      'OCR extracted patient demographics and insurance details.',
      'No obvious drug interactions detected for current medication.',
      'Recommend physician review for referral and treatment planning.',
    ],
  });
}

export function registerPatientFromDocument(_document: File) {
  return Promise.resolve({ success: true, extracted: {} });
}

export function verifyGhanaCard(cardNumber: string) {
  return Promise.resolve({
    success: cardNumber.startsWith('GHA'),
    verified: true,
    authority: 'National Identification Authority Ghana',
  });
}

export function evaluateTriagePriority(vitals: VitalSigns) {
  if (
    vitals.temperature >= 39 ||
    vitals.oxygenSaturation <= 92 ||
    vitals.heartRate >= 120 ||
    vitals.bloodPressure.systolic >= 180
  ) {
    return 'Critical';
  }
  if (
    vitals.temperature >= 38 ||
    vitals.oxygenSaturation <= 94 ||
    vitals.heartRate >= 100 ||
    vitals.bloodPressure.systolic >= 160
  ) {
    return 'Urgent';
  }
  return 'Moderate';
}

// stubs kept so other pages compile — these are demo helpers only
export const recordTriageVitals = async (v: VitalSigns) => ({ success: true, vitals: v });
export const getCriticalPatients = async () => [];
export const getWaitingList = async () => [];
export const createConsultationEncounter = async (p: any) => ({ success: true, encounter: p });
export const addDiagnosisToConsultation = async (d: string) => ({ success: true, diagnosis: d });
export const setPrincipalDiagnosis = async (d: string) => ({ success: true, principalDiagnosis: d });
export const completeConsultation = async (d: any) => ({ success: true, data: d });
export const orderLabTest = async (p: any) => ({ success: true, order: p });
export const collectLabSample = async (id: string) => ({ success: true, orderId: id });
export const uploadLabResult = async (id: string, r: any) => ({ success: true, orderId: id, result: r });
export const validateLabResult = async (id: string) => ({ success: true, orderId: id });
export const getLabResults = async (patientId: string) => [{ patientId, results: [] }];
export const configureSoundAlert = async (c: any) => ({ success: true, config: c });
export const listSoundAlerts = async () => [];
export const triggerSoundAlert = async (id: string) => ({ success: true, alertId: id });
export const generatePublicHealthReport = async (id: string) => ({ success: true, report: id });
export const generateRoster = async (d: string, w: string) => ({ success: true, department: d, weekStart: w });
export const analyzeWithAI = async (m: string, p: any) => ({ success: true, module: m, payload: p });
