import { supabase } from '@/integrations/supabase/client';
import { reportsDb } from '@/lib/reportsDb';
import * as XLSX from 'xlsx';
export type ReportFrequency = 'weekly' | 'monthly' | 'quarterly' | 'annual'; export type ReportStatus = 'queued' | 'processing' | 'completed' | 'warning' | 'failed';
export interface ReportCategory { id:string; name:string; display_order:number; } export interface ReportDefinition { id:string; report_code:string; report_name:string; category_id:string|null; description:string|null; frequency:ReportFrequency; parameters:string[]; default_parameters:Record<string,unknown>; extractor_key:string; supported_formats:string[]; submission_deadline_day:number; is_active:boolean; implementation_status:'seeded'|'mapped'|'validated'|'retired'; category?:ReportCategory|null; }
export interface HealthcareFacility { id:string; name:string; facility_code:string|null; facility_type:string; district:string|null; region:string|null; dhims2_uid:string|null; is_active:boolean; }
export interface FacilityReportConfig { id:string; facility_id:string; report_id:string; is_enabled:boolean; submission_deadline_day:number|null; custom_parameters:Record<string,unknown>; report?:ReportDefinition; }
export interface ReportSnapshot { total:number; by_dimension:Array<{dimension:string;value:string;count:number}>; source:string; warning?:string; }
export interface ReportRunItem { id:string; run_id:string; report_id:string; status:ReportStatus; output_format:'xlsx'|'csv'|'pdf'; file_name:string|null; data_snapshot:ReportSnapshot; validation_messages:string[]; error_message:string|null; }
export interface ReportRun { id:string; facility_id:string; period_start:string; period_end:string; frequency:ReportFrequency; status:string; total_reports:number; success_count:number; warning_count:number; failed_count:number; created_at:string; completed_at:string|null; }
export interface ReportSubmission { id:string; report_id:string; facility_id:string; period_start:string; period_end:string; due_date:string; status:'pending'|'submitted'|'overdue'|'accepted'|'rejected'; submitted_at:string|null; submitted_by:string|null; submission_reference:string|null; }
const SOURCE_TABLES:Record<string,string>={opd_morbidity:'encounters + diagnoses',opd_attendance:'appointments',laboratory:'lab_orders + lab_results',inpatient_days:'admissions / inpatient module',surgeries:'procedure/theatre module',maternity:'maternity module'};
function monthBounds(period:string){const [year,month]=period.split('-').map(Number);const start=new Date(Date.UTC(year,month-1,1));const end=new Date(Date.UTC(year,month,0,23,59,59,999));return{start:start.toISOString(),end:end.toISOString()};}
async function countTable(table:string,dateColumn:string,start:string,end:string){const result=await reportsDb.from(table).select('id',{count:'exact',head:true}).gte(dateColumn,start).lte(dateColumn,end);if(result.error)throw new Error(result.error.message);return result.count??0;}
async function extractSnapshot(report:ReportDefinition,period:string):Promise<ReportSnapshot>{const{start,end}=monthBounds(period);try{switch(report.extractor_key){case'opd_morbidity':{const total=await countTable('diagnoses','created_at',start,end);return{total,by_dimension:[{dimension:'diagnoses recorded',value:'all',count:total}],source:'diagnoses',warning:'Facility-level attribution is pending because legacy clinical rows are not yet facility-scoped.'};}case'opd_attendance':{const total=await countTable('appointments','scheduled_at',start,end);return{total,by_dimension:[{dimension:'appointments',value:'all',count:total}],source:'appointments',warning:'Attendance classification will be completed when the OPD attendance data dictionary is mapped.'};}case'laboratory':{const orders=await countTable('lab_orders','created_at',start,end);const results=await countTable('lab_results','entered_at',start,end);return{total:orders,by_dimension:[{dimension:'lab orders',value:'all',count:orders},{dimension:'results entered',value:'all',count:results}],source:'lab_orders + lab_results'};default:return{total:0,by_dimension:[],source:SOURCE_TABLES[report.extractor_key]??'data dictionary mapping',warning:'No validated source adapter is registered yet. This report remains seeded/configurable but is not presented as DHIMS2-validated output.'};}}}catch(error){return{total:0,by_dimension:[],source:SOURCE_TABLES[report.extractor_key]??'unknown',warning:error instanceof Error?error.message:'Unable to read source data.'};}}
export async function listFacilities():Promise<HealthcareFacility[]>{const{data,error}=await reportsDb.from('healthcare_facilities').select('id,name,facility_code,facility_type,district,region,dhims2_uid,is_active').eq('is_active',true).order('name');if(error)throw new Error(error.message);return(data??[]) as HealthcareFacility[];}
export async function createFacility(input:Omit<HealthcareFacility,'id'|'is_active'>):Promise<HealthcareFacility>{const{data,error}=await reportsDb.from('healthcare_facilities').insert(input).select('id,name,facility_code,facility_type,district,region,dhims2_uid,is_active').single();if(error)throw new Error(error.message);const facility=data as HealthcareFacility;const seed=await reportsDb.rpc('seed_facility_reports',{_facility_id:facility.id});if(seed.error)throw new Error(seed.error.message);return facility;}
export async function listDefinitions():Promise<ReportDefinition[]>{const{data,error}=await reportsDb.from('report_definitions').select('*, report_categories(*)').eq('is_active',true).order('report_code');if(error)throw new Error(error.message);const rows=(data??[]) as Array<Record<string,unknown>>;return rows.map((row)=>{const categories=row.report_categories as ReportCategory[]|ReportCategory|null|undefined;return{...row,category:Array.isArray(categories)?categories[0]??null:categories??null,parameters:Array.isArray(row.parameters)?row.parameters:[]};}) as unknown as ReportDefinition[];}
export async function listFacilityConfigs(facilityId:string):Promise<FacilityReportConfig[]>{const{data,error}=await reportsDb.from('facility_report_config').select('*, report_definitions(*, report_categories(*))').eq('facility_id',facilityId).order('report_id');if(error)throw new Error(error.message);const rows=(data??[]) as Array<Record<string,unknown>>;return rows.map((row)=>({...row,report:row.report_definitions})) as unknown as FacilityReportConfig[];}
export async function setReportEnabled(facilityId:string,reportId:string,enabled:boolean){const{error}=await reportsDb.from('facility_report_config').upsert({facility_id:facilityId,report_id:reportId,is_enabled:enabled},{onConflict:'facility_id,report_id'});if(error)throw new Error(error.message);}
function dueDateFor(period:string,deadline:number){const[year,month]=period.split('-').map(Number);return new Date(Date.UTC(year,month,deadline)).toISOString().slice(0,10);}
export async function generateRun(facilityId:string,period:string,configs:FacilityReportConfig[]){const{start,end}=monthBounds(period);const enabled=configs.filter((config)=>config.is_enabled&&config.report?.frequency==='monthly');if(!enabled.length)throw new Error('No monthly reports are activated for this facility.');const userId=(await supabase.auth.getUser()).data.user?.id;const{data:runData,error:runError}=await reportsDb.from('report_generation_runs').insert({facility_id:facilityId,period_start:start.slice(0,10),period_end:end.slice(0,10),frequency:'monthly',status:'processing',total_reports:enabled.length,created_by:userId,started_at:new Date().toISOString(),parameters:{period}}).select('*').single();if(runError)throw new Error(runError.message);const run=runData as ReportRun;const{data:itemData,error:itemError}=await reportsDb.from('report_generation_items').insert(enabled.map((config)=>({run_id:run.id,report_id:config.report_id,status:'processing',output_format:'xlsx'}))).select('*');if(itemError)throw new Error(itemError.message);const items=itemData as ReportRunItem[];let success=0;let warning=0;let failed=0;for(const item of items){const config=enabled.find((entry)=>entry.report_id===item.report_id);if(!config?.report)continue;const snapshot=await extractSnapshot(config.report,period);const hasWarning=Boolean(snapshot.warning);const status:ReportStatus=hasWarning?'warning':'completed';if(hasWarning)warning+=1;else success+=1;const{error}=await reportsDb.from('report_generation_items').update({status,data_snapshot:snapshot,validation_messages:snapshot.warning?[snapshot.warning]:[],file_name:`${config.report.report_code}_${period}.xlsx`,completed_at:new Date().toISOString()}).eq('id',item.id);if(error)failed+=1;await reportsDb.from('report_submissions').upsert({report_id:config.report_id,facility_id:facilityId,period_start:start.slice(0,10),period_end:end.slice(0,10),due_date:dueDateFor(period,config.submission_deadline_day??config.report.submission_deadline_day),status:'pending',data_snapshot:snapshot},{onConflict:'report_id,facility_id,period_start,period_end'});}failed=failed+(enabled.length-success-warning-failed);const finalStatus=failed>0?'partial_failed':'completed';const{data:finalData,error:finalError}=await reportsDb.from('report_generation_runs').update({status:finalStatus,success_count:success,warning_count:warning,failed_count:failed,completed_at:new Date().toISOString()}).eq('id',run.id).select('*').single();if(finalError)throw new Error(finalError.message);return finalData as ReportRun;}
export async function getRunItems(runId:string):Promise<ReportRunItem[]>{const{data,error}=await reportsDb.from('report_generation_items').select('*').eq('run_id',runId).order('created_at');if(error)throw new Error(error.message);return(data??[]) as ReportRunItem[];}
export async function listSubmissions(facilityId:string,period:string):Promise<ReportSubmission[]>{const{start,end}=monthBounds(period);const{data,error}=await reportsDb.from('report_submissions').select('*').eq('facility_id',facilityId).eq('period_start',start.slice(0,10)).eq('period_end',end.slice(0,10)).order('due_date');if(error)throw new Error(error.message);return(data??[]) as ReportSubmission[];}
export async function markSubmissionsSubmitted(ids:string[]){if(!ids.length)return;const userId=(await supabase.auth.getUser()).data.user?.id;const{error}=await reportsDb.from('report_submissions').update({status:'submitted',submitted_at:new Date().toISOString(),submitted_by:userId}).in('id',ids);if(error)throw new Error(error.message);}
export async function downloadRunWorkbook(run:ReportRun,items:ReportRunItem[],facility:HealthcareFacility){const workbook=XLSX.utils.book_new();const manifest=items.map((item)=>({Report:item.file_name??item.report_id,Status:item.status,Source:item.data_snapshot.source,Total:item.data_snapshot.total,Warnings:item.validation_messages.join(' | ')}));XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(manifest),'Manifest');for(const item of items){const rows=item.data_snapshot.by_dimension.map((row)=>({Dimension:row.dimension,Value:row.value,Count:row.count}));if(!rows.length)rows.push({Dimension:'status',Value:item.status,Count:item.data_snapshot.total});const sheetName=(item.file_name??item.report_id).replace(/[^A-Za-z0-9 ]/g,'').slice(0,28)||'Report';XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(rows),sheetName);}XLSX.writeFile(workbook,`Monthly_Reports_${facility.name.replace(/[^A-Za-z0-9]+/g,'_')}_${run.period_start.slice(0,7)}.xlsx`);}
export function downloadRunManifestCsv(run:ReportRun,items:ReportRunItem[],facility:HealthcareFacility){const rows=[['Report','Status','Source','Total','Warnings'],...items.map((item)=>[item.file_name??item.report_id,item.status,item.data_snapshot.source,String(item.data_snapshot.total),item.validation_messages.join(' | ')])];const csv=rows.map((row)=>row.map((cell)=>`"${String(cell).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`Reports_Manifest_${facility.name.replace(/[^A-Za-z0-9]+/g,'_')}_${run.period_start.slice(0,7)}.csv`;anchor.click();URL.revokeObjectURL(url);}
