begin;

select plan(28);

select ok((select relrowsecurity from pg_class where oid = 'public.user_roles'::regclass),'user_roles has RLS enabled');
select ok(exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_roles' and policyname = 'user_roles_select_own' and qual is not null and qual ilike '%auth.uid%'),'user_roles read policy is scoped to the current user');
select ok(exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'facility_memberships' and policyname = 'memberships_read' and qual is not null and qual ilike '%auth.uid%'),'facility membership reads are scoped to the current user or administrator');
select ok(not has_function_privilege('authenticated','public.notify_due_medications()','EXECUTE') and not has_function_privilege('authenticated','public.lock_overdue_medication_slots()','EXECUTE'),'internal medication maintenance functions are not callable by authenticated clients');
select ok(exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'patients' and policyname = 'authorized users read patients' and qual is not null and qual not in ('true','(true)')),'patient reads are governed by an authorization predicate');

select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('grant_service_order_override','release_service_order','cancel_service_order','mark_service_order_in_progress','complete_service_order') and p.prosecdef and not has_function_privilege('anon',p.oid,'EXECUTE') and has_function_privilege('authenticated',p.oid,'EXECUTE'))=5,'service-order lifecycle RPCs are security-definer and authenticated-only');
select ok(has_function_privilege('authenticated','public.release_service_order(uuid,text)','EXECUTE') and not has_function_privilege('anon','public.release_service_order(uuid,text)','EXECUTE') and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='uuid, _reason text') ilike '%has_role(auth.uid(),''front_desk'')%','payment release is authenticated-only and permits the front-desk payment workflow');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='grant_service_order_override' and pg_get_function_identity_arguments(p.oid)='uuid, _reason text') ilike '%status <> ''pending_payment_approval''%','billing overrides are restricted to orders awaiting payment approval');
select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_lab_order_with_payment_gate','collect_lab_sample','enter_lab_result','approve_lab_result') and p.prosecdef and not has_function_privilege('anon',p.oid,'EXECUTE') and has_function_privilege('authenticated',p.oid,'EXECUTE'))=4,'laboratory workflow RPCs are security-definer and authenticated-only');
select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('find_pharmacy_alternatives','prepare_pharmacy_dispensing','confirm_pharmacy_dispense','create_pharmacy_pos_sale','confirm_pharmacy_pos_sale','create_pharmacy_inventory_item') and p.prosecdef and not has_function_privilege('anon',p.oid,'EXECUTE') and has_function_privilege('authenticated',p.oid,'EXECUTE'))=6,'pharmacy workflow RPCs are security-definer and authenticated-only');
select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_insurance_claim_draft','transition_insurance_claim','update_insurance_claim_financials') and p.prosecdef and not has_function_privilege('anon',p.oid,'EXECUTE') and has_function_privilege('authenticated',p.oid,'EXECUTE'))=3,'insurance claim mutation RPCs are security-definer and authenticated-only');
select ok(has_function_privilege('authenticated','public.pay_selected_invoice_items(uuid,uuid[],text,text)','EXECUTE') and not has_function_privilege('anon','public.pay_selected_invoice_items(uuid,uuid[],text,text)','EXECUTE'),'selected-invoice payment collection is authenticated-only');
select ok(exists (select 1 from pg_policies where schemaname='public' and tablename='insurance_claims' and policyname='staff read claims' and qual is not null and qual ilike '%has_role%' and qual not in ('true','(true)')),'insurance claim reads are role-scoped rather than broadly exposed');
select ok(exists (select 1 from pg_policies where schemaname='public' and tablename='payments' and policyname='staff read payments' and qual is not null and qual ilike '%has_role%' and qual not in ('true','(true)')),'payment reads are role-scoped rather than broadly exposed');
select ok(has_function_privilege('authenticated','public.set_facility_routing_mode(text)','EXECUTE') and not has_function_privilege('anon','public.set_facility_routing_mode(text)','EXECUTE') and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_facility_routing_mode' and pg_get_function_identity_arguments(p.oid)='_mode text') ilike '%has_role(auth.uid(),''admin'')%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_facility_routing_mode' and pg_get_function_identity_arguments(p.oid)='_mode text') ilike '%Administrator role required%','facility routing mode is authenticated-only and administrator-gated');
select ok(has_function_privilege('authenticated','public.recover_stale_report_run(uuid,integer)','EXECUTE') and not has_function_privilege('anon','public.recover_stale_report_run(uuid,integer)','EXECUTE') and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='recover_stale_report_run' and pg_get_function_identity_arguments(p.oid)='_run_id uuid, _stale_after_minutes integer') ilike '%has_facility_access(v_user,v_run.facility_id)%','report recovery is authenticated-only and facility-scoped');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='pay_selected_invoice_items' and pg_get_function_identity_arguments(p.oid)='_invoice_id uuid, _item_ids uuid[], _method text, _reference text') ilike '%idempotent_replay%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='pay_selected_invoice_items' and pg_get_function_identity_arguments(p.oid)='_invoice_id uuid, _item_ids uuid[], _method text, _reference text') ilike '%lower(trim(reference)) = lower(normalized_reference)%','selected-invoice payment rejects duplicate references through an idempotent replay boundary');
select ok(not has_function_privilege('public','public.audit_patient_change()','EXECUTE') and not has_function_privilege('anon','public.audit_patient_change()','EXECUTE') and not has_function_privilege('authenticated','public.audit_patient_change()','EXECUTE') and not has_function_privilege('public','public.validate_service_order_encounter()','EXECUTE') and not has_function_privilege('anon','public.validate_service_order_encounter()','EXECUTE') and not has_function_privilege('authenticated','public.validate_service_order_encounter()','EXECUTE'),'trigger-only SECURITY DEFINER helpers are outside the client execution surface');
select ok(not has_function_privilege('public','public.notify_due_medications()','EXECUTE') and not has_function_privilege('public','public.lock_overdue_medication_slots()','EXECUTE') and not has_function_privilege('anon','public.notify_due_medications()','EXECUTE') and not has_function_privilege('anon','public.lock_overdue_medication_slots()','EXECUTE') and not has_function_privilege('authenticated','public.notify_due_medications()','EXECUTE') and not has_function_privilege('authenticated','public.lock_overdue_medication_slots()','EXECUTE'),'scheduler-only medication maintenance helpers are outside the client execution surface');
select ok(not has_function_privilege('public','public.has_role(uuid,public.app_role)','EXECUTE') and not has_function_privilege('anon','public.has_role(uuid,public.app_role)','EXECUTE') and not has_function_privilege('authenticated','public.has_role(uuid,public.app_role)','EXECUTE') and not has_function_privilege('public','public.has_facility_access(uuid,uuid)','EXECUTE') and not has_function_privilege('anon','public.has_facility_access(uuid,uuid)','EXECUTE') and not has_function_privilege('authenticated','public.has_facility_access(uuid,uuid)','EXECUTE'),'arbitrary-user authorization helper probes are outside the client execution surface');

select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('grant_service_order_override','release_service_order','cancel_service_order','mark_service_order_in_progress','complete_service_order','create_lab_order_with_payment_gate','collect_lab_sample','enter_lab_result','approve_lab_result') and p.prosecdef and has_function_privilege('authenticated',p.oid,'EXECUTE') and not has_function_privilege('anon',p.oid,'EXECUTE'))=9,'classified application SECURITY DEFINER workflow RPCs remain authenticated-only');

select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('get_legacy_patient_candidates','reconcile_legacy_migration_row','validate_legacy_migration_batch','approve_legacy_migration_batch','promote_legacy_migration_batch') and p.prosecdef and not has_function_privilege('anon',p.oid,'EXECUTE') and has_function_privilege('authenticated',p.oid,'EXECUTE'))=5 and (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('get_legacy_patient_candidates','reconcile_legacy_migration_row','validate_legacy_migration_batch','approve_legacy_migration_batch','promote_legacy_migration_batch') and pg_get_functiondef(p.oid) ilike '%has_role(auth.uid(),''admin'')%')=5,'legacy migration reconciliation RPCs are security-definer, authenticated-only and administrator-gated');
select ok(has_function_privilege('authenticated','public.get_my_permissions()','EXECUTE') and not has_function_privilege('anon','public.get_my_permissions()','EXECUTE') and not has_function_privilege('public','public.get_my_permissions()','EXECUTE') and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_my_permissions' and pg_get_function_identity_arguments(p.oid)='') ilike '%auth.uid()%','permission discovery RPC is authenticated-only and bound to the current user');
select ok(has_function_privilege('authenticated','public.replace_role_permissions(public.app_role,text[])','EXECUTE') and not has_function_privilege('anon','public.replace_role_permissions(public.app_role,text[])','EXECUTE') and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='replace_role_permissions' and pg_get_function_identity_arguments(p.oid)='_role public.app_role, _permission_keys text[]') ilike '%has_role(auth.uid(), ''admin'')%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='replace_role_permissions' and pg_get_function_identity_arguments(p.oid)='_role public.app_role, _permission_keys text[]') ilike '%_role=''admin''%','role permission replacement is authenticated-only and administrator-gated');


select ok(has_function_privilege('authenticated','public.create_service_catalogue_item(text,text,text,text,numeric,text)','EXECUTE') and not has_function_privilege('anon','public.create_service_catalogue_item(text,text,text,text,numeric,text)','EXECUTE'),'service catalogue creation is authenticated-only');
select ok(has_function_privilege('authenticated','public.create_lab_test_catalogue_item(text,text,text,text,text,numeric,numeric,text,numeric,integer)','EXECUTE') and not has_function_privilege('anon','public.create_lab_test_catalogue_item(text,text,text,text,text,numeric,numeric,text,numeric,integer)','EXECUTE'),'laboratory catalogue creation is authenticated-only');
select ok(has_function_privilege('authenticated','public.create_pharmacy_inventory_item(text,text,text,text,text,text,text,date,integer,integer,numeric)','EXECUTE') and not has_function_privilege('anon','public.create_pharmacy_inventory_item(text,text,text,text,text,text,text,date,integer,integer,numeric)','EXECUTE'),'pharmacy catalogue creation is authenticated-only');
select ok((select count(*) from public.permissions where permission_key in ('create_services','create_items') and is_active)=2 and (select count(*) from public.role_permissions where (role='pharmacist' and permission_key='create_items') or (role='lab_technician' and permission_key in ('create_items','create_services')) or (role='accountant' and permission_key='create_services'))=4,'catalogue creation privileges are registered for pharmacy, laboratory and accounts roles');

select * from finish();
rollback;


select ok(
  (select pg_get_functiondef(p.oid)
   from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='public'
     and p.proname='get_patient_care_continuity'
     and pg_get_function_identity_arguments(p.oid)='_patient_id uuid')
   ilike '%public.has_role(uid,''admin'')%'
   and (select pg_get_functiondef(p.oid)
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='public'
          and p.proname='get_patient_care_continuity'
          and pg_get_function_identity_arguments(p.oid)='_patient_id uuid')
   not ilike '%public.has_role(uid,''accountant'')%'
   and (select pg_get_functiondef(p.oid)
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='public'
          and p.proname='get_patient_care_continuity'
          and pg_get_function_identity_arguments(p.oid)='_patient_id uuid')
   not ilike '%public.has_role(uid,''front_desk'')%',
  'patient continuity RPC excludes non-clinical accountant/front-desk access'
);


select ok(
  (select pg_get_functiondef(p.oid)
   from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='public' and p.proname='get_patient_hub_snapshot'
     and pg_get_function_identity_arguments(p.oid)='_patient_id uuid')
   ilike '%WHEN is_clinical THEN to_jsonb(p)%'
   and (select pg_get_functiondef(p.oid)
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='public' and p.proname='get_patient_hub_snapshot'
          and pg_get_function_identity_arguments(p.oid)='_patient_id uuid')
   ilike '%ELSE jsonb_build_object%',
  'patient hub snapshot minimizes patient payload for non-clinical roles'
);

select ok(
  (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_emergency_workspace' and pg_get_function_identity_arguments(p.oid)='_limit integer')
  ilike '%public.has_role(auth.uid(),''front_desk'')%'
  and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_emergency_workspace' and pg_get_function_identity_arguments(p.oid)='_limit integer')
  ilike '%disposition%','emergency workspace retains explicit role boundary and disposition field'
);

select ok(
  (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admit_encounter_workflow' and pg_get_function_identity_arguments(p.oid)='_encounter_id uuid, _reason text, _ward text, _emergency_override boolean')
  ilike '%FROM public.facility_configuration%'
  and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admit_encounter_workflow' and pg_get_function_identity_arguments(p.oid)='_encounter_id uuid, _reason text, _ward text, _emergency_override boolean')
  not ilike '%FROM public.facility_settings%'
  and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admit_encounter_workflow' and pg_get_function_identity_arguments(p.oid)='_encounter_id uuid, _reason text, _ward text, _emergency_override boolean')
  ilike '%allow_clinical_emergency_override%','admission override uses canonical facility configuration and emergency flag'
);

select ok(
  (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_insurance_claim_draft' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _payer_name text, _member_number text, _amount_claimed numeric, _invoice_id uuid')
  ilike '%Invoice does not belong to patient%'
  and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_insurance_claim_draft' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _payer_name text, _member_number text, _amount_claimed numeric, _invoice_id uuid')
  ilike '%invoice_id=_invoice_id AND payer_name=trim(_payer_name)%','insurance claim draft must bind supplied invoice to patient and prevent active duplicate claims'
);

select ok(
  (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='_service_order_id uuid, _reason text')
  ilike '%invoice_item_payments%' AND (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='_service_order_id uuid, _reason text') ilike '%invoice_item_id%','service-order release must use item-level payment allocation when an invoice item link exists'
);

select ok(
  (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='update_insurance_claim_financials' and pg_get_function_identity_arguments(p.oid)='_claim_id uuid, _amount_approved numeric, _amount_paid numeric, _claim_number text, _rejection_reason text') ilike '%Approved amount cannot exceed claimed amount%'
  and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='update_insurance_claim_financials' and pg_get_function_identity_arguments(p.oid)='_claim_id uuid, _amount_approved numeric, _amount_paid numeric, _claim_number text, _rejection_reason text') ilike '%Paid amount cannot exceed approved amount%','insurance claim financial edits must not approve or pay beyond claim limits'
);

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_insurance_claim_canonical' and pg_get_function_identity_arguments(p.oid)='_claim_id uuid, _status text, _amount_approved numeric, _amount_paid numeric, _rejection_reason text, _notes text') ilike '%Only approved claims can be marked paid%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_insurance_claim_canonical' and pg_get_function_identity_arguments(p.oid)='_claim_id uuid, _status text, _amount_approved numeric, _amount_paid numeric, _rejection_reason text, _notes text') ilike '%Claim must be under review before adjudication%','insurance claim transitions enforce lifecycle ordering');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='pay_selected_invoice_items' and pg_get_function_identity_arguments(p.oid)='_invoice_id uuid, _item_ids uuid[], _method text, _reference text') ilike '%FOR UPDATE%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='pay_selected_invoice_items' and pg_get_function_identity_arguments(p.oid)='_invoice_id uuid, _item_ids uuid[], _method text, _reference text') ilike '%do not belong to this invoice%','invoice item payments lock and validate selected items before allocation');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='prepare_patient_billable_items' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _from timestamp with time zone, _to timestamp with time zone') ilike '%pg_advisory_xact_lock%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='prepare_patient_billable_items' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _from timestamp with time zone, _to timestamp with time zone') ilike '%FOR UPDATE%','billable item materialization serializes open invoice creation');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_discharge_insurance_claim' and pg_get_function_identity_arguments(p.oid)='_notification_id uuid, _payer_name text, _member_number text') ilike '%pg_advisory_xact_lock%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_discharge_insurance_claim' and pg_get_function_identity_arguments(p.oid)='_notification_id uuid, _payer_name text, _member_number text') ilike '%FOR UPDATE%','discharge insurance claim creation is replay-safe and handoff-locked');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='prepare_pharmacy_dispensing' and pg_get_function_identity_arguments(p.oid)='_prescription_id uuid, _inventory_id uuid, _quantity integer, _notes text') ilike '%exceeds prescribed quantity%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='prepare_pharmacy_dispensing' and pg_get_function_identity_arguments(p.oid)='_prescription_id uuid, _inventory_id uuid, _quantity integer, _notes text') ilike '%status=''unpaid''%','pharmacy dispensing enforces prescribed quantity and idempotent unpaid preparation');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='find_pharmacy_alternatives' and pg_get_function_identity_arguments(p.oid)='_medication text, _strength text') ilike '%Pharmacy role required%','pharmacy inventory search requires a pharmacy role');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_pharmacy_pos_sale' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _inventory_id uuid, _quantity integer') ilike '%Patient not found%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_pharmacy_pos_sale' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _inventory_id uuid, _quantity integer') ilike '%item.active%','pharmacy POS validates patient and active inventory');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_pharmacy_pos_sale' and pg_get_function_identity_arguments(p.oid)='_sale_id uuid') ilike '%status IN(''released'',''in_progress'')%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_pharmacy_pos_sale' and pg_get_function_identity_arguments(p.oid)='_sale_id uuid') ilike '%FOR UPDATE%','pharmacy POS confirmation requires released payment and row locks');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_pharmacy_dispense' and pg_get_function_identity_arguments(p.oid)='_plan_id uuid') ilike '%Prescription does not match dispensing patient%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_pharmacy_dispense' and pg_get_function_identity_arguments(p.oid)='_plan_id uuid') ilike '%Dispensing service order does not match prescription%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.oid=p.pronamespace and p.proname='confirm_pharmacy_dispense' and pg_get_function_identity_arguments(p.oid)='_plan_id uuid') ilike '%FOR UPDATE%','pharmacy dispensing validates prescription, service-order linkage and locks lifecycle rows');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='_service_order_id uuid, _reason text DEFAULT ''Payment received''') ilike '%invoice does not belong to the patient%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='_service_order_id uuid, _reason text DEFAULT ''Payment received''') ilike '%invoice item does not match invoice%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='release_service_order' and pg_get_function_identity_arguments(p.oid)='_service_order_id uuid, _reason text DEFAULT ''Payment received''') ilike '%invoice_item_payments%','service-order release enforces patient/invoice/item consistency');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='collect_lab_sample' and pg_get_function_identity_arguments(p.oid)='_lab_order_id uuid') ilike '%patient_id=o.patient_id%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='collect_lab_sample' and pg_get_function_identity_arguments(p.oid)='_lab_order_id uuid') ilike '%FOR UPDATE%','lab sample collection locks order and matches billing patient');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='enter_lab_result' and pg_get_function_identity_arguments(p.oid)='_lab_order_id uuid, _result_text text, _numeric_value numeric DEFAULT NULL::numeric, _interpretation text DEFAULT NULL::text, _is_abnormal boolean DEFAULT false') ilike '%completed result already exists%','lab result entry blocks completed-result replay');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='approve_lab_result' and pg_get_function_identity_arguments(p.oid)='_lab_result_id uuid') ilike '%Laboratory order must be completed%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='approve_lab_result' and pg_get_function_identity_arguments(p.oid)='_lab_result_id uuid') ilike '%FOR UPDATE%','lab approval locks and validates parent order state');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_imaging_order_with_payment_gate' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _encounter_id uuid DEFAULT NULL::uuid, _modality text DEFAULT ''X-Ray''::text, _study_name text DEFAULT ''General study''::text, _body_site text DEFAULT NULL::text, _priority text DEFAULT ''routine''::text, _clinical_indication text DEFAULT NULL::text, _amount numeric DEFAULT 0') ilike '%Encounter does not belong to patient%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_imaging_order_with_payment_gate' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _encounter_id uuid DEFAULT NULL::uuid, _modality text DEFAULT ''X-Ray''::text, _study_name text DEFAULT ''General study''::text, _body_site text DEFAULT NULL::text, _priority text DEFAULT ''routine''::text, _clinical_indication text DEFAULT NULL::text, _amount numeric DEFAULT 0') ilike '%Patient not found%','imaging order validates patient and encounter ownership');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='start_imaging_order' and pg_get_function_identity_arguments(p.oid)='_imaging_order_id uuid') ilike '%s.patient_id<>o.patient_id%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='start_imaging_order' and pg_get_function_identity_arguments(p.oid)='_imaging_order_id uuid') ilike '%FOR UPDATE%','imaging start enforces service-order linkage and row locks');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='complete_imaging_order' and pg_get_function_identity_arguments(p.oid)='_imaging_order_id uuid, _report text, _impression text') ilike '%Radiology report ready%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='complete_imaging_order' and pg_get_function_identity_arguments(p.oid)='_imaging_order_id uuid, _report text, _impression text') ilike '%NOT EXISTS%','imaging completion prevents duplicate result notifications');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_procedure_note' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _procedure_name text, _template_used text, _indication text, _technique text, _findings text, _complications text, _post_op_plan text, _charge_amount numeric, _service_order_id uuid') ilike '%sid.patient_id<>_patient_id%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_procedure_note' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _procedure_name text, _template_used text, _indication text, _technique text, _findings text, _complications text, _post_op_plan text, _charge_amount numeric, _service_order_id uuid') ilike '%FOR UPDATE%','procedure note enforces patient/service-order consistency');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_medication_administration' and pg_get_function_identity_arguments(p.oid)='_record_id uuid, _status text, _reason text DEFAULT NULL::text, _notes text DEFAULT NULL::text, _witnessed_by uuid DEFAULT NULL::uuid') ilike '%Medication prescription does not match patient%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_medication_administration' and pg_get_function_identity_arguments(p.oid)='_record_id uuid, _status text, _reason text DEFAULT NULL::text, _notes text DEFAULT NULL::text, _witnessed_by uuid DEFAULT NULL::uuid') ilike '%Unsupported medication administration status%','MAR transition enforces prescription identity and status allowlist');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_theatre_case' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _procedure_name text, _scheduled_start timestamp with time zone DEFAULT NULL::timestamp with time zone, _theatre_name text DEFAULT NULL::text, _urgency text DEFAULT ''elective''::text, _surgeon_id uuid DEFAULT NULL::uuid, _anesthetist_id uuid DEFAULT NULL::uuid, _encounter_id uuid DEFAULT NULL::uuid') ilike '%Encounter does not belong to patient%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_theatre_case' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _procedure_name text, _scheduled_start timestamp with time zone DEFAULT NULL::timestamp with time zone, _theatre_name text DEFAULT NULL::text, _urgency text DEFAULT ''elective''::text, _surgeon_id uuid DEFAULT NULL::uuid, _anesthetist_id uuid DEFAULT NULL::uuid, _encounter_id uuid DEFAULT NULL::uuid') ilike '%Assigned surgeon must be a practitioner%','theatre creation validates patient encounter and clinician identity');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_theatre_case' and pg_get_function_identity_arguments(p.oid)='_case_id uuid, _status text, _cancellation_reason text DEFAULT NULL::text') ilike '%Invalid theatre lifecycle transition%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_theatre_case' and pg_get_function_identity_arguments(p.oid)='_case_id uuid, _status text, _cancellation_reason text DEFAULT NULL::text') ilike '%FOR UPDATE%','theatre transition enforces state machine and row locking');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_transfusion_event' and pg_get_function_identity_arguments(p.oid)='_record_id uuid, _status text, _reaction_observed boolean DEFAULT false, _reaction_notes text DEFAULT NULL::text') ilike '%Transfusion must be independently verified%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_transfusion_event' and pg_get_function_identity_arguments(p.oid)='_record_id uuid, _status text, _reaction_observed boolean DEFAULT false, _reaction_notes text DEFAULT NULL::text') ilike '%Invalid transfusion lifecycle transition%','transfusion administration requires verification and valid lifecycle transitions');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='schedule_patient_referral_workflow' and pg_get_function_identity_arguments(p.oid)='_referral_id uuid') ilike '%FOR UPDATE%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='schedule_patient_referral_workflow' and pg_get_function_identity_arguments(p.oid)='_referral_id uuid') ilike '%pg_advisory_xact_lock%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='schedule_patient_referral_workflow' and pg_get_function_identity_arguments(p.oid)='_referral_id uuid') ilike '%Referral patient not found%','referral scheduling locks the referral and serializes appointment creation');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_nursing_shift_handover' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _shift_label text, _clinical_summary text, _pending_tasks text DEFAULT NULL::text, _safety_concerns text DEFAULT NULL::text, _escalation_required boolean DEFAULT false, _ward_id uuid DEFAULT NULL::uuid') ilike '%Patient not found%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_nursing_shift_handover' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _shift_label text, _clinical_summary text, _pending_tasks text DEFAULT NULL::text, _safety_concerns text DEFAULT NULL::text, _escalation_required boolean DEFAULT false, _ward_id uuid DEFAULT NULL::uuid') ilike '%open handover already exists%','handover creation validates patient and prevents duplicate open shift handovers');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='acknowledge_nursing_handover' and pg_get_function_identity_arguments(p.oid)='_handover_id uuid') ilike '%Outgoing officer cannot acknowledge%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='acknowledge_nursing_handover' and pg_get_function_identity_arguments(p.oid)='_handover_id uuid') ilike '%FOR UPDATE%','handover acknowledgement prevents self-acknowledgement and races');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admit_encounter_workflow' and pg_get_function_identity_arguments(p.oid)='_encounter_id uuid, _reason text DEFAULT NULL::text, _ward text DEFAULT NULL::text, _emergency_override boolean DEFAULT true') ilike '%Encounter patient not found%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admit_encounter_workflow' and pg_get_function_identity_arguments(p.oid)='_encounter_id uuid, _reason text DEFAULT NULL::text, _ward text DEFAULT NULL::text, _emergency_override boolean DEFAULT true') ilike '%FROM public.encounters WHERE id=_encounter_id FOR UPDATE%','admission validates patient linkage and locks encounter');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='discharge_admission_workflow' and pg_get_function_identity_arguments(p.oid)='_admission_id uuid, _summary text DEFAULT NULL::text') ilike '%FROM public.admissions WHERE id=_admission_id FOR UPDATE%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='discharge_admission_workflow' and pg_get_function_identity_arguments(p.oid)='_admission_id uuid, _summary text DEFAULT NULL::text') ilike '%existing%TRUE%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='discharge_admission_workflow' and pg_get_function_identity_arguments(p.oid)='_admission_id uuid, _summary text DEFAULT NULL::text') ilike '%discharge_billing_handoff%','discharge locks admission and is replay-safe for billing handoff');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_emergency_case' and pg_get_function_identity_arguments(p.oid)='_case_id uuid, _status text, _disposition text DEFAULT NULL::text') ilike '%FOR UPDATE%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='transition_emergency_case' and pg_get_function_identity_arguments(p.oid)='_case_id uuid, _status text, _disposition text DEFAULT NULL::text') ilike '%Disposition is required%','emergency transitions lock cases and require disposition on closure');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_transfusion_record' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _blood_product text, _unit_identifier text, _blood_group text DEFAULT NULL::text, _consent_confirmed boolean DEFAULT false, _encounter_id uuid DEFAULT NULL::uuid') ilike '%Blood unit is already assigned%' and (select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_transfusion_record' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _blood_product text, _unit_identifier text, _blood_group text DEFAULT NULL::text, _consent_confirmed boolean DEFAULT false, _encounter_id uuid DEFAULT NULL::uuid') ilike '%Encounter does not belong to the selected patient%','transfusion creation binds patient encounter and prevents active unit reuse');

select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_attending_patient_history' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _current_encounter_id uuid DEFAULT NULL::uuid') ilike '%Encounter does not belong to patient%' ,'attending history rejects cross-patient encounter context');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_encounter_clinical_context' and pg_get_function_identity_arguments(p.oid)='_patient_id uuid, _encounter_id uuid DEFAULT NULL::uuid') ilike '%Encounter does not belong to patient%' ,'clinical context rejects cross-patient encounter context');
