import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, BellRing, Image as ImageIcon, Loader2, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';

type Card={key:string;label:string;value:number;href:string;description:string};
export default function RadiologyTechnicianDashboard(){
  const [cards,setCards]=useState<Card[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string | null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error:rpcError}=await (supabase as any).rpc('get_role_dashboard_summary');if(rpcError){setError(rpcError.message);setCards([])}else{setCards((data?.cards??[]) as Card[])}setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const icons:Record<string,typeof ImageIcon>={ready:ImageIcon,progress:Loader2,urgent:AlertTriangle,notifications:BellRing};
  return <div className="space-y-6 animate-fade-in"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Imaging Operations</p><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><ImageIcon className="h-6 w-6 text-primary"/>Radiology Technician Dashboard</h1><p className="text-sm text-muted-foreground mt-1">Acquisition readiness, active studies, image quality workflow and urgent work.</p></div><button type="button" onClick={()=>void load()} className="btn-secondary inline-flex items-center gap-2"><RefreshCw className="h-4 w-4"/>{loading?'Refreshing…':'Refresh'}</button></header>{error&&<div role="alert" className="rounded-xl border border-critical/30 bg-critical/5 p-4 text-sm"><p className="font-medium text-critical">Dashboard data unavailable</p><p className="mt-1 text-muted-foreground">{error}</p><button type="button" onClick={()=>void load()} className="mt-3 btn-secondary">Retry</button></div>}<section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(c=>{const Icon=icons[c.key]??ImageIcon;return <Link key={c.key} to={c.href} className="card-medical p-4 hover:-translate-y-0.5 transition-all"><div className="flex justify-between gap-2"><p className="text-xs text-muted-foreground">{c.label}</p><Icon className="h-4 w-4 text-primary"/></div><p className="mt-2 text-3xl font-bold tabular-nums">{c.value}</p><p className="mt-1 text-xs text-muted-foreground">{c.description}</p></Link>})}</section><div className="grid gap-3 sm:grid-cols-3"><Link to="/radiology" className="card-medical p-5"><p className="font-semibold">Imaging worklist</p><p className="mt-1 text-sm text-muted-foreground">Process released studies and update imaging status.</p></Link><Link to="/department-queue" className="card-medical p-5"><p className="font-semibold">Acquisition queue</p><p className="mt-1 text-sm text-muted-foreground">Coordinate studies ready for acquisition.</p></Link><Link to="/notifications" className="card-medical p-5"><p className="font-semibold">Notifications</p><p className="mt-1 text-sm text-muted-foreground">Review operational and critical alerts.</p></Link></div></div>;
}