import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { cn } from '@/lib/utils';
import { Activity, BarChart3, Baby, BedDouble, Calendar, CalendarClock, ChevronLeft, ChevronRight, ClipboardList, Cloud, CreditCard, Database, Droplets, Eye, FileText, FlaskConical, HeartPulse, LayoutDashboard, LogOut, Pill, Receipt, Scissors, ShieldCheck, Siren, Smile, Stethoscope, Syringe, Upload, UserCog, Users, Utensils, Video } from 'lucide-react';

interface NavItem { icon: React.ElementType; label: string; href: string }
interface SidebarProps { collapsed: boolean; onToggle: () => void }
const clinical: NavItem = { icon: Stethoscope, label: 'Clinical Operations', href: '/clinical-operations' };
const ward: NavItem = { icon: BedDouble, label: 'Ward & Bed Board', href: '/ward-bed-board' };
const handover: NavItem = { icon: ClipboardList, label: 'Nursing Handover', href: '/nursing-handover' };
const mar: NavItem = { icon: Syringe, label: 'Medication Administration', href: '/medications' };
const claims: NavItem = { icon: ShieldCheck, label: 'Insurance Claims', href: '/insurance-claims' };
const emergency: NavItem = { icon: Siren, label: 'Emergency Board', href: '/emergency-board' };
const theatre: NavItem = { icon: CalendarClock, label: 'Theatre Board', href: '/theatre-board' };
const transfusion: NavItem = { icon: Droplets, label: 'Transfusion Board', href: '/transfusion-board' };
const reports: NavItem = { icon: BarChart3, label: 'Reports Center', href: '/reports' };
const reportSubmissions: NavItem = { icon: ClipboardList, label: 'Submission Dashboard', href: '/reports/submissions' };
const roleNavItems: Record<string, NavItem[]> = {
  admin: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Users, label: 'Patients', href: '/patients' }, { icon: ClipboardList, label: 'Registration', href: '/registration' }, { icon: Calendar, label: 'Appointments', href: '/appointments' }, { icon: HeartPulse, label: 'Triage', href: '/vitals' }, { icon: Stethoscope, label: 'Encounters', href: '/encounters' }, clinical, ward, handover, emergency, theatre, transfusion, claims, reports, reportSubmissions, { icon: CreditCard, label: 'Accounts Approvals', href: '/accounts-approvals' }, { icon: ClipboardList, label: 'Department Queue', href: '/department-queue' }, { icon: FlaskConical, label: 'Laboratory', href: '/laboratory' }, { icon: Pill, label: 'Pharmacy', href: '/pharmacy' }, mar, { icon: CreditCard, label: 'Billing', href: '/billing' }, { icon: Baby, label: 'Maternity', href: '/maternity' }, { icon: Video, label: 'Telemedicine', href: '/telemedicine' }, { icon: ShieldCheck, label: 'AI Clinical Hub', href: '/ai-clinical' }, { icon: UserCog, label: 'Manage Users', href: '/admin/users' }, { icon: Database, label: 'System Library', href: '/admin/system' }, { icon: Cloud, label: 'Offline Synchronization', href: '/admin/offline-sync' }, { icon: Upload, label: 'Data Import', href: '/admin/data-import' }],
  practitioner: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Calendar, label: 'Appointments', href: '/appointments' }, { icon: Users, label: 'Patients', href: '/patients' }, { icon: Stethoscope, label: 'Encounters', href: '/encounters' }, clinical, emergency, theatre, transfusion, { icon: ClipboardList, label: 'Department Queue', href: '/department-queue' }, { icon: Smile, label: 'Dental', href: '/dental' }, { icon: Scissors, label: 'Procedure Notes', href: '/procedures' }, { icon: Activity, label: 'Anesthesia', href: '/anesthesia' }, { icon: FlaskConical, label: 'Laboratory', href: '/laboratory' }, { icon: Pill, label: 'Prescriptions', href: '/pharmacy' }, mar, { icon: Video, label: 'Telemedicine', href: '/telemedicine' }, { icon: Baby, label: 'Fertility', href: '/fertility' }, { icon: Eye, label: 'Ophthalmology', href: '/ophthalmology' }, { icon: ShieldCheck, label: 'AI Clinical Hub', href: '/ai-clinical' }],
  nurse: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Users, label: 'Patients', href: '/patients' }, { icon: HeartPulse, label: 'Vitals & Triage', href: '/vitals' }, { icon: Stethoscope, label: 'Encounters', href: '/encounters' }, clinical, ward, handover, emergency, theatre, transfusion, { icon: BedDouble, label: 'Inpatients', href: '/inpatients' }, mar, { icon: Utensils, label: 'Meal Orders', href: '/menu' }],
  specialist_nurse: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Users, label: 'Patients', href: '/patients' }, { icon: Calendar, label: 'Appointments', href: '/appointments' }, { icon: HeartPulse, label: 'Vitals & Triage', href: '/vitals' }, { icon: Stethoscope, label: 'Encounters', href: '/encounters' }, clinical, ward, handover, emergency, theatre, transfusion, { icon: BedDouble, label: 'Inpatients', href: '/inpatients' }, mar, { icon: ShieldCheck, label: 'AI Clinical Hub', href: '/ai-clinical' }],
  midwife: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Baby, label: 'Maternity', href: '/maternity' }, { icon: Baby, label: 'Fertility', href: '/fertility' }, { icon: BedDouble, label: 'Admissions', href: '/admissions' }, clinical, handover, emergency, theatre, transfusion, { icon: HeartPulse, label: 'Vitals', href: '/vitals' }, mar],
  front_desk: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Users, label: 'Patients', href: '/patients' }, { icon: ClipboardList, label: 'Registration', href: '/registration' }, { icon: Calendar, label: 'Appointments', href: '/appointments' }, { icon: HeartPulse, label: 'Triage', href: '/vitals' }, clinical, { icon: CreditCard, label: 'Billing', href: '/billing' }],
  accountant: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: CreditCard, label: 'Billing', href: '/billing' }, claims, { icon: ShieldCheck, label: 'Accounts Approvals', href: '/accounts-approvals' }, { icon: Receipt, label: 'Invoices', href: '/billing' }, clinical, { icon: ClipboardList, label: 'Financial Reports', href: '/financial-reports' }],
  lab_technician: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: ClipboardList, label: 'Department Queue', href: '/department-queue' }, { icon: FlaskConical, label: 'Laboratory', href: '/laboratory' }, { icon: Upload, label: 'Outside Lab Uploads', href: '/outside-lab' }, { icon: ClipboardList, label: 'Reports', href: '/reports' }],
  pharmacist: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: ClipboardList, label: 'Department Queue', href: '/department-queue' }, { icon: Pill, label: 'Pharmacy / Dispensing', href: '/pharmacy' }, mar, { icon: ClipboardList, label: 'Inventory', href: '/inventory' }, { icon: FileText, label: 'Stock Alerts', href: '/stock-alerts' }],
  canteen: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: Utensils, label: 'Menu', href: '/menu' }, { icon: ClipboardList, label: 'Orders', href: '/orders' }, { icon: Users, label: 'Dietary Plans', href: '/dietary-plans' }],
  patient: [{ icon: LayoutDashboard, label: 'Dashboard', href: '/dashboard' }, { icon: FileText, label: 'My Portal', href: '/patient-portal' }, { icon: Calendar, label: 'My Appointments', href: '/appointments' }, { icon: Video, label: 'My Telemedicine', href: '/telemedicine' }, { icon: CreditCard, label: 'My Billing', href: '/billing' }],
};

export default function Sidebar({ collapsed, onToggle }: SidebarProps) {
  const { user, logout } = useAuth();
  const location = useLocation();
  if (!user) return null;
  const navItems = roleNavItems[user.role] || roleNavItems.patient;
  return <aside className={cn('fixed left-0 top-0 z-40 flex h-screen flex-col sidebar-gradient transition-[width] duration-300 max-md:w-20', collapsed ? 'w-20' : 'w-64')}>
    <div className="flex items-center justify-between border-b border-sidebar-border p-4">
      {!collapsed ? <div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-sidebar-primary"><HeartPulse className="h-6 w-6 text-sidebar-primary-foreground" /></div><div className="min-w-0 max-md:hidden"><h1 className="font-heading text-lg font-bold text-sidebar-foreground">Harmony Health Hub</h1><p className="truncate text-xs text-sidebar-foreground/60">Healthcare Management System</p></div></div> : <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-sidebar-primary"><HeartPulse className="h-6 w-6 text-sidebar-primary-foreground" /></div>}
      <button type="button" onClick={onToggle} className="rounded-md p-1 text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-foreground" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button>
    </div>
    <nav className="flex-1 overflow-y-auto p-3 scrollbar-none"><ul className="space-y-1">{navItems.map((item) => { const active = location.pathname === item.href; return <li key={item.label + item.href}><Link to={item.href} title={collapsed ? item.label : undefined} className={cn(active ? 'nav-link-active' : 'nav-link', collapsed && 'justify-center px-2')}><item.icon className="h-5 w-5 shrink-0" />{!collapsed && <span className="min-w-0 flex-1 truncate">{item.label}</span>}</Link></li>; })}</ul></nav>
    <div className="border-t border-sidebar-border p-3">{!collapsed && <div className="mb-2 flex min-w-0 items-center gap-3 px-3 py-2"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-sidebar-accent font-medium text-sidebar-foreground">{(user.firstName?.[0] || user.email[0]).toUpperCase()}{(user.lastName?.[0] || '').toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-sidebar-foreground">{user.firstName} {user.lastName}</p><p className="truncate text-xs capitalize text-sidebar-foreground/60">{user.role}</p></div></div>}<button type="button" onClick={() => void logout()} title="Sign out" className={cn('nav-link w-full', collapsed && 'justify-center px-2')}><LogOut className="h-5 w-5 shrink-0" />{!collapsed && <span>Sign out</span>}</button></div>
  </aside>;
}
