import { useEffect, useState } from 'react';
import { Activity, BedDouble, ClipboardList, Droplets, ShieldCheck, Siren, Stethoscope } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

type Tab = 'capacity'|'nursing'|'emergency'|'theatre'|'transfusion'|'insurance';
type Patient={id:string;patient_code:string;first_name:string;last_name:string};
const tabs:[Tab,string,React.ElementType][]=[['capacity','Ward & Beds',BedDouble],['nursing','Nursing',ClipboardList],['emergency','Emergency',Siren],['theatre','Theatre',Stethoscope],['transfusion','Transfusion',Droplets],['insurance','Insurance',ShieldCheck]];
export default function ClinicalOperations(){
 const {user}=useAuth(); const [tab,setTab]=useState<Tab>('capacity'); const [patients,setPatients]=useState<Patient[]>([]); const [rows,setRows]=useState<any[]>([]); const [patientId,setPatientId]=useState(''); const [busy,setBusy]=useState(false); const [form,setForm]=useState<Record<string,string>>({});
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const table=tab==='capacity'?'ward_units':tab==='nursing'?'nursing_care_plans':tab==='emergency'?'emergency_cases':tab==='theatre'?'theatre_cases':tab==='transfusion'?'transfusion_records':'insurance_claims';
 const load=async()=>{const [{data:p},{data:r,error}]=await Promise.all([supabase.from('patients').select('id,patient_code,first_name,last_name').order('created_at',{ascending:false}).limit(300),supabase.from(table as never).select('*').order('created_at',{ascending:false}).limit(50)]);setPatients((p??[]) as Patient[]);if(error)toast({title:'Unable to load records',description:error.message,variant:'destructive'});setRows((r??[]) as any[])};
 useEffect(()=>{void load()},[tab]);
 const save=async()=>{if(!user||busy)return;setBusy(true);try{let payload:any={};if(tab==='capacity'){if(!form.name||!form.code)throw new Error('Ward name and code are required.');payload={name:form.name,code:form.code,specialty:form.specialty||null};}
 else {if(!patientId)throw new Error('Select a patient first.');if(tab==='nursing'){if(!form.problem||!form.goal||!form.interventions)throw new Error('Problem, goal and interventions are required.');payload={patient_id:patientId,problem:form.problem,goal:form.goal,interventions:form.interventions,priority:form.priority||'routine',created_by:user.id};}
 if(tab==='emergency'){if(!form.complaint)throw new Error('Chief complaint is required.');payload={patient_id:patientId,chief_complaint:form.complaint,acuity:form.acuity||'urgent',arrival_mode:form.arrival_mode||'walk_in',assigned_officer:user.id,status:'triage'};}
 if(tab==='theatre'){if(!form.procedure_name||!form.scheduled_start)throw new Error('Procedure and scheduled start are required.');payload={patient_id:patientId,procedure_name:form.procedure_name,theatre_name:form.theatre_name||null,scheduled_start:form.scheduled_start,urgency:form.urgency||'elective',surgeon_id:user.id,created_by:user.id,status:'requested'};}
 if(tab==='transfusion'){if(!form.blood_product||!form.unit_identifier)throw new Error('Blood product and unit identifier are required.');payload={patient_id:patientId,blood_product:form.blood_product,unit_identifier:form.unit_identifier,blood_group:form.blood_group||null,consent_confirmed:form.consent==='true',administered_by:user.id,status:'planned'};}
 if(tab==='insurance'){if(!form.payer_name||!form.amount_claimed)throw new Error('Payer and claimed amount are required.');payload={patient_id:patientId,payer_name:form.payer_name,member_number:form.member_number||null,amount_claimed:Number(form.amount_claimed),created_by:user.id,status:'draft'};}}
 const {error}=await supabase.from(table as never).insert(payload as never);if(error)throw error;toast({title:'Saved',description:'The record was created successfully.'});setForm({});setPatientId('');await load();}catch(e){toast({title:'Save failed',description:e instanceof Error?e.message:'Please review the form.',variant:'destructive'})}finally{setBusy(false)}};
 const selected=patients.find(p=>p.id===patientId);
 return <div className="space-y-6"><div><h1 className="text-2xl font-heading font-bold">Clinical Operations</h1><p className="text-sm text-muted-foreground">Enterprise workflows for inpatient capacity, nursing continuity, emergency care, theatre, transfusion and insurance.</p></div>
 <div className="grid grid-cols-2 md:grid-cols-6 gap-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setForm({})}} className={`rounded-lg border p-3 text-left text-sm ${tab===id?'bg-primary text-primary-foreground':'bg-card hover:bg-muted'}`}><Icon className="w-5 h-5 mb-2"/>{label}</button>)}</div>
 <div className="rounded-xl border bg-card p-5 space-y-4">{tab!=='capacity'&&<select value={patientId} onChange={e=>setPatientId(e.target.value)} className="w-full rounded-md border bg-background p-2"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.patient_code} — {p.first_name} {p.last_name}</option>)}</select>}
 {tab==='capacity'&&<div className="grid md:grid-cols-3 gap-3"><input placeholder="Ward name" value={form.name||''} onChange={e=>set('name',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Ward code" value={form.code||''} onChange={e=>set('code',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Specialty" value={form.specialty||''} onChange={e=>set('specialty',e.target.value)} className="rounded-md border bg-background p-2"/></div>}
 {tab==='nursing'&&<div className="grid gap-3"><input placeholder="Nursing problem" value={form.problem||''} onChange={e=>set('problem',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Goal / expected outcome" value={form.goal||''} onChange={e=>set('goal',e.target.value)} className="rounded-md border bg-background p-2"/><textarea placeholder="Interventions" value={form.interventions||''} onChange={e=>set('interventions',e.target.value)} className="rounded-md border bg-background p-2"/><select value={form.priority||'routine'} onChange={e=>set('priority',e.target.value)} className="rounded-md border bg-background p-2"><option>routine</option><option>high</option><option>critical</option></select></div>}
 {tab==='emergency'&&<div className="grid md:grid-cols-3 gap-3"><textarea placeholder="Chief complaint" value={form.complaint||''} onChange={e=>set('complaint',e.target.value)} className="rounded-md border bg-background p-2"/><select value={form.acuity||'urgent'} onChange={e=>set('acuity',e.target.value)} className="rounded-md border bg-background p-2"><option>resuscitation</option><option>emergency</option><option>urgent</option><option>less_urgent</option><option>non_urgent</option></select><select value={form.arrival_mode||'walk_in'} onChange={e=>set('arrival_mode',e.target.value)} className="rounded-md border bg-background p-2"><option>walk_in</option><option>ambulance</option><option>referral</option><option>other</option></select></div>}
 {tab==='theatre'&&<div className="grid md:grid-cols-3 gap-3"><input placeholder="Procedure name" value={form.procedure_name||''} onChange={e=>set('procedure_name',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Theatre name" value={form.theatre_name||''} onChange={e=>set('theatre_name',e.target.value)} className="rounded-md border bg-background p-2"/><input type="datetime-local" value={form.scheduled_start||''} onChange={e=>set('scheduled_start',e.target.value)} className="rounded-md border bg-background p-2"/></div>}
 {tab==='transfusion'&&<div className="grid md:grid-cols-3 gap-3"><input placeholder="Blood product" value={form.blood_product||''} onChange={e=>set('blood_product',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Unit identifier" value={form.unit_identifier||''} onChange={e=>set('unit_identifier',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Documented blood group" value={form.blood_group||''} onChange={e=>set('blood_group',e.target.value)} className="rounded-md border bg-background p-2"/></div>}
 {tab==='insurance'&&<div className="grid md:grid-cols-3 gap-3"><input placeholder="Payer / insurer" value={form.payer_name||''} onChange={e=>set('payer_name',e.target.value)} className="rounded-md border bg-background p-2"/><input placeholder="Member number" value={form.member_number||''} onChange={e=>set('member_number',e.target.value)} className="rounded-md border bg-background p-2"/><input type="number" min="0" placeholder="Amount claimed" value={form.amount_claimed||''} onChange={e=>set('amount_claimed',e.target.value)} className="rounded-md border bg-background p-2"/></div>}
 <button disabled={busy} onClick={save} className="rounded-md bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50">{busy?'Saving…':'Save record'}</button></div>
 <div className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2 mb-4"><Activity className="w-5 h-5"/><h2 className="font-semibold">Recent records</h2></div>{rows.length===0?<p className="text-sm text-muted-foreground">No records yet.</p>:<div className="space-y-2">{rows.slice(0,10).map((r,i)=><div key={r.id||i} className="rounded-lg border p-3 text-sm"><div className="font-medium">{r.name||r.problem||r.chief_complaint||r.procedure_name||r.blood_product||r.payer_name||'Operational record'}</div><div className="text-muted-foreground">{r.status||r.priority||r.urgency||'Recorded'} · {r.created_at?new Date(r.created_at).toLocaleString():'—'}{selected?' · '+selected.patient_code:''}</div></div>)}</div>}</div>
 <p className="text-xs text-muted-foreground">Only documented information is stored. The system does not infer diagnoses, compatibility or treatment decisions.</p></div>;
}