import { useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
type Claim={id:string;patient_id:string;payer_name:string;member_number:string|null;claim_number:string;amount_claimed:number;amount_approved:number;amount_paid:number;status:string;rejection_reason:string|null;service_start_date:string|null;service_end_date:string|null;created_at:string};
type Patient={id:string;patient_code:string;first_name:string;last_name:string};
const statuses=['submitted','acknowledged','under_review','approved','partially_approved','rejected','paid','resubmission_required','voided'];
export default function InsuranceClaims(){const{toast}=useToast();const[claims,setClaims]=useState<Claim[]>([]);const[patients,setPatients]=useState<Patient[]>([]);const[busy,setBusy]=useState(false);const[filter,setFilter]=useState('all');
const load=async()=>{const[p,c]=await Promise.all([supabase.from('patients').select('id,patient_code,first_name,last_name').limit(500),supabase.from('insurance_claims').select('id,patient_id,payer_name,member_number,claim_number,amount_claimed,amount_approved,amount_paid,status,rejection_reason,service_start_date,service_end_date,created_at').order('created_at',{ascending:false}).limit(100)]);if(p.error||c.error)toast({title:'Unable to load claims',description:(p.error||c.error)?.message,variant:'destructive'});setPatients((p.data??[])as Patient[]);setClaims((c.data??[])as Claim[])};useEffect(()=>{void load()},[]);
const transition=async(id:string,status:string)=>{setBusy(true);const{error}=await supabase.rpc('transition_insurance_claim',{_claim_id:id,_to_status:status,_notes:status==='rejected'?'Claim rejected during review':'Status updated from claims queue'}as never);setBusy(false);if(error)toast({title:'Claim transition failed',description:error.message,variant:'destructive'});else{toast({title:'Claim status updated'});void load()}};
const patient=(id:string)=>{const p=patients.find(x=>x.id===id);return p?`${p.patient_code} — ${p.first_name} ${p.last_name}`:'Patient'};const visible=filter==='all'?claims:claims.filter(c=>c.status===filter);
return <div className="space-y-6"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-heading font-bold">Insurance Claims</h1><p className="text-sm text-muted-foreground">Financial claim lifecycle, approvals, rejection and resubmission control.</p></div><button onClick={()=>void load()} className="rounded-md border p-2" aria-label="Refresh"><RefreshCw className="h-4 w-4"/></button></div><div className="flex flex-wrap gap-2 items-center"><ShieldCheck className="h-5 w-5"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-md border bg-background p-2"><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><span className="text-sm text-muted-foreground">{visible.length} claim{visible.length===1?'':'s'}</span></div><div className="grid gap-3">{visible.map(c=><article key={c.id} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{c.claim_number}</h2><p className="text-sm">{patient(c.patient_id)} · {c.payer_name}</p><p className="text-xs text-muted-foreground">{c.status} · claimed {Number(c.amount_claimed||0).toLocaleString()}</p></div><select disabled={busy||c.status==='paid'||c.status==='voided'} value="" onChange={e=>{if(e.target.value)void transition(c.id,e.target.value)}} className="rounded-md border bg-background px-2 py-1 text-sm"><option value="">Change status…</option>{statuses.filter(s=>s!==c.status).map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-2 text-xs"><div>Approved: {Number(c.amount_approved||0).toLocaleString()}</div><div>Paid: {Number(c.amount_paid||0).toLocaleString()}</div><div>Member: {c.member_number||'Not recorded'}</div><div>Service: {c.service_start_date||'—'}{c.service_end_date?` → ${c.service_end_date}`:''}</div></div>{c.rejection_reason&&<p className="mt-2 text-xs text-destructive">Rejection: {c.rejection_reason}</p>}</article>)}{visible.length===0&&<p className="text-sm text-muted-foreground">No claims match the selected status.</p>}</div></div>}
