import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { AlertTriangle, Baby, Plus, RefreshCw } from 'lucide-react';

type Patient = { id:string; first_name:string; last_name:string; patient_code:string };
type Episode = { id:string; patient_id:string; gravida:number|null; para:number|null; lmp:string|null; edd:string|null; risk_level:string; status:string; notes:string|null; created_at:string };
type Observation = { id:string; observed_at:string; blood_pressure:string|null; pulse:number|null; temperature:number|null; fetal_heart_rate:number|null; contractions_per_10_min:number|null; cervical_dilation_cm:number|null; effacement_percent:number|null; station:string|null; membrane_status:string|null; notes:string|null };
const db = supabase as any;
export default function Maternity(){
 const [patients,setPatients]=useState<Patient[]>([]),[episodes,setEpisodes]=useState<Episode[]>([]),[observations,setObservations]=useState<Observation[]>([]);
 const [patientId,setPatientId]=useState(''),[episodeId,setEpisodeId]=useState(''),[risk,setRisk]=useState('routine'),[status,setStatus]=useState('antenatal');
 const [gravida,setGravida]=useState(''),[para,setPara]=useState(''),[lmp,setLmp]=useState(''),[edd,setEdd]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 const [obs,setObs]=useState({blood_pressure:'',pulse:'',temperature:'',fetal_heart_rate:'',contractions_per_10_min:'',cervical_dilation_cm:'',effacement_percent:'',station:'',membrane_status:'',notes:''});
 const loadObservations=async(id:string)=>{const {data,error}=await supabase.from('maternity_observations').select('*').eq('episode_id',id).order('observed_at',{ascending:false}).limit(20);if(error)setMessage(error.message);else setObservations((data??[]) as Observation[])};
 const load=async()=>{setLoading(true);const [{data:ps,error:pe},{data:es,error:ee}]=await Promise.all([supabase.from('patients').select('id,first_name,last_name,patient_code').order('first_name').limit(1000),supabase.from('maternity_episodes').select('*').order('created_at',{ascending:false}).limit(200)]);if(pe||ee){setMessage(pe?.message??ee?.message??'Unable to load maternity records.');setLoading(false);return}setPatients((ps??[]) as Patient[]);setEpisodes((es??[]) as Episode[]);const selected=episodeId||((es??[])[0] as Episode|undefined)?.id||'';if(selected){setEpisodeId(selected);await loadObservations(selected)}setLoading(false)};
 useEffect(()=>{void load()},[]);
 const selected=useMemo(()=>episodes.find(e=>e.id===episodeId),[episodes,episodeId]);
 const pname=(id:string)=>{const p=patients.find(x=>x.id===id);return p?`${p.first_name} ${p.last_name} (${p.patient_code})`:id};
 const createEpisode=async()=>{if(!patientId)return setMessage('Select a patient first.');setLoading(true);const {data,error}=await db.rpc('create_maternity_episode_workflow',{_patient_id:patientId,_gravida:gravida?Number(gravida):null,_para:para?Number(para):null,_lmp:lmp||null,_edd:edd||null,_risk_level:risk,_status:status,_notes:notes||null});if(error)setMessage(error.message);else{setMessage('Maternity episode created.');setPatientId('');setGravida('');setPara('');setLmp('');setEdd('');setNotes('');await load();if(data?.episode_id)setEpisodeId(data.episode_id)}setLoading(false)};
 const addObservation=async()=>{if(!episodeId)return setMessage('Select a maternity episode first.');setLoading(true);const {data,error}=await db.rpc('record_maternity_observation_workflow',{_episode_id:episodeId,_blood_pressure:obs.blood_pressure||null,_pulse:obs.pulse?Number(obs.pulse):null,_temperature:obs.temperature?Number(obs.temperature):null,_fetal_heart_rate:obs.fetal_heart_rate?Number(obs.fetal_heart_rate):null,_contractions_per_10_min:obs.contractions_per_10_min?Number(obs.contractions_per_10_min):null,_cervical_dilation_cm:obs.cervical_dilation_cm?Number(obs.cervical_dilation_cm):null,_effacement_percent:obs.effacement_percent?Number(obs.effacement_percent):null,_station:obs.station||null,_membrane_status:obs.membrane_status||null,_notes:obs.notes||null});if(error)setMessage(error.message);else{setMessage('Observation recorded.');setObs({blood_pressure:'',pulse:'',temperature:'',fetal_heart_rate:'',contractions_per_10_min:'',cervical_dilation_cm:'',effacement_percent:'',station:'',membrane_status:'',notes:''});await loadObservations(data?.episode_id??episodeId)}setLoading(false)};
 return <div className="space-y-6 animate-fade-in"><header><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><Baby className="w-6 h-6 text-primary"/>Maternity Services</h1><p className="text-muted-foreground">Antenatal, labour and postpartum episode tracking.</p></header>{message&&<div className="card-medical p-3 text-sm">{message}</div>}<div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]">
 <section className="card-medical rounded-3xl p-5 space-y-4"><h2 className="font-semibold">Open maternity episode</h2><select className="input-medical w-full" value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name} — {p.patient_code}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="number" min="0" className="input-medical" placeholder="Gravida" value={gravida} onChange={e=>setGravida(e.target.value)}/><input type="number" min="0" className="input-medical" placeholder="Para" value={para} onChange={e=>setPara(e.target.value)}/></div><div className="grid grid-cols-2 gap-3"><input type="date" className="input-medical" value={lmp} onChange={e=>setLmp(e.target.value)}/><input type="date" className="input-medical" value={edd} onChange={e=>setEdd(e.target.value)}/></div><div className="grid grid-cols-2 gap-3"><select className="input-medical" value={risk} onChange={e=>setRisk(e.target.value)}><option value="routine">Routine</option><option value="high">High risk</option><option value="critical">Critical</option></select><select className="input-medical" value={status} onChange={e=>setStatus(e.target.value)}><option value="antenatal">Antenatal</option><option value="labour">Labour</option><option value="postpartum">Postpartum</option></select></div><textarea className="input-medical w-full min-h-20" placeholder="Clinical notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="btn-primary w-full" onClick={()=>void createEpisode()} disabled={loading}><Plus className="inline w-4 h-4 mr-2"/>Create episode</button></section>
 <section className="space-y-4"><div className="card-medical rounded-3xl p-5"><div className="flex justify-between"><h2 className="font-semibold">Episodes</h2><button className="btn-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw className="w-4 h-4"/></button></div><div className="mt-4 space-y-2 max-h-64 overflow-auto">{episodes.map(e=><button key={e.id} onClick={()=>{setEpisodeId(e.id);void loadObservations(e.id)}} className={`w-full text-left rounded-xl border p-3 ${episodeId===e.id?'border-primary bg-primary/5':'border-border'}`}><div className="flex justify-between gap-2"><span className="font-medium truncate">{pname(e.patient_id)}</span><span className="text-xs shrink-0">{e.risk_level}</span></div><div className="text-xs text-muted-foreground">{e.status} · EDD {e.edd??'not recorded'}</div></button>)}</div></div>
 {selected&&<div className="card-medical rounded-3xl p-5 space-y-4"><div className="flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-warning"/><span className="font-semibold">Current episode</span></div><p className="text-sm">{pname(selected.patient_id)} · G{selected.gravida??'—'} P{selected.para??'—'} · {selected.risk_level}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{(['blood_pressure','pulse','temperature','fetal_heart_rate','contractions_per_10_min','cervical_dilation_cm','effacement_percent','station'] as const).map(k=><input key={k} className="input-medical" placeholder={k.replaceAll('_',' ')} value={obs[k]} onChange={e=>setObs({...obs,[k]:e.target.value})}/>)}</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><input className="input-medical" placeholder="Membrane status" value={obs.membrane_status} onChange={e=>setObs({...obs,membrane_status:e.target.value})}/><input className="input-medical" placeholder="Observation notes" value={obs.notes} onChange={e=>setObs({...obs,notes:e.target.value})}/></div><button className="btn-primary" onClick={()=>void addObservation()} disabled={loading}>Record observation</button></div>}
 {observations.length>0&&<div className="card-medical rounded-3xl p-5"><h2 className="font-semibold mb-3">Recent observations</h2>{observations.map(o=><div key={o.id} className="border-b border-border py-2 text-sm"><div className="flex justify-between gap-2"><span>{new Date(o.observed_at).toLocaleString()}</span><span>FHR {o.fetal_heart_rate??'—'}</span></div><div className="text-muted-foreground">BP {o.blood_pressure??'—'} · Pulse {o.pulse??'—'} · Dilation {o.cervical_dilation_cm??'—'} cm · {o.membrane_status??'membranes not recorded'}</div></div>)}</div>}</section></div></div>;
}
