import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { BellRing, Save } from 'lucide-react';

const channels=['in_app','email','sms','push','whatsapp'] as const;
const categories=['appointments','medication','clinical','billing','reviews','marketing','greetings','campaigns','wellness'] as const;

export default function NotificationPreferences(){
 const {user}=useAuth(); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [p,setP]=useState<any>({locale:'en-GH',timezone:'Africa/Accra',quiet_hours_start:'22:00',quiet_hours_end:'07:00',pause_non_critical:false,channel_preferences:{in_app:true,email:false,sms:false,push:false,whatsapp:false},category_preferences:{}});
 useEffect(()=>{if(!user)return;void (async()=>{const {data}=await supabase.rpc('ensure_notification_preferences',{_user_id:user.id});if(data)setP((x:any)=>({...x,...data,channel_preferences:{...x.channel_preferences,...(data.channel_preferences??{})},category_preferences:{...x.category_preferences,...(data.category_preferences??{})}}));setLoading(false);})();},[user]);
 if(!user||loading)return <div className="p-6">Loading notification preferences…</div>;
 const toggle=(group:'channel_preferences'|'category_preferences',key:string)=>setP((x:any)=>({...x,[group]:{...x[group],[key]:!x[group]?.[key]}}));
 const save=async()=>{setSaving(true);const {error}=await (supabase as any).from('user_notification_preferences').upsert({user_id:user.id,locale:p.locale,timezone:p.timezone,quiet_hours_start:p.quiet_hours_start,quiet_hours_end:p.quiet_hours_end,pause_non_critical:p.pause_non_critical,channel_preferences:p.channel_preferences,category_preferences:p.category_preferences,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(!error){for(const c of channels){const {error:consentError}=await supabase.rpc('record_notification_consent',{_channel:c,_category:'all',_granted:p.channel_preferences?.[c]===true,_consent_version:'notification-preferences-v1',_user_agent:navigator.userAgent});if(consentError){window.alert(consentError.message);break;}}}setSaving(false);if(error)window.alert(error.message);};
 return <div className="space-y-6 max-w-3xl"><div><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><BellRing className="w-6 h-6 text-primary"/> Notification preferences</h1><p className="text-muted-foreground mt-1">Control non-critical notification channels, categories, language and quiet hours.</p></div>
 <section className="card-medical p-5 space-y-4"><h2 className="font-semibold">Channels</h2>{channels.map(c=><label key={c} className="flex items-center justify-between border-b border-border py-3"><span className="capitalize">{c.replace('_',' ')}</span><input type="checkbox" checked={p.channel_preferences?.[c]===true} onChange={()=>toggle('channel_preferences',c)} disabled={c==='in_app'}/></label>)}</section>
 <section className="card-medical p-5 space-y-4"><h2 className="font-semibold">Categories</h2><div className="grid sm:grid-cols-2 gap-3">{categories.map(c=><label key={c} className="flex items-center gap-2"><input type="checkbox" checked={p.category_preferences?.[c]!==false} onChange={()=>toggle('category_preferences',c)}/><span className="capitalize">{c}</span></label>)}</div></section>
 <section className="card-medical p-5 space-y-4"><h2 className="font-semibold">Timing & language</h2><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">Language<input className="input-medical mt-1 w-full" value={p.locale} onChange={e=>setP((x:any)=>({...x,locale:e.target.value}))}/></label><label className="text-sm">Time zone<input className="input-medical mt-1 w-full" value={p.timezone} onChange={e=>setP((x:any)=>({...x,timezone:e.target.value}))}/></label><label className="text-sm">Quiet hours start<input type="time" className="input-medical mt-1 w-full" value={p.quiet_hours_start?.slice(0,5)} onChange={e=>setP((x:any)=>({...x,quiet_hours_start:e.target.value}))}/></label><label className="text-sm">Quiet hours end<input type="time" className="input-medical mt-1 w-full" value={p.quiet_hours_end?.slice(0,5)} onChange={e=>setP((x:any)=>({...x,quiet_hours_end:e.target.value}))}/></label></div><label className="flex items-center gap-2"><input type="checkbox" checked={p.pause_non_critical===true} onChange={e=>setP((x:any)=>({...x,pause_non_critical:e.target.checked}))}/><span>Pause all non-critical notifications</span></label><p className="text-xs text-muted-foreground">Critical clinical alerts follow the clinical escalation policy and are not suppressed by this setting.</p></section>
 <button className="btn-primary inline-flex items-center gap-2" disabled={saving} onClick={()=>void save()}><Save className="w-4 h-4"/>{saving?'Saving…':'Save preferences'}</button></div>;
}