import { useEffect, useState } from 'react';
import { ClipboardCheck, RefreshCw } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

type Patient={id:string;patient_code:string;first_name:string;last_name:string};
type Handover={id:string;patient_id:string;shift_label:string;clinical_summary:string;pending_tasks:string|null;safety_concerns:string|null;escalation_required:boolean;acknowledged_at:string|null;created_at:string};
export default function NursingHandover(){const {user}=useAuth();const [patients,setPatients]=useState<Patient[]>([]);const [rows,setRows]=useState<Handover[]>([]);const [patientId,setPatientId]=useState('');const [form,setForm]=useState({shift_label:'Morning',clinical_summary:'',pending_tasks:'',safety_concerns:'',escalation_required:false});
 const load=async()=>{const [p,h]=await Promise.all([supabase.from('patients').select('id,patient_code,first_name,last_name').order('created_at',{ascending:false}).limit(300),supabase.from('nursing_shift_handovers').select('id,patient_id,shift_label,clinical_summary,pending_tasks,safety_concerns,escalation_required,acknowledged_at,created_at').order('created_at',{ascending:false}).limit(50)]);if(p.error||h.error)toast({title:'Unable to load handovers',description:(p.error||h.error)?.message,variant:'destructive'});setPatients((p.data??[]) as Patient[]);setRows((h.data??[]) as Handover[])};useEffect(()=>{void load()},[]);
 const save=async()=>{if(!user||!patientId||!form.clinical_summary)return;const {error}=await supabase.from('nursing_shift_handovers').insert({patient_id:patientId,outgoing_officer:user.id,shift_label:form.shift_label,clinical_summary:form.clinical_summary,pending_tasks:form.pending_tasks||null,safety_concerns:form.safety_concerns||null,escalation_required:form.escalation_required} as never);if(error)toast({title:'Handover failed',description:error.message,variant:'destructive'});else{toast({title:'Handover recorded'});setPatientId('');setForm({shift_label:'Morning',clinical_summary:'',pending_tasks:'',safety_concerns:'',escalation_required:false});void load()}};
 const ack=async(id:string)=>{const {error}=await supabase.rpc('acknowledge_nursing_handover',{_handover_id:id} as never);if(error)toast({title:'Acknowledgement failed',description:error.message,variant:'destructive'});else{toast({title:'Handover acknowledged'});void load()}};const name=(id:string)=>{const p=patients.find(x=>x.id===id);return p?`${p.patient_code} — ${p.first_name} ${p.last_name}`:'Patient'};
 return <div className="space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-heading font-bold">Nursing Shift Handover</h1><p className="text-sm text-muted-foreground">Structured continuity, pending tasks and safety escalation.</p></div><button onClick={()=>void load()} className="rounded-md border p-2" aria-label="Refresh"><RefreshCw className="w-4 h-4"/></button></div><div className="rounded-xl border bg-card p-4 space-y-3"><select value={patientId} onChange={e=>setPatientId(e.target.value)} className="w-full rounded-md border bg-background p-2"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{name(p.id)}</option>)}</select><div className="grid md:grid-cols-2 gap-3"><select value={form.shift_label} onChange={e=>setForm({...form,shift_label:e.target.value})} className="rounded-md border bg-background p-2"><option>Morning</option><option>Afternoon</option><option>Night</option></select><label className="flex items-center gap-2 rounded-md border p-2"><input type="checkbox" checked={form.escalation_required} onChange={e=>setForm({...form,escalation_required:e.target.checked})}/> Escalation required</label></div><textarea placeholder="Clinical summary" value={form.clinical_summary} onChange={e=>setForm({...form,clinical_summary:e.target.value})} className="w-full rounded-md border bg-background p-2 min-h-24"/><textarea placeholder="Pending tasks" value={form.pending_tasks} onChange={e=>setForm({...form,pending_tasks:e.target.value})} className="w-full rounded-md border bg-background p-2"/><textarea placeholder="Safety concerns" value={form.safety_concerns} onChange={e=>setForm({...form,safety_concerns:e.target.value})} className="w-full rounded-md border bg-background p-2"/><button onClick={()=>void save()} className="rounded-md bg-primary px-4 py-2 text-primary-foreground"><ClipboardCheck className="inline w-4 h-4 mr-1"/>Record handover</button></div><div className="space-y-2">{rows.map(r=><div key={r.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-3"><div><div className="font-medium">{name(r.patient_id)} · {r.shift_label}</div><p className="text-sm mt-1">{r.clinical_summary}</p></div>{r.acknowledged_at?<span className="text-xs text-muted-foreground">Acknowledged</span>:<button onClick={()=>void ack(r.id)} className="rounded-md border px-2 py-1 text-xs">Acknowledge</button>}</div>{r.pending_tasks&&<p className="text-xs mt-2">Tasks: {r.pending_tasks}</p>}{r.safety_concerns&&<p className="text-xs mt-1">Safety: {r.safety_concerns}</p>}</div>)}</div></div>}
