import { useCallback, useEffect, useState } from 'react';
import { CalendarClock, Calculator, Plus, RefreshCw } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Period={id:string;name:string;period_start:string;period_end:string;pay_date:string;status:string};
type Item={id:string;employee_id:string;basic_pay:number;allowances:number;other_earnings:number;statutory_deductions:number;other_deductions:number;gross_pay:number;net_pay:number;employee?:{first_name:string;last_name:string;employee_number:string}};
const db=supabase as any;
async function activeFacilityId(){const{data,error}=await db.rpc('current_user_facility_id');if(error||!data)throw new Error(error?.message||'No active facility is selected.');return data as string}

export default function Payroll(){
 const[periods,setPeriods]=useState<Period[]>([]);const[selected,setSelected]=useState<Period|null>(null);const[items,setItems]=useState<Item[]>([]);const[show,setShow]=useState(false);const[loading,setLoading]=useState(true);
 const[form,setForm]=useState({name:'',period_start:'',period_end:'',pay_date:''});
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await db.from('payroll_periods').select('id,name,period_start,period_end,pay_date,status').order('period_start',{ascending:false});if(error)toast.error(error.message);else setPeriods((data||[]) as Period[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const loadItems=async(p:Period)=>{setSelected(p);const{data,error}=await db.from('payroll_items').select('id,employee_id,basic_pay,allowances,other_earnings,statutory_deductions,other_deductions,gross_pay,net_pay,hr_employees(first_name,last_name,employee_number)').eq('payroll_period_id',p.id);if(error)toast.error(error.message);else setItems((data||[]).map((x:any)=>({...x,employee:x.hr_employees})) as Item[])};
 const create=async()=>{if(!form.name||!form.period_start||!form.period_end||!form.pay_date)return toast.error('All payroll period fields are required.');try{const facility_id=await activeFacilityId();const{error}=await db.from('payroll_periods').insert({...form,facility_id});if(error)throw error;toast.success('Payroll period created.');setShow(false);setForm({name:'',period_start:'',period_end:'',pay_date:''});void load()}catch(e:any){toast.error(e.message||'Unable to create payroll period.')}};
 const generate=async()=>{if(!selected)return;const{data,error}=await db.rpc('generate_payroll_items',{_payroll_period_id:selected.id});if(error)toast.error(error.message);else{toast.success(String(data||0)+' payroll items generated from active employees.');void loadItems(selected)}};
 return <div className='space-y-6 animate-fade-in'>
  <header className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'><div><h1 className='text-2xl font-heading font-bold flex items-center gap-2'><CalendarClock className='h-6 w-6 text-primary'/>Payroll</h1><p className='text-sm text-muted-foreground'>Controlled payroll periods and auditable employee pay calculations. Statutory deductions remain configurable rather than hard-coded.</p></div><div className='flex gap-2'><button className='btn-secondary h-10 w-10 p-0' aria-label='Refresh' onClick={()=>void load()}><RefreshCw className='h-4 w-4'/></button><button className='btn-primary inline-flex gap-2' onClick={()=>setShow(v=>!v)}><Plus className='h-4 w-4'/>New period</button></div></header>
  {show&&<section className='card-medical p-5 space-y-4'><h2 className='font-semibold'>Create payroll period</h2><div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-4'>{([['name','Period name'],['period_start','Start'],['period_end','End'],['pay_date','Pay date']] as const).map(([key,label])=><label key={key} className='text-sm space-y-1'><span>{label}</span><input className='input-medical w-full' type={key==='name'?'text':'date'} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}</div><button className='btn-primary' onClick={()=>void create()}>Create period</button></section>}
  <div className='grid gap-5 lg:grid-cols-[22rem_1fr]'><section className='card-medical overflow-hidden'><div className='border-b p-4 font-semibold'>Payroll periods</div><div className='divide-y'>{loading?<p className='p-6 text-sm text-muted-foreground'>Loading…</p>:periods.map(p=><button key={p.id} type='button' onClick={()=>void loadItems(p)} className={'block w-full p-4 text-left hover:bg-muted/40 '+(selected?.id===p.id?'bg-muted/50':'')}><div className='font-medium'>{p.name}</div><div className='mt-1 text-xs text-muted-foreground'>{p.period_start} → {p.period_end} · Pay {p.pay_date}</div><span className='badge-info mt-2 inline-flex'>{p.status}</span></button>)}{!loading&&!periods.length&&<p className='p-6 text-sm text-muted-foreground'>No payroll periods.</p>}</div></section>
   <section className='card-medical overflow-hidden'><div className='flex items-center justify-between border-b p-4'><div><h2 className='font-semibold'>{selected?.name||'Payroll run'}</h2><p className='text-xs text-muted-foreground'>{items.length} employee lines</p></div>{selected&&<button className='btn-primary inline-flex gap-2' onClick={()=>void generate()}><Calculator className='h-4 w-4'/>Generate from active employees</button>}</div><div className='overflow-x-auto'><table className='table-medical w-full'><thead><tr><th>Employee</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Gross</th><th>Net</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><div className='font-medium'>{i.employee?.first_name} {i.employee?.last_name}</div><div className='text-xs text-muted-foreground'>{i.employee?.employee_number}</div></td><td>GHS {Number(i.basic_pay).toFixed(2)}</td><td>GHS {Number(i.allowances+i.other_earnings).toFixed(2)}</td><td>GHS {Number(i.statutory_deductions+i.other_deductions).toFixed(2)}</td><td>GHS {Number(i.gross_pay).toFixed(2)}</td><td className='font-semibold'>GHS {Number(i.net_pay).toFixed(2)}</td></tr>)}{!items.length&&<tr><td colSpan={6} className='p-10 text-center text-sm text-muted-foreground'>{selected?'Generate payroll lines from active employees.':'Select a payroll period to view its run.'}</td></tr>}</tbody></table></div></section>
  </div>
 </div>;
}