import { useEffect, useState } from 'react';
import { CalendarClock, Phone, Stethoscope, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { playWorkflowSound } from '@/lib/workflowFeedback';

type Referral={referral_id:string;patient_id:string;patient_name:string;telephone:string|null;specialty:string;appointment_date:string|null;referred_at:string;status:string};

export default function SpecialistReferralQueue(){
 const[rows,setRows]=useState<Referral[]>([]);const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const{data,error}=await(supabase as any).rpc('get_pending_specialist_referrals');if(error){toast({title:'Specialist referral queue unavailable',description:error.message,variant:'destructive'});setLoading(false);return}setRows((data??[])as Referral[]);setLoading(false)};
 useEffect(()=>{void load();const ch=supabase.channel('specialist-referral-queue').on('postgres_changes',{event:'*',schema:'public',table:'patient_referrals'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
 const initiate=async(row:Referral)=>{const{error}=await(supabase as any).from('patient_referrals').update({status:'scheduled'}).eq('id',row.referral_id).in('status',['requested','accepted']);if(error){toast({title:'Could not initiate referral',description:error.message,variant:'destructive'});return}playWorkflowSound('success');toast({title:'Specialist appointment initiated',description:`${row.patient_name} · ${row.specialty}`});void load()};
 return <div className="space-y-6 animate-fade-in"><header><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><Stethoscope className="w-6 h-6 text-primary"/>Specialist Referral Queue</h1><p className="text-muted-foreground">Scheduled specialist referrals remain visible until the receiving appointment is initiated and completed.</p></header><section className="card-medical overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><div><b>{rows.length}</b> pending specialist referral{rows.length===1?'':'s'}</div><button className="btn-secondary" onClick={()=>void load()}>Refresh</button></div>{loading?<div className="p-10 text-center text-muted-foreground">Loading referral queue…</div>:rows.length===0?<div className="p-10 text-center text-muted-foreground">No pending specialist referrals.</div>:<div className="divide-y">{rows.map(row=><article key={row.referral_id} className="p-4 grid gap-4 lg:grid-cols-[1.4fr_1fr_1fr_auto] lg:items-center"><div><div className="font-semibold flex items-center gap-2"><UserRound className="w-4 h-4 text-primary"/>{row.patient_name}</div><p className="text-xs text-muted-foreground mt-1">Referred {new Date(row.referred_at).toLocaleString()}</p></div><div><p className="text-xs text-muted-foreground">Telephone</p><p className="text-sm flex items-center gap-1"><Phone className="w-3.5 h-3.5"/>{row.telephone||'Not recorded'}</p></div><div><p className="text-xs text-muted-foreground">Specialist / appointment</p><p className="text-sm font-medium">{row.specialty}</p><p className="text-xs flex items-center gap-1 mt-1"><CalendarClock className="w-3.5 h-3.5"/>{row.appointment_date?new Date(row.appointment_date).toLocaleString():'Date not set'}</p></div><div className="flex gap-2"><Link className="btn-secondary" to={`/patients/${row.patient_id}`}>Patient</Link><button className="btn-primary" onClick={()=>void initiate(row)}>Initiate</button></div></article>)}</div>}</section></div>;
}
