import RefreshButton from '@/components/ui/RefreshButton';
import { useEffect, useState } from 'react';
import { CalendarClock, Phone, RefreshCw, Stethoscope, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { playWorkflowSound } from '@/lib/workflowFeedback';

type Referral={referral_id:string;patient_id:string;patient_name:string;age:number|null;telephone:string|null;specialty:string|null;destination:string|null;reason:string|null;principal_diagnosis:string|null;appointment_date:string|null;referred_at:string;status:string;referral_type:string;source_text:string|null};

export default function SpecialistReferralQueue(){
 const[rows,setRows]=useState<Referral[]>([]);const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);const[dates,setDates]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);const{data,error}=await(supabase as any).rpc('get_pending_specialist_referrals', {});if(error){toast({title:'Specialist referral queue unavailable',description:error.message,variant:'destructive'});setRows([])}else setRows((data??[])as Referral[]);setLoading(false)};
 useEffect(()=>{void load();const ch=supabase.channel('specialist-referral-queue').on('postgres_changes',{event:'*',schema:'public',table:'patient_referrals'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
 const initiate=async(row:Referral)=>{setBusyId(row.referral_id);try{const selectedDate=dates[row.referral_id];if(selectedDate){const{error}=await(supabase as any).rpc('set_patient_referral_appointment_date',{_referral_id:row.referral_id,_appointment_date:new Date(selectedDate).toISOString()});if(error)throw error}const{data,error}=await(supabase as any).rpc('schedule_patient_referral_workflow',{_referral_id:row.referral_id});if(error)throw error;playWorkflowSound('success');toast({title:'Specialist appointment initiated',description:row.patient_name+' · '+(row.specialty||'Physician specialist')+(data?.appointment_date?' · '+new Date(data.appointment_date).toLocaleString():'')});void load()}catch(e:any){playWorkflowSound('critical');toast({title:'Could not initiate specialist appointment',description:e.message,variant:'destructive'})}finally{setBusyId(null)}};
 return <div className='space-y-6 animate-fade-in'><header><div className='flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between'><div><h1 className='text-2xl font-heading font-bold flex items-center gap-2'><Stethoscope className='w-6 h-6 text-primary'/>Specialist Appointment List</h1><p className='text-muted-foreground'>Patients whose clerking sheet indicates a specialist review are consolidated here for appointment initiation.</p></div><RefreshButton onClick={() => void load()} /></div></header>
 <section className='card-medical overflow-hidden'><div className='p-4 border-b'><b>{rows.length}</b> specialist appointment item{rows.length===1?'':'s'}</div>{loading?<div className='p-10 text-center text-muted-foreground'>Loading specialist appointment list…</div>:rows.length===0?<div className='p-10 text-center text-muted-foreground'>No specialist appointments require initiation.</div>:<div className='divide-y'>{rows.map(row=><article key={row.referral_id} className='p-4 grid gap-4 xl:grid-cols-[1.4fr_.7fr_1fr_1.2fr_auto] xl:items-center'><div><div className='font-semibold flex items-center gap-2'><UserRound className='w-4 h-4 text-primary'/>{row.patient_name}</div><p className='text-xs text-muted-foreground mt-1'>{row.age!=null?row.age+' years':'Age not recorded'} · Referred {new Date(row.referred_at).toLocaleDateString()}</p><p className='text-xs mt-2'>{row.principal_diagnosis||'Diagnosis not recorded'}</p></div><div><p className='text-xs text-muted-foreground'>Telephone</p><p className='text-sm flex items-center gap-1'><Phone className='w-3.5 h-3.5'/>{row.telephone||'Not recorded'}</p></div><div><p className='text-xs text-muted-foreground'>Specialist / physician</p><p className='text-sm font-semibold'>{row.specialty||'Physician specialist'}</p><p className='text-xs text-muted-foreground mt-1'>{row.destination||'Specialist Clinic'}</p></div><div><p className='text-xs text-muted-foreground'>Appointment</p><div className='flex items-center gap-2 mt-1'><CalendarClock className='w-4 h-4 text-muted-foreground'/><input type='datetime-local' value={dates[row.referral_id]??(row.appointment_date?new Date(row.appointment_date).toISOString().slice(0,16):'')} onChange={e=>setDates(v=>({...v,[row.referral_id]:e.target.value}))} className='input-medical text-xs'/></div></div><div className='flex gap-2'><Link className='btn-secondary' to={'/patients/'+row.patient_id}>Patient</Link><button className='btn-primary disabled:opacity-50' disabled={busyId===row.referral_id||!(dates[row.referral_id]||row.appointment_date)} onClick={()=>void initiate(row)}>{busyId===row.referral_id?'Scheduling…':'Book appointment'}</button></div></article>)}</div>}</section></div>;
}