CREATE INDEX IF NOT EXISTS idx_encounters_patient ON public.encounters (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_encounters_status ON public.encounters (status);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON public.appointments (patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_sched ON public.appointments (scheduled_at DESC);
CREATE INDEX IF NOT EXISTS idx_vitals_patient ON public.vital_signs (patient_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_lab_orders_patient ON public.lab_orders (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lab_orders_status ON public.lab_orders (status);
CREATE INDEX IF NOT EXISTS idx_lab_results_order ON public.lab_results (lab_order_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_patient ON public.prescriptions (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prescriptions_status ON public.prescriptions (status);
CREATE INDEX IF NOT EXISTS idx_invoices_patient ON public.invoices (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON public.invoice_items (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON public.payments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_patient ON public.payments (patient_id);
CREATE INDEX IF NOT EXISTS idx_diagnoses_encounter ON public.diagnoses (encounter_id);
CREATE INDEX IF NOT EXISTS idx_med_admin_patient ON public.medication_administrations (patient_id, administered_at DESC);
CREATE INDEX IF NOT EXISTS idx_fert_monitoring_cycle ON public.fertility_monitoring (cycle_id, visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON public.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_patients_name ON public.patients (last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_patients_code ON public.patients (patient_code);
CREATE INDEX IF NOT EXISTS idx_outside_docs_patient ON public.outside_lab_documents (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vital_alerts_patient ON public.vital_alerts (patient_id, created_at DESC);