import { ChangeEvent, FormEvent, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, FileCheck2, Heart, Loader2, Printer, Save, Shield, Upload, User, X } from 'lucide-react';
import { toast } from 'sonner';
import { cn, getBarcodeUrl, getQrCodeUrl } from '@/lib/utils';
import { registerPatient } from '@/lib/healthApi';
import { analyzePatientDocument, uploadPatientFile, validatePatientDocument, validateProfilePhoto } from '@/lib/patientDocuments';

interface FormData { patientId:string; membershipType:'permanent'|'temporary'; membershipDuration:'1'|'7'|'30'; registrationReason:string; ghanaCardNumber:string; firstName:string; lastName:string; dateOfBirth:string; gender:string; email:string; phone:string; address:string; city:string; emergencyName:string; emergencyRelation:string; emergencyPhone:string; insuranceProvider:string; policyNumber:string; groupNumber:string; insuranceExpiry:string; bloodType:string; genotype:string; allergies:string; chronicConditions:string; medicalHistory:string }
const emptyForm:FormData={patientId:'',membershipType:'permanent',membershipDuration:'1',registrationReason:'',ghanaCardNumber:'',firstName:'',lastName:'',dateOfBirth:'',gender:'',email:'',phone:'',address:'',city:'',emergencyName:'',emergencyRelation:'',emergencyPhone:'',insuranceProvider:'',policyNumber:'',groupNumber:'',insuranceExpiry:'',bloodType:'',genotype:'',allergies:'',chronicConditions:'',medicalHistory:''};
const sections=[['personal','Personal Information',User],['contact','Contact Details',User],['documents','Documents',Upload],['emergency','Emergency Contact',AlertTriangle],['insurance','Insurance',Shield],['medical','Medical History',Heart]] as const;

export default function PatientRegistration(){
 const navigate=useNavigate(); const[active,setActive]=useState('personal'); const[form,setForm]=useState<FormData>(emptyForm); const[hasInsurance,setHasInsurance]=useState(false); const[profilePhoto,setProfilePhoto]=useState<File|null>(null); const[documents,setDocuments]=useState<File[]>([]); const[analysis,setAnalysis]=useState<Record<string,string[]>>({}); const[registered,setRegistered]=useState<{id:string;code:string;name:string}|null>(null); const[saving,setSaving]=useState(false);
 const update=(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm((v)=>({...v,[e.target.name]:e.target.value}));
 const choosePhoto=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const v=validateProfilePhoto(f);if(!v.valid){toast.error(v.reason);return}setProfilePhoto(f)};
 const chooseDocs=(e:ChangeEvent<HTMLInputElement>)=>{const accepted=Array.from(e.target.files??[]).filter((f)=>{const v=validatePatientDocument(f);if(!v.valid)toast.error(`${f.name}: ${v.reason}`);return v.valid});setDocuments(accepted);e.target.value=''};
 const reset=()=>{setForm({...emptyForm});setHasInsurance(false);setProfilePhoto(null);setDocuments([]);setAnalysis({});setRegistered(null);setActive('personal')};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(saving)return;setSaving(true);try{const patientCode=form.membershipType==='temporary'?`TMP-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`:form.patientId||undefined;const expiry=form.membershipType==='temporary'?new Date(Date.now()+Number(form.membershipDuration)*86400000).toISOString():null;const result=await registerPatient({...form,patientId:patientCode,membershipExpiresAt:expiry});const id=result?.patient?.id;const code=result?.patientId||patientCode;if(!id||!code)throw new Error('Registration succeeded without a patient identifier.');if(profilePhoto)await uploadPatientFile(id,profilePhoto,'profile_photo');for(const doc of documents)await uploadPatientFile(id,doc,'registration_supporting_document');setRegistered({id,code,name:`${form.firstName} ${form.lastName}`});toast.success(`${form.membershipType==='temporary'?'Temporary':'Permanent'} patient ${code} registered.`);try{const{notifyRoles}=await import('@/lib/notifications');await notifyRoles(['front_desk','nurse'],{title:'New patient registered',message:`${form.firstName} ${form.lastName} (${code}) is ready for care.`,severity:'info',category:'other',link:'/vitals',relatedPatientId:id})}catch{ /* notification is best effort */}}catch(error){toast.error(error instanceof Error?error.message:'Could not register patient.')}finally{setSaving(false)}};
 return <div className="animate-fade-in space-y-6"><div className="flex items-center gap-4"><button type="button" onClick={()=>navigate(-1)} className="p-2 rounded-lg hover:bg-muted" aria-label="Go back"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-2xl font-heading font-bold">Patient Registration</h1><p className="text-muted-foreground">Register permanent patients or low-cost temporary visitors for walk-in services.</p></div></div>
 <div className="grid grid-cols-1 lg:grid-cols-4 gap-6"><aside><div className="card-medical p-4 sticky top-24"><nav className="space-y-1">{sections.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setActive(id)} className={cn('w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium text-left',active===id?'bg-primary text-primary-foreground':'hover:bg-muted text-muted-foreground')}><Icon className="h-4 w-4"/>{label}</button>)}</nav></div></aside>
 <form onSubmit={submit} className="lg:col-span-3 space-y-6">{active==='personal'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold flex items-center gap-2"><User className="h-5 w-5 text-primary"/>Patient identity</h2><div className="grid md:grid-cols-2 gap-4"><label className="text-sm space-y-1 md:col-span-2"><span className="font-medium">Registration type</span><select name="membershipType" value={form.membershipType} onChange={update} className="input-medical w-full"><option value="permanent">Permanent registered patient</option><option value="temporary">Temporary / walk-in visitor</option></select></label>{form.membershipType==='temporary'&&<><label className="text-sm space-y-1"><span className="font-medium">Temporary validity</span><select name="membershipDuration" value={form.membershipDuration} onChange={update} className="input-medical w-full"><option value="1">1 day / one-time visit</option><option value="7">7 days / short visit</option><option value="30">30 days / visiting patient</option></select></label><Field label="Reason for visit *" name="registrationReason" value={form.registrationReason} onChange={update} required placeholder="e.g. walk-in laboratory test"/></> }<Field label="First Name *" name="firstName" value={form.firstName} onChange={update} required/><Field label="Last Name *" name="lastName" value={form.lastName} onChange={update} required/><Field label="Date of Birth" name="dateOfBirth" type="date" value={form.dateOfBirth} onChange={update}/><SelectField label="Gender" name="gender" value={form.gender} onChange={update} options={['male','female','other']}/><Field label="Patient ID" name="patientId" value={form.patientId} onChange={update} placeholder="Leave blank for system-generated ID" disabled={form.membershipType==='temporary'}/><Field label="National ID / Ghana Card" name="ghanaCardNumber" value={form.ghanaCardNumber} onChange={update}/><div className="md:col-span-2"><label className="text-sm font-medium">Profile photo</label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto} className="input-medical w-full mt-1"/>{profilePhoto&&<p className="text-xs text-muted-foreground mt-1">{profilePhoto.name}</p>}</div></div>{form.membershipType==='temporary'&&<p className="text-xs rounded-xl bg-primary/5 border border-primary/20 p-3 text-muted-foreground">A temporary membership number is issued so the visitor can pay at Billing and receive the requested service without carrying the cost of a full permanent registration.</p>}</section>}
 {active==='contact'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold">Contact Details</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Email" name="email" type="email" value={form.email} onChange={update}/><Field label="Phone *" name="phone" type="tel" value={form.phone} onChange={update} required/><div className="md:col-span-2"><Field label="Address" name="address" value={form.address} onChange={update}/></div><Field label="City" name="city" value={form.city} onChange={update}/></div></section>}
 {active==='documents'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold flex items-center gap-2"><Upload className="h-5 w-5 text-primary"/>Documents</h2><input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,text/plain" onChange={chooseDocs} className="input-medical w-full"/>{documents.map((file)=><div key={file.name} className="rounded-xl border p-3 flex items-center justify-between gap-3"><span className="text-sm truncate flex items-center gap-2"><FileCheck2 className="w-4 h-4 text-primary"/>{file.name}</span><button type="button" onClick={()=>setDocuments((v)=>v.filter((x)=>x.name!==file.name))}><X className="w-4 h-4"/></button></div>)}</section>}
 {active==='emergency'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-warning"/>Emergency Contact</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Name" name="emergencyName" value={form.emergencyName} onChange={update}/><Field label="Relationship" name="emergencyRelation" value={form.emergencyRelation} onChange={update}/><Field label="Phone" name="emergencyPhone" value={form.emergencyPhone} onChange={update}/></div></section>}
 {active==='insurance'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold flex items-center gap-2"><Shield className="h-5 w-5 text-success"/>Insurance</h2><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" checked={hasInsurance} onChange={e=>setHasInsurance(e.target.checked)}/>Patient has health insurance</label>{hasInsurance&&<div className="grid md:grid-cols-2 gap-4"><Field label="Provider" name="insuranceProvider" value={form.insuranceProvider} onChange={update} required/><Field label="Policy number" name="policyNumber" value={form.policyNumber} onChange={update} required/><Field label="Group number" name="groupNumber" value={form.groupNumber} onChange={update}/><Field label="Expiry" name="insuranceExpiry" type="date" value={form.insuranceExpiry} onChange={update}/></div>}</section>}
 {active==='medical'&&<section className="card-medical p-6 space-y-4"><h2 className="text-lg font-semibold flex items-center gap-2"><Heart className="h-5 w-5 text-critical"/>Medical history</h2><div className="grid md:grid-cols-2 gap-4"><SelectField label="Blood group" name="bloodType" value={form.bloodType} onChange={update} options={['A+','A-','B+','B-','AB+','AB-','O+','O-']}/><Field label="Genotype" name="genotype" value={form.genotype} onChange={update}/><TextAreaField label="Chronic conditions" name="chronicConditions" value={form.chronicConditions} onChange={update}/><TextAreaField label="Known allergies" name="allergies" value={form.allergies} onChange={update}/><div className="md:col-span-2"><TextAreaField label="Medical history" name="medicalHistory" value={form.medicalHistory} onChange={update}/></div></div></section>}
 {registered&&<section className="card-medical p-6 border-primary/20 bg-primary/5"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-primary">Registration complete</p><h2 className="text-xl font-semibold">{registered.name}</h2><p className="text-sm text-muted-foreground">Membership number: {registered.code}</p></div><button type="button" className="btn-secondary" onClick={()=>window.print()}><Printer className="h-4 w-4"/>Print ID</button></div><div className="mt-4 grid md:grid-cols-[160px_1fr] gap-4"><img src={getQrCodeUrl(registered.code)} alt="Patient QR" className="w-40 aspect-square rounded-xl border bg-white p-2"/><img src={getBarcodeUrl(registered.code)} alt="Patient barcode" className="h-20 w-full object-contain bg-white border rounded-xl self-center"/></div></section>}
 <div className="flex justify-end gap-3 print:hidden">{registered&&<button type="button" className="btn-secondary" onClick={reset}>Register another</button>}<button type="button" className="btn-secondary" onClick={()=>navigate(-1)}>Cancel</button>{!registered&&<button type="submit" className="btn-primary" disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{saving?'Registering…':'Register Patient'}</button>}</div></form></div></div>
}
function Field({label,name,value,onChange,type='text',required=false,placeholder,disabled=false}:{label:string;name:keyof FormData;value:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void;type?:string;required?:boolean;placeholder?:string;disabled?:boolean}){return <label className="block text-sm space-y-1"><span className="font-medium">{label}</span><input id={name} name={name} type={type} value={value} onChange={onChange} required={required} placeholder={placeholder} disabled={disabled} className="input-medical w-full"/></label>}
function TextAreaField({label,name,value,onChange}:{label:string;name:keyof FormData;value:string;onChange:(e:ChangeEvent<HTMLTextAreaElement>)=>void}){return <label className="block text-sm space-y-1"><span className="font-medium">{label}</span><textarea id={name} name={name} value={value} onChange={onChange} className="input-medical w-full min-h-24"/></label>}
function SelectField({label,name,value,onChange,options}:{label:string;name:keyof FormData;value:string;onChange:(e:ChangeEvent<HTMLSelectElement>)=>void;options:string[]}){return <label className="block text-sm space-y-1"><span className="font-medium">{label}</span><select id={name} name={name} value={value} onChange={onChange} className="input-medical w-full"><option value="">Select</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
