import { Component, lazy, Suspense, type ErrorInfo, type ReactNode } from 'react';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/toaster';
import { Toaster as Sonner } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { AuthProvider } from '@/contexts/AuthContext';
import MainLayout from '@/components/layout/MainLayout';
import OfflineStatus from '@/components/system/OfflineStatus';
import RoleGuard from '@/components/auth/RoleGuard';
import Index from './pages/Index';
import Login from './pages/Login';
const Dashboard = lazy(() => import('./pages/Dashboard'));
const PatientRegistration = lazy(() => import('./pages/patients/PatientRegistration'));
const PatientSearch = lazy(() => import('./pages/patients/PatientSearch'));
const PatientHub = lazy(() => import('./pages/patients/PatientHub'));
const PatientCareContinuity = lazy(() => import('./pages/patients/PatientCareContinuity'));
const PatientChat = lazy(() => import('./pages/patients/PatientChat'));
const PatientPortal = lazy(() => import('./pages/PatientPortal'));
const SystemLibrary = lazy(() => import('./pages/admin/SystemLibrary'));
const Triage = lazy(() => import('./pages/Triage'));
const Consultation = lazy(() => import('./pages/Consultation'));
const Ophthalmology = lazy(() => import('./pages/Ophthalmology'));
const Laboratory = lazy(() => import('./pages/Laboratory'));
const Imaging = lazy(() => import('./pages/Imaging'));
const ClinicalResults = lazy(() => import('./pages/ClinicalResults'));
const Pharmacy = lazy(() => import('./pages/Pharmacy'));
const Notifications = lazy(() => import('./pages/Notifications'));
const AdminUsers = lazy(() => import('./pages/admin/AdminUsers'));
const RolePermissions = lazy(() => import('./pages/admin/RolePermissions'));
const BulkUpload = lazy(() => import('./pages/admin/BulkUpload'));
const DataImport = lazy(() => import('./pages/admin/DataImport'));
const PatientAudit = lazy(() => import('./pages/PatientAudit'));
const AdmissionManagement = lazy(() => import('./pages/AdmissionManagement'));
const MedicalRecords = lazy(() => import('./pages/MedicalRecords'));
const Monitoring = lazy(() => import('./pages/Monitoring'));
const SoundAlerts = lazy(() => import('./pages/SoundAlerts'));
const ReportsCenter = lazy(() => import('./pages/ReportsCenter'));
const ReportsSubmissionDashboard = lazy(() => import('./pages/ReportsSubmissionDashboard'));
const RosterGenerator = lazy(() => import('./pages/RosterGenerator'));
const AIClinicalHub = lazy(() => import('./pages/AIClinicalHub'));
const Encounters = lazy(() => import('./pages/Encounters'));
const Billing = lazy(() => import('./pages/Billing'));
const BillingTariffAdjustments = lazy(() => import('./pages/BillingTariffAdjustments'));
const Fertility = lazy(() => import('./pages/Fertility'));
const Telemedicine = lazy(() => import('./pages/Telemedicine'));
const Appointments = lazy(() => import('./pages/Appointments'));
const Dental = lazy(() => import('./pages/Dental'));
const ProcedureNotes = lazy(() => import('./pages/ProcedureNotes'));
const AnestheticAssessment = lazy(() => import('./pages/AnestheticAssessment'));
const TreatmentTemplates = lazy(() => import('./pages/TreatmentTemplates'));
const OutsideLabUploads = lazy(() => import('./pages/OutsideLabUploads'));
const AIReportGenerator = lazy(() => import('./pages/AIReportGenerator'));
const AccountsApprovals = lazy(() => import('./pages/AccountsApprovals'));
const DepartmentQueue = lazy(() => import('./pages/DepartmentQueue'));
const NotFound = lazy(() => import('./pages/NotFound'));
const Maternity = lazy(() => import('./pages/Maternity'));
const Settings = lazy(() => import('./pages/admin/Settings'));
const SystemLogs = lazy(() => import('./pages/admin/SystemLogs'));
const OfflineSyncCenter = lazy(() => import('./pages/admin/OfflineSyncCenter'));
const ShiftManagement = lazy(() => import('./pages/admin/ShiftManagement'));
const CareTransitions = lazy(() => import('./pages/CareTransitions'));
const MedicationAdministration = lazy(() => import('./pages/MedicationAdministration'));
const ClinicalOperations = lazy(() => import('./pages/ClinicalOperations'));
const WardBedBoard = lazy(() => import('./pages/WardBedBoard'));
const NursingHandover = lazy(() => import('./pages/NursingHandover'));
const InsuranceClaims = lazy(() => import('./pages/InsuranceClaims'));
const EmergencyBoard = lazy(() => import('./pages/EmergencyBoard'));
const TheatreBoard = lazy(() => import('./pages/TheatreBoard'));
const TransfusionBoard = lazy(() => import('./pages/TransfusionBoard'));
const CanteenMeals = lazy(() => import('./pages/CanteenMeals'));
const Profile = lazy(() => import('./pages/Profile'));
const SpecialistReferralQueue = lazy(() => import('./pages/SpecialistReferralQueue'));
const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 60000, gcTime: 300000, refetchOnWindowFocus: false, retry: 1 } } });
const PageFallback = () => <div className="flex min-h-[40vh] items-center justify-center p-12 text-sm text-muted-foreground">Loading…</div>;
interface ErrorBoundaryProps { children: ReactNode }
interface ErrorBoundaryState { error: Error | null }
class AppErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> { state: ErrorBoundaryState = { error: null }; static getDerivedStateFromError(error: Error): ErrorBoundaryState { return { error }; } componentDidCatch(error: Error, info: ErrorInfo) { console.error('Harmony Health Hub render error', error, info.componentStack); } handleReload = () => window.location.reload(); render() { if (!this.state.error) return this.props.children; return <div className="min-h-screen bg-background px-6 py-16 text-foreground"><div className="mx-auto max-w-xl rounded-2xl border border-border bg-card p-6 shadow-sm"><h1 className="text-xl font-semibold">Harmony Health Hub could not display this page</h1><p className="mt-2 text-sm text-muted-foreground">The application encountered a runtime error. Your session and data have not been cleared.</p><p className="mt-4 break-words rounded-lg bg-muted p-3 text-xs text-muted-foreground">{this.state.error.message || 'Unknown application error'}</p><button type="button" onClick={this.handleReload} className="btn-primary mt-4">Reload application</button></div></div>; } }
const clinicalRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse', 'radiologist'] as const;
const nursingRoles = ['admin', 'nurse', 'midwife', 'specialist_nurse'] as const;
const emergencyRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'front_desk'] as const;
const theatreRoles = ['admin', 'practitioner', 'nurse'] as const;
const transfusionRoles = ['admin', 'practitioner', 'nurse'] as const;
const insuranceRoles = ['admin', 'accountant'] as const;
const laboratoryRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'lab_technician', 'front_desk'] as const;
const pharmacyRoles = ['admin', 'pharmacist'] as const;
const reportsRoles = ['admin'] as const;
const accountsRoles = ['admin', 'accountant', 'front_desk'] as const;
const billingTariffRoles = ['admin', 'accountant'] as const;
const resultReviewRoles = ['admin', 'practitioner'] as const;
export default function App() { return <AppErrorBoundary><QueryClientProvider client={queryClient}><ThemeProvider attribute="class" defaultTheme="system" enableSystem><AuthProvider><TooltipProvider><Toaster /><Sonner /><OfflineStatus /><BrowserRouter basename={import.meta.env.BASE_URL.replace(/\/$/, '')}><Suspense fallback={<PageFallback />}><Routes><Route path="/" element={<Index />} /><Route path="/login" element={<Login />} /><Route element={<MainLayout />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/profile" element={<Profile />} /><Route path="/registration" element={<PatientRegistration />} /><Route path="/patients" element={<PatientSearch />} /><Route path="/patients/:patientId" element={<PatientHub />} /><Route path="/patients/:patientId/continuity" element={<PatientCareContinuity />} /><Route path="/patients/:patientId/audit" element={<PatientAudit />} /><Route path="/patients/:patientId/chat" element={<PatientChat />} /><Route path="/patient-portal" element={<PatientPortal />} /><Route path="/appointments" element={<Appointments />} /><Route path="/vitals" element={<Triage />} /><Route path="/consultation" element={<Consultation />} /><Route path="/encounters" element={<Encounters />} /><Route path="/specialist-referrals" element={<RoleGuard allowedRoles={clinicalRoles}><SpecialistReferralQueue /></RoleGuard>} /><Route path="/clinical-results" element={<RoleGuard allowedRoles={resultReviewRoles}><ClinicalResults /></RoleGuard>} /><Route path="/clinical-operations" element={<RoleGuard allowedRoles={clinicalRoles}><ClinicalOperations /></RoleGuard>} /><Route path="/ward-bed-board" element={<RoleGuard allowedRoles={clinicalRoles}><WardBedBoard /></RoleGuard>} /><Route path="/nursing-handover" element={<RoleGuard allowedRoles={nursingRoles}><NursingHandover /></RoleGuard>} /><Route path="/insurance-claims" element={<RoleGuard allowedRoles={insuranceRoles}><InsuranceClaims /></RoleGuard>} /><Route path="/emergency-board" element={<RoleGuard allowedRoles={emergencyRoles}><EmergencyBoard /></RoleGuard>} /><Route path="/theatre-board" element={<RoleGuard allowedRoles={theatreRoles}><TheatreBoard /></RoleGuard>} /><Route path="/transfusion-board" element={<RoleGuard allowedRoles={transfusionRoles}><TransfusionBoard /></RoleGuard>} /><Route path="/ophthalmology" element={<Ophthalmology />} /><Route path="/accounts-approvals" element={<RoleGuard allowedRoles={accountsRoles}><AccountsApprovals /></RoleGuard>} /><Route path="/department-queue" element={<DepartmentQueue />} /><Route path="/laboratory" element={<RoleGuard allowedRoles={laboratoryRoles}><Laboratory /></RoleGuard>} /><Route path="/lab-results" element={<RoleGuard allowedRoles={laboratoryRoles}><Laboratory /></RoleGuard>} /><Route path="/lab-requests" element={<RoleGuard allowedRoles={laboratoryRoles}><Laboratory /></RoleGuard>} /><Route path="/results-entry" element={<RoleGuard allowedRoles={laboratoryRoles}><Laboratory /></RoleGuard>} /><Route path="/imaging" element={<RoleGuard allowedRoles={clinicalRoles}><Imaging /></RoleGuard>} /><Route path="/radiology" element={<RoleGuard allowedRoles={clinicalRoles}><Imaging /></RoleGuard>} /><Route path="/pharmacy" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/medications" element={<RoleGuard allowedRoles={clinicalRoles}><MedicationAdministration /></RoleGuard>} /><Route path="/dispensing" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/inventory" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/stock-alerts" element={<SoundAlerts />} /><Route path="/sound-alerts" element={<SoundAlerts />} /><Route path="/records" element={<MedicalRecords />} /><Route path="/inpatients" element={<AdmissionManagement />} /><Route path="/admissions" element={<AdmissionManagement />} /><Route path="/monitoring" element={<Monitoring />} /><Route path="/maternity" element={<RoleGuard allowedRoles={nursingRoles}><Maternity /></RoleGuard>} /><Route path="/care-transitions" element={<CareTransitions />} /><Route path="/billing" element={<Billing />} /><Route path="/invoices" element={<Billing />} /><Route path="/billing/tariffs" element={<RoleGuard allowedRoles={billingTariffRoles}><BillingTariffAdjustments /></RoleGuard>} /><Route path="/insurance" element={<RoleGuard allowedRoles={insuranceRoles}><InsuranceClaims /></RoleGuard>} /><Route path="/financial-reports" element={<Billing />} /><Route path="/telemedicine" element={<Telemedicine />} /><Route path="/fertility" element={<Fertility />} /><Route path="/dental" element={<Dental />} /><Route path="/procedures" element={<RoleGuard allowedRoles={clinicalRoles}><ProcedureNotes /></RoleGuard>} /><Route path="/anesthesia" element={<RoleGuard allowedRoles={clinicalRoles}><AnestheticAssessment /></RoleGuard>} /><Route path="/treatment-templates" element={<RoleGuard allowedRoles={clinicalRoles}><TreatmentTemplates /></RoleGuard>} /><Route path="/outside-lab" element={<OutsideLabUploads />} /><Route path="/ai-report" element={<AIReportGenerator />} /><Route path="/menu" element={<CanteenMeals />} /><Route path="/orders" element={<CanteenMeals />} /><Route path="/dietary-plans" element={<CanteenMeals />} /><Route path="/reports" element={<RoleGuard allowedRoles={reportsRoles}><ReportsCenter /></RoleGuard>} /><Route path="/reports/submissions" element={<RoleGuard allowedRoles={reportsRoles}><ReportsSubmissionDashboard /></RoleGuard>} /><Route path="/public-health" element={<RoleGuard allowedRoles={reportsRoles}><ReportsCenter /></RoleGuard>} /><Route path="/roster" element={<RosterGenerator />} /><Route path="/ai-clinical" element={<RoleGuard allowedRoles={clinicalRoles}><AIClinicalHub /></RoleGuard>} /><Route path="/admin/users" element={<RoleGuard allowedRoles={['admin']}><AdminUsers /></RoleGuard>} /><Route path="/admin/system" element={<RoleGuard allowedRoles={['admin']}><SystemLibrary /></RoleGuard>} /><Route path="/admin/roles" element={<RoleGuard allowedRoles={['admin']}><RolePermissions /></RoleGuard>} /><Route path="/admin/permissions" element={<RoleGuard allowedRoles={['admin']}><RolePermissions /></RoleGuard>} /><Route path="/admin/settings" element={<RoleGuard allowedRoles={['admin']}><Settings /></RoleGuard>} /><Route path="/admin/shifts" element={<RoleGuard allowedRoles={['admin']}><ShiftManagement /></RoleGuard>} /><Route path="/admin/bulk-upload" element={<RoleGuard allowedRoles={['admin']}><BulkUpload /></RoleGuard>} /><Route path="/admin/data-import" element={<RoleGuard allowedRoles={['admin']}><DataImport /></RoleGuard>} /><Route path="/admin/logs" element={<RoleGuard allowedRoles={['admin']}><SystemLogs /></RoleGuard>} /><Route path="/admin/offline-sync" element={<RoleGuard allowedRoles={['admin']}><OfflineSyncCenter /></RoleGuard>} /><Route path="/notifications" element={<Notifications />} /></Route><Route path="*" element={<NotFound />} /></Routes></Suspense></BrowserRouter></TooltipProvider></AuthProvider></ThemeProvider></QueryClientProvider></AppErrorBoundary>;
}