import { Component, lazy, Suspense, type ErrorInfo, type ReactNode } from 'react';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/toaster';
import { Toaster as Sonner } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { AuthProvider } from '@/contexts/AuthContext';
import MainLayout from '@/components/layout/MainLayout';
import RouteLoadingScreen from '@/components/system/RouteLoadingScreen';
import OfflineStatus from '@/components/system/OfflineStatus';
import RoleGuard from '@/components/auth/RoleGuard';
import Index from './pages/Index';
import Login from './pages/Login';
const Dashboard = lazy(() => import('./pages/Dashboard'));
const PatientRegistration = lazy(() => import('./pages/patients/PatientRegistration'));
const PatientSearch = lazy(() => import('./pages/patients/PatientSearch'));
const PatientHub = lazy(() => import('./pages/patients/PatientHub'));
const PatientCareContinuity = lazy(() => import('./pages/patients/PatientCareContinuity'));
const PatientChat = lazy(() => import('./pages/patients/PatientChat'));
const PatientPortal = lazy(() => import('./pages/PatientPortal'));
const SystemLibrary = lazy(() => import('./pages/admin/SystemLibrary'));
const ClinicalReferences = lazy(() => import('./pages/admin/ClinicalReferences'));
const Triage = lazy(() => import('./pages/Triage'));
const Ophthalmology = lazy(() => import('./pages/Ophthalmology'));
const Laboratory = lazy(() => import('./pages/Laboratory'));
const LaboratoryResults = lazy(() => import('./pages/LaboratoryResults'));
const Imaging = lazy(() => import('./pages/Imaging'));
const ClinicalResults = lazy(() => import('./pages/ClinicalResults'));
const Pharmacy = lazy(() => import('./pages/Pharmacy'));
const Notifications = lazy(() => import('./pages/Notifications'));
const NotificationPreferences = lazy(() => import('./pages/NotificationPreferences'));
const AdminUsers = lazy(() => import('./pages/admin/AdminUsers'));
const RolePermissions = lazy(() => import('./pages/admin/RolePermissions'));
const InsuranceCompanies = lazy(() => import('./pages/admin/InsuranceCompanies'));
const BulkUpload = lazy(() => import('./pages/admin/BulkUpload'));
const DataImport = lazy(() => import('./pages/admin/DataImport'));
const FacilityAttributionReview = lazy(() => import('./pages/admin/FacilityAttributionReview'));
const FacilityDataSharing = lazy(() => import('./pages/admin/FacilityDataSharing'));
const PlatformFacilityOnboarding = lazy(() => import('./pages/admin/PlatformFacilityOnboarding'));
const PatientAudit = lazy(() => import('./pages/PatientAudit'));
const AdmissionManagement = lazy(() => import('./pages/AdmissionManagement'));
const InpatientManagement = lazy(() => import('./pages/InpatientManagement'));
const AdministrationWorkspace = lazy(() => import('./pages/AdministrationWorkspace'));
const ITSupportWorkspace = lazy(() => import('./pages/ITSupportWorkspace'));
const MedicalRecords = lazy(() => import('./pages/MedicalRecords'));
const Monitoring = lazy(() => import('./pages/Monitoring'));
const SoundAlerts = lazy(() => import('./pages/SoundAlerts'));
const ReportsCenter = lazy(() => import('./pages/ReportsCenter'));
const ReportsSubmissionDashboard = lazy(() => import('./pages/ReportsSubmissionDashboard'));
const RosterGenerator = lazy(() => import('./pages/RosterGenerator'));
const AIClinicalHub = lazy(() => import('./pages/AIClinicalHub'));
const Encounters = lazy(() => import('./pages/Encounters'));
const Billing = lazy(() => import('./pages/Billing'));
const InpatientBilling = lazy(() => import('./pages/InpatientBilling'));
const BillingTariffAdjustments = lazy(() => import('./pages/BillingTariffAdjustments'));
const Fertility = lazy(() => import('./pages/Fertility'));
const Telemedicine = lazy(() => import('./pages/Telemedicine'));
const Appointments = lazy(() => import('./pages/Appointments'));
const Dental = lazy(() => import('./pages/Dental'));
const ProcedureNotes = lazy(() => import('./pages/ProcedureNotes'));
const AnestheticAssessment = lazy(() => import('./pages/AnestheticAssessment'));
const TreatmentTemplates = lazy(() => import('./pages/TreatmentTemplates'));
const OutsideLabUploads = lazy(() => import('./pages/OutsideLabUploads'));
const AIReportGenerator = lazy(() => import('./pages/AIReportGenerator'));
const AccountsApprovals = lazy(() => import('./pages/AccountsApprovals'));
const DepartmentQueue = lazy(() => import('./pages/DepartmentQueue'));
const NotFound = lazy(() => import('./pages/NotFound'));
const Maternity = lazy(() => import('./pages/Maternity'));
const Settings = lazy(() => import('./pages/admin/Settings'));
const SystemLogs = lazy(() => import('./pages/admin/SystemLogs'));
const OfflineSyncCenter = lazy(() => import('./pages/admin/OfflineSyncCenter'));
const ShiftManagement = lazy(() => import('./pages/admin/ShiftManagement'));
const CareTransitions = lazy(() => import('./pages/CareTransitions'));
const MedicationAdministration = lazy(() => import('./pages/MedicationAdministration'));
const ClinicalOperations = lazy(() => import('./pages/ClinicalOperations'));
const WardBedBoard = lazy(() => import('./pages/WardBedBoard'));
const NursingHandover = lazy(() => import('./pages/NursingHandover'));
const InsuranceClaims = lazy(() => import('./pages/InsuranceClaims'));
const EmergencyBoard = lazy(() => import('./pages/EmergencyBoard'));
const TheatreBoard = lazy(() => import('./pages/TheatreBoard'));
const TransfusionBoard = lazy(() => import('./pages/TransfusionBoard'));
const CanteenMeals = lazy(() => import('./pages/CanteenMeals'));
const Profile = lazy(() => import('./pages/Profile'));
const HumanResources = lazy(() => import('./pages/HumanResources'));
const Payroll = lazy(() => import('./pages/Payroll'));
const SpecialistReferralQueue = lazy(() => import('./pages/SpecialistReferralQueue'));
const ReviewAppointmentQueue = lazy(() => import('./pages/ReviewAppointmentQueue'));
const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 60000, gcTime: 300000, refetchOnWindowFocus: false, retry: 1 } } });
const PageFallback = RouteLoadingScreen;
interface ErrorBoundaryProps { children: ReactNode }
interface ErrorBoundaryState { error: Error | null }
class AppErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> { state: ErrorBoundaryState = { error: null }; static getDerivedStateFromError(error: Error): ErrorBoundaryState { return { error }; } componentDidCatch(error: Error, info: ErrorInfo) { console.error('Harmony Health Hub render error', error, info.componentStack); } handleReload = () => window.location.reload(); render() { if (!this.state.error) return this.props.children; return <div className="min-h-screen bg-background px-6 py-16 text-foreground"><div className="mx-auto max-w-xl rounded-2xl border border-border bg-card p-6 shadow-sm"><h1 className="text-xl font-semibold">Harmony Health Hub could not display this page</h1><p className="mt-2 text-sm text-muted-foreground">The application encountered a runtime error. Your session and data have not been cleared.</p><p className="mt-4 break-words rounded-lg bg-muted p-3 text-xs text-muted-foreground">{this.state.error.message || 'Unknown application error'}</p><button type="button" onClick={this.handleReload} className="btn-primary mt-4">Reload application</button></div></div>; } }
const clinicalRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse', 'radiologist', 'radiology_technician'] as const;
const encounterRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse'] as const;
const laboratoryWorkspaceRoles = ['admin', 'lab_technician'] as const;
const radiologyWorkspaceRoles = ['admin', 'radiologist', 'radiology_technician'] as const;
const departmentQueueRoles = ['admin', 'it_admin', 'accountant', 'lab_technician', 'radiologist', 'radiology_technician', 'pharmacist', 'canteen', 'front_desk', 'nurse', 'specialist_nurse', 'midwife'] as const;
const wardManagementRoles = ['admin', 'it_admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse'] as const;
const clinicalOperationsRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse'] as const;
const nursingRoles = ['admin', 'nurse', 'midwife', 'specialist_nurse'] as const;
const emergencyRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'front_desk'] as const;
const theatreRoles = ['admin', 'practitioner', 'nurse'] as const;
const transfusionRoles = ['admin', 'practitioner', 'nurse'] as const;
const insuranceRoles = ['admin', 'accountant'] as const;
const laboratoryRoles = ['admin', 'lab_technician'] as const;
const pharmacyRoles = ['admin', 'pharmacist'] as const;
const reportsRoles = ['admin', 'practitioner', 'accountant', 'lab_technician'] as const;
const accountsRoles = ['admin', 'accountant', 'front_desk'] as const;
const billingTariffRoles = ['admin', 'accountant'] as const;
const resultReviewRoles = ['admin', 'practitioner', 'nurse', 'specialist_nurse', 'midwife'] as const;
const billingRoles = ['admin', 'accountant', 'front_desk', 'patient'] as const;
const telemedicineRoles = ['admin', 'practitioner', 'patient'] as const;
const fertilityRoles = ['admin', 'practitioner', 'midwife'] as const;
const outsideLabRoles = ['admin', 'lab_technician', 'patient'] as const;
const pharmacyInventoryRoles = ['admin', 'pharmacist'] as const;
const canteenRoles = ['admin', 'canteen'] as const;
const financialReportRoles = ['admin', 'accountant'] as const;
const patientRecordsRoles = ['admin', 'practitioner', 'nurse', 'specialist_nurse', 'radiologist', 'radiology_technician', 'front_desk', 'patient'] as const;
const patientContinuityRoles = ['admin', 'practitioner', 'nurse', 'midwife', 'specialist_nurse', 'pharmacist', 'lab_technician'] as const;
const appointmentRoles = ['admin', 'practitioner', 'nurse', 'specialist_nurse', 'midwife', 'front_desk', 'patient'] as const;
const registrationRoles = ['admin', 'front_desk'] as const;
const patientPortalRoles = ['patient'] as const;
const notificationRoles = ['admin', 'radiologist', 'radiology_technician', 'it_admin', 'patient'] as const;
const inpatientRoles = ['admin', 'it_admin', 'system_superuser', 'practitioner', 'nurse', 'midwife', 'specialist_nurse'] as const;
const hrRoles = ['admin', 'it_admin'] as const;
const payrollRoles = ['admin', 'it_admin', 'accountant'] as const;
export default function App() { return <AppErrorBoundary><QueryClientProvider client={queryClient}><ThemeProvider attribute="class" defaultTheme="system" enableSystem><AuthProvider><TooltipProvider><Toaster /><Sonner position="bottom-right" visibleToasts={3} duration={4000} closeButton richColors={false} /><OfflineStatus /><BrowserRouter basename={import.meta.env.BASE_URL.replace(/\/$/, '')}><Suspense fallback={<PageFallback />}><Routes><Route path="/" element={<Index />} /><Route path="/login" element={<Login />} /><Route element={<MainLayout />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/profile" element={<Profile />} /><Route path="/hr" element={<RoleGuard allowedRoles={hrRoles}><HumanResources /></RoleGuard>} /><Route path="/payroll" element={<RoleGuard allowedRoles={payrollRoles}><Payroll /></RoleGuard>} /><Route path="/registration" element={<RoleGuard allowedRoles={registrationRoles}><PatientRegistration /></RoleGuard>} /><Route path="/patients" element={<RoleGuard allowedRoles={patientRecordsRoles}><PatientSearch /></RoleGuard>} /><Route path="/patients/:patientId" element={<RoleGuard allowedRoles={patientRecordsRoles}><PatientHub /></RoleGuard>} /><Route path="/patients/:patientId/continuity" element={<RoleGuard allowedRoles={patientContinuityRoles}><PatientCareContinuity /></RoleGuard>} /><Route path="/patients/:patientId/audit" element={<RoleGuard allowedRoles={['admin']}><PatientAudit /></RoleGuard>} /><Route path="/patients/:patientId/chat" element={<RoleGuard allowedRoles={['admin','practitioner','nurse','specialist_nurse','midwife','patient']}><PatientChat /></RoleGuard>} /><Route path="/patient-portal" element={<RoleGuard allowedRoles={patientPortalRoles}><PatientPortal /></RoleGuard>} /><Route path="/appointments" element={<RoleGuard allowedRoles={appointmentRoles}><Appointments /></RoleGuard>} /><Route path="/vitals" element={<RoleGuard allowedRoles={clinicalRoles}><Triage /></RoleGuard>} /><Route path="/consultation" element={<RoleGuard allowedRoles={encounterRoles}><Navigate to="/encounters" replace /></RoleGuard>} /><Route path="/encounters/:encounterId" element={<RoleGuard allowedRoles={encounterRoles}><Encounters /></RoleGuard>} /><Route path="/encounters" element={<RoleGuard allowedRoles={encounterRoles}><Encounters /></RoleGuard>} /><Route path="/specialist-referrals" element={<RoleGuard allowedRoles={clinicalRoles}><SpecialistReferralQueue /></RoleGuard>} /><Route path="/review-appointments" element={<RoleGuard allowedRoles={clinicalRoles}><ReviewAppointmentQueue /></RoleGuard>} /><Route path="/clinical-results" element={<RoleGuard allowedRoles={resultReviewRoles}><ClinicalResults /></RoleGuard>} /><Route path="/clinical-operations" element={<RoleGuard allowedRoles={clinicalOperationsRoles}><ClinicalOperations /></RoleGuard>} /><Route path="/ward-bed-board" element={<RoleGuard allowedRoles={wardManagementRoles}><WardBedBoard /></RoleGuard>} /><Route path="/nursing-handover" element={<RoleGuard allowedRoles={nursingRoles}><NursingHandover /></RoleGuard>} /><Route path="/insurance-claims" element={<RoleGuard allowedRoles={insuranceRoles}><InsuranceClaims /></RoleGuard>} /><Route path="/emergency-board" element={<RoleGuard allowedRoles={emergencyRoles}><EmergencyBoard /></RoleGuard>} /><Route path="/theatre-board" element={<RoleGuard allowedRoles={theatreRoles}><TheatreBoard /></RoleGuard>} /><Route path="/transfusion-board" element={<RoleGuard allowedRoles={transfusionRoles}><TransfusionBoard /></RoleGuard>} /><Route path="/ophthalmology" element={<RoleGuard allowedRoles={clinicalRoles}><Ophthalmology /></RoleGuard>} /><Route path="/accounts-approvals" element={<RoleGuard allowedRoles={accountsRoles}><AccountsApprovals /></RoleGuard>} /><Route path="/department-queue" element={<RoleGuard allowedRoles={departmentQueueRoles}><DepartmentQueue /></RoleGuard>} /><Route path="/laboratory" element={<RoleGuard allowedRoles={laboratoryWorkspaceRoles}><Laboratory /></RoleGuard>} /><Route path="/lab-results" element={<RoleGuard allowedRoles={resultReviewRoles}><LaboratoryResults /></RoleGuard>} /><Route path="/lab-requests" element={<RoleGuard allowedRoles={encounterRoles}><Navigate to="/encounters" replace /></RoleGuard>} /><Route path="/results-entry" element={<RoleGuard allowedRoles={laboratoryWorkspaceRoles}><Laboratory /></RoleGuard>} /><Route path="/imaging" element={<RoleGuard allowedRoles={radiologyWorkspaceRoles}><Imaging /></RoleGuard>} /><Route path="/radiology" element={<RoleGuard allowedRoles={radiologyWorkspaceRoles}><Imaging /></RoleGuard>} /><Route path="/pharmacy" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/medications" element={<RoleGuard allowedRoles={clinicalRoles}><MedicationAdministration /></RoleGuard>} /><Route path="/dispensing" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/inventory" element={<RoleGuard allowedRoles={pharmacyRoles}><Pharmacy /></RoleGuard>} /><Route path="/stock-alerts" element={<RoleGuard allowedRoles={pharmacyInventoryRoles}><SoundAlerts /></RoleGuard>} /><Route path="/sound-alerts" element={<SoundAlerts />} /><Route path="/records" element={<RoleGuard allowedRoles={patientRecordsRoles}><MedicalRecords /></RoleGuard>} /><Route path="/inpatient" element={<RoleGuard allowedRoles={inpatientRoles}><InpatientManagement /></RoleGuard>} /><Route path="/inpatients" element={<RoleGuard allowedRoles={inpatientRoles}><InpatientManagement /></RoleGuard>} /><Route path="/admissions" element={<RoleGuard allowedRoles={wardManagementRoles}><AdmissionManagement /></RoleGuard>} /><Route path="/monitoring" element={<RoleGuard allowedRoles={nursingRoles}><Monitoring /></RoleGuard>} /><Route path="/maternity" element={<RoleGuard allowedRoles={nursingRoles}><Maternity /></RoleGuard>} /><Route path="/care-transitions" element={<RoleGuard allowedRoles={clinicalRoles}><CareTransitions /></RoleGuard>} /><Route path="/finance" element={<RoleGuard allowedRoles={['admin','accountant','front_desk']}><Navigate to="/billing" replace /></RoleGuard>} /><Route path="/administration" element={<RoleGuard allowedRoles={['admin']}><AdministrationWorkspace /></RoleGuard>} /><Route path="/it-support" element={<RoleGuard allowedRoles={['admin','it_admin']}><ITSupportWorkspace /></RoleGuard>} /><Route path="/billing" element={<RoleGuard allowedRoles={billingRoles}><Billing /></RoleGuard>} /><Route path="/billing/inpatients" element={<RoleGuard allowedRoles={accountsRoles}><InpatientBilling /></RoleGuard>} /><Route path="/billing/inpatients/:patientId" element={<RoleGuard allowedRoles={accountsRoles}><InpatientBilling /></RoleGuard>} /><Route path="/invoices" element={<RoleGuard allowedRoles={billingRoles}><Billing /></RoleGuard>} /><Route path="/billing/tariffs" element={<RoleGuard allowedRoles={billingTariffRoles}><BillingTariffAdjustments /></RoleGuard>} /><Route path="/insurance" element={<RoleGuard allowedRoles={insuranceRoles}><InsuranceClaims /></RoleGuard>} /><Route path="/financial-reports" element={<RoleGuard allowedRoles={financialReportRoles}><Billing /></RoleGuard>} /><Route path="/telemedicine" element={<RoleGuard allowedRoles={telemedicineRoles}><Telemedicine /></RoleGuard>} /><Route path="/fertility" element={<RoleGuard allowedRoles={fertilityRoles}><Fertility /></RoleGuard>} /><Route path="/dental" element={<RoleGuard allowedRoles={clinicalRoles}><Dental /></RoleGuard>} /><Route path="/procedures" element={<RoleGuard allowedRoles={clinicalRoles}><ProcedureNotes /></RoleGuard>} /><Route path="/anesthesia" element={<RoleGuard allowedRoles={clinicalRoles}><AnestheticAssessment /></RoleGuard>} /><Route path="/treatment-templates" element={<RoleGuard allowedRoles={clinicalRoles}><TreatmentTemplates /></RoleGuard>} /><Route path="/outside-lab" element={<RoleGuard allowedRoles={outsideLabRoles}><OutsideLabUploads /></RoleGuard>} /><Route path="/ai-report" element={<RoleGuard allowedRoles={clinicalRoles}><AIReportGenerator /></RoleGuard>} /><Route path="/menu" element={<RoleGuard allowedRoles={[...canteenRoles, "patient"]}><CanteenMeals /></RoleGuard>} /><Route path="/orders" element={<RoleGuard allowedRoles={canteenRoles}><CanteenMeals /></RoleGuard>} /><Route path="/dietary-plans" element={<RoleGuard allowedRoles={canteenRoles}><CanteenMeals /></RoleGuard>} /><Route path="/reports" element={<RoleGuard allowedRoles={reportsRoles}><ReportsCenter /></RoleGuard>} /><Route path="/reports/submissions" element={<RoleGuard allowedRoles={reportsRoles}><ReportsSubmissionDashboard /></RoleGuard>} /><Route path="/public-health" element={<RoleGuard allowedRoles={reportsRoles}><ReportsCenter /></RoleGuard>} /><Route path="/roster" element={<RosterGenerator />} /><Route path="/ai-clinical" element={<RoleGuard allowedRoles={clinicalRoles}><AIClinicalHub /></RoleGuard>} /><Route path="/admin/users" element={<RoleGuard allowedRoles={['admin','it_admin','system_superuser']}><AdminUsers /></RoleGuard>} /><Route path="/admin/system" element={<RoleGuard allowedRoles={['admin']}><SystemLibrary /></RoleGuard>} /><Route path="/admin/clinical-references" element={<RoleGuard allowedRoles={['admin','system_superuser']}><ClinicalReferences /></RoleGuard>} /><Route path="/admin/roles" element={<RoleGuard allowedRoles={['admin']}><RolePermissions /></RoleGuard>} /><Route path="/admin/insurance-companies" element={<RoleGuard allowedRoles={['admin','it_admin']}><InsuranceCompanies /></RoleGuard>} /><Route path="/admin/permissions" element={<RoleGuard allowedRoles={['admin']}><RolePermissions /></RoleGuard>} /><Route path="/admin/settings" element={<RoleGuard allowedRoles={['admin','it_admin','system_superuser']}><Settings /></RoleGuard>} /><Route path="/admin/shifts" element={<RoleGuard allowedRoles={['admin']}><ShiftManagement /></RoleGuard>} /><Route path="/admin/bulk-upload" element={<RoleGuard allowedRoles={['admin']}><BulkUpload /></RoleGuard>} /><Route path="/admin/data-import" element={<RoleGuard allowedRoles={['admin']}><DataImport /></RoleGuard>} /><Route path="/admin/facility-attribution" element={<RoleGuard allowedRoles={['admin','it_admin','system_superuser']}><FacilityAttributionReview /></RoleGuard>} /><Route path="/admin/facility-sharing" element={<RoleGuard allowedRoles={['admin','it_admin','system_superuser']}><FacilityDataSharing /></RoleGuard>} /><Route path="/admin/facility-onboarding" element={<RoleGuard allowedRoles={['system_superuser']}><PlatformFacilityOnboarding /></RoleGuard>} /><Route path="/admin/logs" element={<RoleGuard allowedRoles={['admin','it_admin']}><SystemLogs /></RoleGuard>} /><Route path="/admin/offline-sync" element={<RoleGuard allowedRoles={['admin','it_admin']}><OfflineSyncCenter /></RoleGuard>} /><Route path="/notifications" element={<RoleGuard allowedRoles={notificationRoles}><Notifications /></RoleGuard>} /><Route path="/notification-preferences" element={<RoleGuard allowedRoles={notificationRoles}><NotificationPreferences /></RoleGuard>} /></Route><Route path="*" element={<NotFound />} /></Routes></Suspense></BrowserRouter></TooltipProvider></AuthProvider></ThemeProvider></QueryClientProvider></AppErrorBoundary>;
}