BEGIN;
CREATE OR REPLACE FUNCTION public.prepare_patient_billable_items(_patient_id uuid, _from timestamptz DEFAULT date_trunc('day',now()), _to timestamptz DEFAULT now())
RETURNS TABLE(invoice_id uuid,invoice_item_id uuid,source_type text,source_id uuid,description text,category text,department text,quantity integer,unit_price numeric,amount numeric,paid_amount numeric,outstanding_amount numeric,service_order_id uuid,service_order_status text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog','public'
AS $function$
DECLARE inv uuid; tariff numeric; r record; days_count integer; uid uuid:=auth.uid();
BEGIN
 IF uid IS NULL OR NOT(public.has_role(uid,'admin') OR public.has_role(uid,'accountant') OR public.has_role(uid,'front_desk')) THEN RAISE EXCEPTION 'Billing access denied'; END IF;
 IF _patient_id IS NULL OR _from IS NULL OR _to IS NULL OR _from>_to THEN RAISE EXCEPTION 'Invalid patient billing period'; END IF;
 IF NOT EXISTS(select 1 from public.patients where id=_patient_id) THEN RAISE EXCEPTION 'Patient not found'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(_patient_id::text,0));
 SELECT id INTO inv FROM public.invoices WHERE patient_id=_patient_id AND status IN('pending','partially_paid') ORDER BY created_at DESC LIMIT 1 FOR UPDATE;
 IF inv IS NULL THEN INSERT INTO public.invoices(invoice_number,patient_id,total_amount,created_by) VALUES('INV-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||substr(gen_random_uuid()::text,1,6),_patient_id,0,uid) RETURNING id INTO inv; END IF;
 SELECT st.amount INTO tariff FROM public.service_tariffs st WHERE st.service_code='CONSULTATION' AND st.active AND st.effective_from<=_to::date AND (st.effective_to IS NULL OR st.effective_to>=_from::date) ORDER BY st.effective_from DESC NULLS LAST LIMIT 1;
 IF tariff IS NOT NULL THEN INSERT INTO public.invoice_items(invoice_id,description,quantity,unit_price,amount,category,source_type,source_id,service_code,department) SELECT inv,'Consultation',1,tariff,tariff,'consultation','appointment',a.id,'CONSULTATION','consultation' FROM public.appointments a WHERE a.patient_id=_patient_id AND a.scheduled_at BETWEEN _from AND _to AND a.status NOT IN('cancelled','no_show') AND NOT EXISTS(select 1 from public.invoice_items i where i.source_type='appointment' and i.source_id=a.id) AND NOT EXISTS(select 1 from public.service_orders so where so.patient_id=a.patient_id and so.related_entity_id=a.id and so.department='consultation' and so.status<>'cancelled'); END IF;
 SELECT st.amount INTO tariff FROM public.service_tariffs st WHERE st.service_code='LAB-GENERIC' AND st.active AND st.effective_from<=_to::date AND (st.effective_to IS NULL OR st.effective_to>=_from::date) ORDER BY st.effective_from DESC NULLS LAST LIMIT 1;
 IF tariff IS NOT NULL THEN FOR r IN SELECT l.id,l.test_name FROM public.lab_orders l WHERE l.patient_id=_patient_id AND l.created_at BETWEEN _from AND _to AND l.status<>'cancelled' AND NOT EXISTS(select 1 from public.service_orders so where so.patient_id=l.patient_id and so.related_entity_id=l.id and so.department='laboratory' and so.status<>'cancelled') LOOP INSERT INTO public.invoice_items(invoice_id,description,quantity,unit_price,amount,category,source_type,source_id,service_code,department) SELECT inv,r.test_name,1,tariff,tariff,'lab','lab_order',r.id,'LAB-GENERIC','laboratory' WHERE NOT EXISTS(select 1 from public.invoice_items i where i.source_type='lab_order' and i.source_id=r.id); END LOOP; END IF;
 SELECT st.amount INTO tariff FROM public.service_tariffs st WHERE st.service_code='PROCEDURE-GENERIC' AND st.active AND st.effective_from<=_to::date AND (st.effective_to IS NULL OR st.effective_to>=_from::date) ORDER BY st.effective_from DESC NULLS LAST LIMIT 1;
 FOR r IN SELECT so.id,so.service_name,so.amount,so.department,so.service_code,so.quantity FROM public.service_orders so WHERE so.patient_id=_patient_id AND so.created_at BETWEEN _from AND _to AND so.status<>'cancelled' LOOP
   INSERT INTO public.invoice_items(invoice_id,description,quantity,unit_price,amount,category,source_type,source_id,service_code,department)
   SELECT inv,r.service_name,greatest(coalesce(r.quantity,1),1),coalesce(nullif(r.amount,0),tariff,0),coalesce(nullif(r.amount,0),tariff,0)*greatest(coalesce(r.quantity,1),1),case when r.department='pharmacy' then 'pharmacy' when r.department='laboratory' then 'lab' when r.department in('imaging','radiology') then 'imaging' else 'procedure' end,'service_order',r.id,coalesce(r.service_code,'PROCEDURE-GENERIC'),r.department
   WHERE NOT EXISTS(select 1 from public.invoice_items i where i.source_type='service_order' and i.source_id=r.id);
 END LOOP;
 SELECT st.amount INTO tariff FROM public.service_tariffs st WHERE st.service_code='PROCEDURE-GENERIC' AND st.active AND st.effective_from<=_to::date AND (st.effective_to IS NULL OR st.effective_to>=_from::date) ORDER BY st.effective_from DESC NULLS LAST LIMIT 1;
 IF tariff IS NOT NULL THEN FOR r IN SELECT p.id,p.medication,p.computed_quantity FROM public.prescriptions p WHERE p.patient_id=_patient_id AND p.created_at BETWEEN _from AND _to AND p.status<>'cancelled' AND NOT EXISTS(select 1 from public.service_orders so where so.patient_id=p.patient_id and so.related_entity_id=p.id and so.department='pharmacy' and so.status<>'cancelled') LOOP INSERT INTO public.invoice_items(invoice_id,description,quantity,unit_price,amount,category,source_type,source_id,service_code,department) SELECT inv,'Medication: '||r.medication,greatest(coalesce(nullif(r.computed_quantity,0),1),1),tariff,greatest(coalesce(nullif(r.computed_quantity,0),1),1)*tariff,'pharmacy','prescription',r.id,'PROCEDURE-GENERIC','pharmacy' WHERE NOT EXISTS(select 1 from public.invoice_items i where i.source_type='prescription' and i.source_id=r.id); END LOOP; END IF;
 SELECT st.amount INTO tariff FROM public.service_tariffs st WHERE st.service_code='WARD-ACCOM' AND st.active AND st.effective_from<=_to::date AND (st.effective_to IS NULL OR st.effective_to>=_from::date) ORDER BY st.effective_from DESC NULLS LAST LIMIT 1;
 IF tariff IS NOT NULL AND to_regclass('public.admissions') IS NOT NULL THEN FOR r IN SELECT a.id,a.admitted_at,a.discharged_at,a.ward FROM public.admissions a WHERE a.patient_id=_patient_id AND a.admitted_at<=_to AND coalesce(a.discharged_at,_to)>=_from LOOP days_count:=greatest(1,ceil(extract(epoch from(least(coalesce(r.discharged_at,_to),_to)-greatest(r.admitted_at,_from)))/86400)::integer); INSERT INTO public.invoice_items(invoice_id,description,quantity,unit_price,amount,category,source_type,source_id,service_code,department) SELECT inv,'Accommodation: '||coalesce(r.ward,'Ward'),days_count,tariff,days_count*tariff,'ward','admission',r.id,'WARD-ACCOM','ward' WHERE NOT EXISTS(select 1 from public.invoice_items i where i.source_type='admission' and i.source_id=r.id); END LOOP; END IF;
 UPDATE public.invoices SET total_amount=coalesce((select sum(ii.amount) from public.invoice_items ii where ii.invoice_id=inv),0),updated_at=now() WHERE id=inv;
 RETURN QUERY SELECT ii.invoice_id,ii.id,ii.source_type,ii.source_id,ii.description,ii.category,ii.department,ii.quantity,ii.unit_price,ii.amount,coalesce((select sum(ip.amount) from public.invoice_item_payments ip where ip.invoice_item_id=ii.id),0),greatest(ii.amount-coalesce((select sum(ip.amount) from public.invoice_item_payments ip where ip.invoice_item_id=ii.id),0),0),so.id,so.status FROM public.invoice_items ii LEFT JOIN LATERAL(select s.id,s.status from public.service_orders s where s.invoice_item_id=ii.id order by s.created_at desc limit 1)so on true WHERE ii.invoice_id=inv ORDER BY ii.created_at;
END;$function$;

CREATE OR REPLACE FUNCTION public.get_billing_window(_patient_id uuid,_at timestamptz DEFAULT now())
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog','public'
AS $function$
DECLARE v_patient public.patients; v_encounter uuid; v_invoice uuid; v_start timestamptz:=date_trunc('day',coalesce(_at,now())); v_end timestamptz:=date_trunc('day',coalesce(_at,now()))+interval '1 day'-interval '1 microsecond'; v_insured boolean:=false; v_insurer text; v_insurer_id uuid; v_credit numeric:=0; v_total numeric:=0; v_insurance numeric:=0; v_topup numeric:=0; v_items jsonb; v_account_id text;
BEGIN
 IF auth.uid() IS NULL OR NOT(public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'accountant') OR public.has_role(auth.uid(),'front_desk')) THEN RAISE EXCEPTION 'Billing access denied'; END IF;
 SELECT * INTO v_patient FROM public.patients WHERE id=_patient_id AND coalesce(status,'active')<>'inactive'; IF v_patient.id IS NULL THEN RAISE EXCEPTION 'Active patient not found'; END IF;
 SELECT e.id INTO v_encounter FROM public.encounters e WHERE e.patient_id=_patient_id AND e.created_at<=v_end AND (e.completed_at IS NULL OR e.completed_at>=v_start) ORDER BY coalesce(e.started_at,e.created_at) DESC LIMIT 1;
 v_insured:=NULLIF(trim(v_patient.insurance_provider),'') IS NOT NULL AND NULLIF(trim(v_patient.insurance_number),'') IS NOT NULL AND (v_patient.insurance_expiry IS NULL OR v_patient.insurance_expiry>=_at::date);
 IF v_insured THEN
   v_insurer_id:=v_patient.insurance_company_id;
   IF v_insurer_id IS NULL THEN SELECT c.insurance_company_id,c.payer_name INTO v_insurer_id,v_insurer FROM public.insurance_cases c WHERE c.patient_id=_patient_id AND c.eligibility_status='eligible' AND c.created_at<=v_end ORDER BY c.updated_at DESC LIMIT 1; END IF;
   IF v_insurer_id IS NOT NULL THEN SELECT name INTO v_insurer FROM public.insurance_companies WHERE id=v_insurer_id; END IF;
   v_insurer:=coalesce(v_insurer,(SELECT c.payer_name FROM public.insurance_cases c WHERE c.patient_id=_patient_id AND c.eligibility_status='eligible' AND c.created_at<=v_end ORDER BY c.updated_at DESC LIMIT 1),v_patient.insurance_provider);
 END IF;
 PERFORM public.prepare_patient_billable_items(_patient_id,v_start,v_end);
 SELECT i.id INTO v_invoice FROM public.invoices i WHERE i.patient_id=_patient_id AND i.status IN('pending','partially_paid') ORDER BY i.created_at DESC LIMIT 1 FOR UPDATE;
 IF v_invoice IS NULL THEN RAISE EXCEPTION 'Billing invoice could not be prepared'; END IF;
 IF v_encounter IS NOT NULL THEN UPDATE public.invoices SET encounter_id=coalesce(encounter_id,v_encounter),updated_at=now() WHERE id=v_invoice; END IF;
 UPDATE public.invoice_items ii SET insurance_charge=CASE WHEN NOT v_insured THEN 0 ELSE least(ii.amount,greatest(coalesce((SELECT t.insurance_charge FROM public.insurance_service_tariffs t WHERE ((v_insurer_id IS NOT NULL AND t.insurance_company_id=v_insurer_id) OR (v_insurer_id IS NULL AND lower(t.payer_name)=lower(v_insurer))) AND t.service_code=ii.service_code AND t.active AND t.effective_from<=_at::date AND (t.effective_to IS NULL OR t.effective_to>=_at::date) ORDER BY t.effective_from DESC LIMIT 1),0)*greatest(ii.quantity,1),0)) END, top_up=CASE WHEN NOT v_insured THEN greatest(ii.amount-coalesce((SELECT sum(ip.amount) FROM public.invoice_item_payments ip WHERE ip.invoice_item_id=ii.id),0),0) ELSE greatest(ii.amount-least(ii.amount,greatest(coalesce((SELECT t.insurance_charge FROM public.insurance_service_tariffs t WHERE ((v_insurer_id IS NOT NULL AND t.insurance_company_id=v_insurer_id) OR (v_insurer_id IS NULL AND lower(t.payer_name)=lower(v_insurer))) AND t.service_code=ii.service_code AND t.active AND t.effective_from<=_at::date AND (t.effective_to IS NULL OR t.effective_to>=_at::date) ORDER BY t.effective_from DESC LIMIT 1),0)*greatest(ii.quantity,1),0)),0) END,updated_at=now() WHERE ii.invoice_id=v_invoice;
 SELECT coalesce(sum(ii.amount),0),coalesce(sum(ii.insurance_charge),0),coalesce(sum(case when v_insured then ii.top_up else ii.amount end),0) INTO v_total,v_insurance,v_topup FROM public.invoice_items ii WHERE ii.invoice_id=v_invoice;
 SELECT coalesce(sum(case when entry_type in('deposit','credit') then amount else -amount end),0) INTO v_credit FROM public.patient_account_credits WHERE patient_id=_patient_id;
 SELECT coalesce(jsonb_agg(jsonb_build_object('invoice_item_id',ii.id,'source_type',ii.source_type,'source_id',ii.source_id,'description',ii.description,'category',ii.category,'department',ii.department,'quantity',ii.quantity,'unit_price',ii.unit_price,'charge',ii.amount,'insurance_charge',coalesce(ii.insurance_charge,0),'top_up',case when v_insured then coalesce(ii.top_up,ii.amount) else ii.amount end,'paid_amount',coalesce((select sum(ip.amount) from public.invoice_item_payments ip where ip.invoice_item_id=ii.id),0),'outstanding_amount',greatest(ii.amount-coalesce((select sum(ip.amount) from public.invoice_item_payments ip where ip.invoice_item_id=ii.id),0),0),'billed_at',ii.billed_at,'service_order_id',so.id,'service_order_status',so.status) order by ii.created_at),'[]'::jsonb) INTO v_items FROM public.invoice_items ii LEFT JOIN LATERAL(select s.id,s.status from public.service_orders s where s.invoice_item_id=ii.id order by s.created_at desc limit 1)so on true WHERE ii.invoice_id=v_invoice;
 SELECT i.invoice_number INTO v_account_id FROM public.invoices i WHERE i.id=v_invoice;
 RETURN jsonb_build_object('invoice_id',v_invoice,'account_id',v_account_id,'records_folder_id',v_patient.patient_code,'patient_name',concat_ws(' ',v_patient.first_name,v_patient.last_name),'patient_type',case when v_insured then 'Insured' else 'Cash / Non-Insured' end,'insurance_name',case when v_insured then v_insurer else null end,'encounter_id',v_encounter,'date_time',coalesce(_at,now()),'total_amount',round(v_total,2),'insurance_total',round(v_insurance,2),'top_up_total',round(v_topup,2),'credit_balance',round(v_credit,2),'amount_due',round(v_topup-v_credit,2),'items',v_items);
END;$function$;
COMMIT;