-- Extend canonical facility attribution to specialty, inpatient,
-- nursing, referral, insurance, pharmacy, procedure, transfusion,
-- emergency and AI clinical transaction records.
do $$ declare t text; begin foreach t in array array['emergency_cases','maternity_episodes','fertility_cycles','inpatient_bed_movements','nursing_care_plans','nursing_shift_handovers','patient_referrals','care_transitions','insurance_cases','insurance_claims','pharmacy_dispensing_plans','pharmacy_pos_sales','procedure_notes','theatre_cases','transfusion_records','vital_alerts','ai_case_memory','ai_clinical_sessions','ai_diagnosis_suggestions','ai_report_requests'] loop execute format('alter table public.%I add column if not exists facility_id uuid references public.healthcare_facilities(id)',t); execute format('create index if not exists %I on public.%I(facility_id)',t||'_facility_id_idx',t); end loop; end $$;

create or replace function public.enforce_extended_facility_lineage() returns trigger language plpgsql security definer set search_path='' as $$
declare v_facility uuid; v_active uuid; v_recon boolean:=coalesce(current_setting('hms.facility_reconciliation',true),'off')='on';
begin
 v_active:=public.current_user_facility_id();
 if tg_table_name in ('emergency_cases','maternity_episodes','fertility_cycles','patient_referrals','care_transitions','insurance_cases','pharmacy_dispensing_plans','pharmacy_pos_sales','transfusion_records','vital_alerts','ai_case_memory','ai_clinical_sessions','ai_report_requests','nursing_notes') then execute 'select p.facility_id from public.patients p where p.id=$1' into v_facility using new.patient_id;
 elsif tg_table_name in ('nursing_care_plans','nursing_shift_handovers','inpatient_bed_movements','ward_beds') then execute 'select p.facility_id from public.patients p where p.id=$1' into v_facility using new.patient_id; if v_facility is null and new.admission_id is not null then select a.facility_id into v_facility from public.admissions a where a.id=new.admission_id; end if;
 elsif tg_table_name in ('procedure_notes','theatre_cases','transfusion_records','ai_case_memory','ai_diagnosis_suggestions') then if new.encounter_id is not null then select e.facility_id into v_facility from public.encounters e where e.id=new.encounter_id; end if; if v_facility is null and new.patient_id is not null then select p.facility_id into v_facility from public.patients p where p.id=new.patient_id; end if;
 elsif tg_table_name='insurance_claims' then if new.invoice_id is not null then select i.facility_id into v_facility from public.invoices i where i.id=new.invoice_id; end if; if v_facility is null then select p.facility_id into v_facility from public.patients p where p.id=new.patient_id; end if; end if;
 if v_facility is null then if new.facility_id is null and v_active is not null then new.facility_id:=v_active; elsif new.facility_id is null and not v_recon then raise exception 'Parent clinical record has no facility attribution'; end if;
 elsif new.facility_id is null then new.facility_id:=v_facility;
 elsif new.facility_id<>v_facility and not(v_recon and(public.current_user_has_role('admin') or public.current_user_has_role('it_admin'))) then raise exception 'Facility lineage mismatch'; end if;
 if new.facility_id is not null and v_active is not null and new.facility_id<>v_active and not(v_recon and(public.current_user_has_role('admin') or public.current_user_has_role('it_admin'))) then raise exception 'Facility context mismatch'; end if;
 if tg_op='UPDATE' and old.facility_id is not null and new.facility_id is null then raise exception 'Facility attribution cannot be cleared'; end if; return new;
end $$;
revoke all on function public.enforce_extended_facility_lineage() from public,anon,authenticated;

do $$ declare t text; begin foreach t in array array['emergency_cases','maternity_episodes','fertility_cycles','inpatient_bed_movements','nursing_care_plans','nursing_shift_handovers','patient_referrals','care_transitions','insurance_cases','insurance_claims','pharmacy_dispensing_plans','pharmacy_pos_sales','procedure_notes','theatre_cases','transfusion_records','vital_alerts','ai_case_memory','ai_clinical_sessions','ai_diagnosis_suggestions','ai_report_requests','nursing_notes','ward_beds'] loop execute format('drop trigger if exists %I on public.%I','trg_'||t||'_extended_facility_lineage',t); execute format('create trigger %I before insert or update on public.%I for each row execute function public.enforce_extended_facility_lineage()','trg_'||t||'_extended_facility_lineage',t); execute format('drop policy if exists %I on public.%I','facility isolation select',t); execute format('create policy %I on public.%I as restrictive for select to authenticated using (facility_id is null or public.current_user_has_facility_access(facility_id))','facility isolation select',t); end loop; end $$;