REVOKE EXECUTE ON FUNCTION public.record_triage_assessment_offline(
  UUID, UUID, INTEGER, INTEGER, INTEGER, NUMERIC, INTEGER, NUMERIC,
  NUMERIC, NUMERIC, INTEGER, TEXT, TEXT, TEXT, TEXT
) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_triage_assessment_offline(
  UUID, UUID, INTEGER, INTEGER, INTEGER, NUMERIC, INTEGER, NUMERIC,
  NUMERIC, NUMERIC, INTEGER, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_triage_assessment_offline(
  UUID, UUID, INTEGER, INTEGER, INTEGER, NUMERIC, INTEGER, NUMERIC,
  NUMERIC, NUMERIC, INTEGER, TEXT, TEXT, TEXT, TEXT
) TO authenticated;