ALTER FUNCTION public.acknowledge_nursing_handover(uuid) SET search_path='';
REVOKE ALL ON FUNCTION public.acknowledge_nursing_handover(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.acknowledge_nursing_handover(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.acknowledge_nursing_handover(uuid) TO authenticated;
ALTER FUNCTION public.create_ai_clinical_session(uuid,text,jsonb,jsonb) SET search_path='';
REVOKE ALL ON FUNCTION public.create_ai_clinical_session(uuid,text,jsonb,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_ai_clinical_session(uuid,text,jsonb,jsonb) FROM anon;
GRANT EXECUTE ON FUNCTION public.create_ai_clinical_session(uuid,text,jsonb,jsonb) TO authenticated;
ALTER FUNCTION public.create_ai_report_request(uuid,text) SET search_path='';
REVOKE ALL ON FUNCTION public.create_ai_report_request(uuid,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_ai_report_request(uuid,text) FROM anon;
GRANT EXECUTE ON FUNCTION public.create_ai_report_request(uuid,text) TO authenticated;
ALTER FUNCTION public.create_insurance_claim_draft(uuid,text,text,numeric,uuid) SET search_path='';
REVOKE ALL ON FUNCTION public.create_insurance_claim_draft(uuid,text,text,numeric,uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_insurance_claim_draft(uuid,text,text,numeric,uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.create_insurance_claim_draft(uuid,text,text,numeric,uuid) TO authenticated;
ALTER FUNCTION public.create_patient_admission(uuid,text,text,text) SET search_path='';
REVOKE ALL ON FUNCTION public.create_patient_admission(uuid,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_patient_admission(uuid,text,text,text) FROM anon;
GRANT EXECUTE ON FUNCTION public.create_patient_admission(uuid,text,text,text) TO authenticated;