-- Notification event catalog expansion: non-breaking event coverage for future modules.
-- Events remain disabled until their corresponding provider/channel and workflow are validated.
INSERT INTO public.notification_events
(event_name,description,trigger_source,audience,channel_priority,priority_level,quiet_hours_behavior,opt_out_allowed,template_key,enabled)
SELECT v.event_name,v.description,v.trigger_source,v.audience::jsonb,v.channels::jsonb,v.priority,v.quiet_hours_behavior,v.opt_out,v.template_key,false
FROM (VALUES
('patient_registered','Patient registration completed','registration','["patient","front_desk"]','["in_app","email"]','medium','send',false,'account.patient_registered'),
('patient_duplicate_detected','Potential duplicate patient identity detected','empi','["staff"]','["in_app"]','high','send',false,'identity.duplicate_detected'),
('patient_merge_completed','Patient records merged','empi','["staff"]','["in_app"]','high','send',false,'identity.merge_completed'),
('appointment_waitlisted','Patient added to appointment waitlist','appointments','["patient","front_desk"]','["in_app","email","sms"]','medium','delay',true,'appointment.waitlisted'),
('appointment_waitlist_slot_available','Waitlist appointment slot available','appointments','["patient"]','["in_app","push","sms"]','high','send',true,'appointment.waitlist_slot_available'),
('appointment_no_show','Appointment marked no-show','appointments','["patient","practitioner"]','["in_app","push"]','medium','send',true,'appointment.no_show'),
('appointment_recall_due','Recall appointment due','scheduler','["patient"]','["in_app","sms","email"]','medium','delay',true,'appointment.recall_due'),
('encounter_opened','Clinical encounter opened','encounters','["patient","practitioner"]','["in_app"]','medium','send',false,'encounter.opened'),
('encounter_completed','Clinical encounter completed','encounters','["patient","practitioner"]','["in_app","push"]','medium','send',false,'encounter.completed'),
('clinical_note_signed','Clinical note signed','clinical','["patient","practitioner"]','["in_app","push"]','medium','send',false,'clinical.note_signed'),
('clinical_note_amended','Clinical note amended','clinical','["patient","practitioner"]','["in_app"]','high','send',false,'clinical.note_amended'),
('care_plan_review_due','Care plan review due','scheduler','["patient","practitioner"]','["in_app","push"]','medium','delay',true,'care_plan.review_due'),
('referral_created','Referral created','referrals','["patient","staff"]','["in_app","email"]','medium','send',false,'referral.created'),
('referral_accepted','Referral accepted','referrals','["patient","staff"]','["in_app","push"]','medium','send',false,'referral.accepted'),
('referral_declined','Referral declined','referrals','["patient","staff"]','["in_app","email"]','high','send',false,'referral.declined'),
('referral_appointment_booked','Referral appointment booked','referrals','["patient"]','["in_app","sms","email"]','medium','delay',true,'referral.appointment_booked'),
('handover_created','Clinical handover created','nursing','["staff"]','["in_app"]','high','send',false,'nursing.handover_created'),
('handover_acknowledgement_due','Handover acknowledgement due','scheduler','["staff"]','["in_app","push"]','high','send',false,'nursing.handover_acknowledgement_due'),
('vital_alert_critical','Critical vital sign alert','clinical','["nurse","practitioner"]','["in_app","push","sms","voice"]','critical','send',false,'clinical.vital_alert_critical'),
('triage_completed','Triage assessment completed','emergency','["patient","nurse","practitioner"]','["in_app"]','high','send',false,'emergency.triage_completed'),
('emergency_case_created','Emergency case created','emergency','["clinical_staff"]','["in_app","push"]','critical','send',false,'emergency.case_created'),
('admission_created','Inpatient admission created','inpatient','["patient","ward_staff"]','["in_app","push"]','high','send',false,'inpatient.admission_created'),
('bed_assigned','Bed assigned','inpatient','["patient","ward_staff"]','["in_app","push"]','high','send',false,'inpatient.bed_assigned'),
('patient_transferred','Patient transferred','inpatient','["patient","ward_staff"]','["in_app","push"]','high','send',false,'inpatient.transferred'),
('discharge_started','Discharge workflow started','inpatient','["patient","staff"]','["in_app"]','high','send',false,'discharge.started'),
('discharge_completed','Discharge completed','inpatient','["patient","staff"]','["in_app","email"]','high','send',false,'discharge.completed'),
('lab_sample_collected','Laboratory sample collected','laboratory','["patient","laboratory"]','["in_app"]','medium','send',false,'lab.sample_collected'),
('lab_result_verified','Laboratory result verified','laboratory','["patient","practitioner"]','["in_app","push","email"]','high','send',false,'lab.result_verified'),
('lab_critical_result','Critical laboratory result','laboratory','["practitioner","nurse"]','["in_app","push","sms","voice"]','critical','send',false,'lab.critical_result'),
('lab_result_recalled','Laboratory result recalled','laboratory','["patient","practitioner"]','["in_app","push"]','high','send',false,'lab.result_recalled'),
('imaging_order_created','Imaging order created','imaging','["patient","imaging"]','["in_app"]','medium','send',false,'imaging.order_created'),
('imaging_exam_completed','Imaging examination completed','imaging','["patient","practitioner"]','["in_app","push"]','medium','send',false,'imaging.exam_completed'),
('imaging_report_verified','Imaging report verified','imaging','["patient","practitioner"]','["in_app","push","email"]','high','send',false,'imaging.report_verified'),
('imaging_critical_finding','Critical imaging finding','imaging','["practitioner","nurse"]','["in_app","push","sms","voice"]','critical','send',false,'imaging.critical_finding'),
('prescription_dispensed','Prescription dispensed','pharmacy','["patient","practitioner"]','["in_app","push"]','medium','send',false,'medication.dispensed'),
('prescription_cancelled','Prescription cancelled','pharmacy','["patient","practitioner"]','["in_app","push"]','high','send',false,'medication.prescription_cancelled'),
('drug_interaction_alert','Drug interaction alert','pharmacy','["pharmacist","practitioner"]','["in_app","push"]','critical','send',false,'medication.interaction_alert'),
('stock_low','Medication stock low','pharmacy','["pharmacist","inventory"]','["in_app","push"]','high','send',false,'inventory.stock_low'),
('stock_out','Medication stock out','pharmacy','["pharmacist","inventory"]','["in_app","push"]','critical','send',false,'inventory.stock_out'),
('purchase_order_approved','Purchase order approved','supply_chain','["procurement"]','["in_app","email"]','medium','send',false,'supply.purchase_order_approved'),
('purchase_order_received','Purchase order received','supply_chain','["procurement","inventory"]','["in_app"]','medium','send',false,'supply.purchase_order_received'),
('invoice_created','Invoice created','billing','["patient","billing"]','["in_app","email"]','medium','delay',true,'billing.invoice_created'),
('payment_received','Payment received','billing','["patient","billing"]','["in_app","email"]','medium','send',false,'billing.payment_received'),
('payment_failed','Payment failed','billing','["patient","billing"]','["in_app","email","sms"]','high','send',false,'billing.payment_failed'),
('insurance_claim_submitted','Insurance claim submitted','claims','["patient","claims_staff"]','["in_app","email"]','medium','send',false,'claims.submitted'),
('insurance_claim_rejected','Insurance claim rejected','claims','["patient","claims_staff"]','["in_app","email","sms"]','high','send',false,'claims.rejected'),
('insurance_claim_paid','Insurance claim paid','claims','["patient","claims_staff"]','["in_app","email"]','medium','send',false,'claims.paid'),
('preauthorization_requested','Preauthorization requested','claims','["claims_staff"]','["in_app"]','medium','send',false,'claims.preauthorization_requested'),
('preauthorization_approved','Preauthorization approved','claims','["patient","claims_staff"]','["in_app","email"]','medium','send',false,'claims.preauthorization_approved'),
('preauthorization_rejected','Preauthorization rejected','claims','["patient","claims_staff"]','["in_app","email","sms"]','high','send',false,'claims.preauthorization_rejected'),
('staff_account_created','Staff account created','identity','["staff"]','["in_app","email"]','medium','send',false,'account.staff_created'),
('staff_role_changed','Staff role changed','identity','["staff","admin"]','["in_app","email"]','high','send',false,'security.role_changed'),
('staff_access_revoked','Staff access revoked','identity','["staff","admin"]','["in_app","email"]','critical','send',false,'security.access_revoked'),
('password_reset_requested','Password reset requested','identity','["patient","staff"]','["in_app","email"]','high','send',false,'security.password_reset'),
('mfa_enabled','Multi-factor authentication enabled','identity','["patient","staff"]','["in_app","email"]','medium','send',false,'security.mfa_enabled'),
('login_suspicious','Suspicious login detected','identity','["patient","staff"]','["in_app","email","sms"]','critical','send',false,'security.suspicious_login'),
('data_export_requested','Data export requested','privacy','["patient","privacy_officer"]','["in_app","email"]','high','send',false,'privacy.export_requested'),
('data_erasure_requested','Data erasure requested','privacy','["patient","privacy_officer"]','["in_app","email"]','high','send',false,'privacy.erasure_requested'),
('consent_changed','Notification consent changed','preferences','["patient"]','["in_app","email"]','medium','send',false,'preferences.consent_changed'),
('notification_provider_failed','Notification provider failure','notification_service','["admin","it_admin"]','["in_app","email"]','critical','send',false,'notification.provider_failed'),
('notification_provider_recovered','Notification provider recovered','notification_service','["admin","it_admin"]','["in_app","email"]','medium','send',false,'notification.provider_recovered'),
('notification_delivery_failed','Notification delivery failed','notification_service','["admin","it_admin"]','["in_app"]','high','send',false,'notification.delivery_failed'),
('notification_queue_backlog','Notification queue backlog threshold reached','notification_service','["admin","it_admin"]','["in_app","email"]','high','send',false,'notification.queue_backlog'),
('facility_created','Facility onboarding completed','facility_admin','["admin","it_admin"]','["in_app","email"]','high','send',false,'facility.created'),
('facility_provider_verified','Notification provider verified','facility_admin','["admin","it_admin"]','["in_app","email"]','medium','send',false,'facility.provider_verified'),
('facility_provider_verification_failed','Notification provider verification failed','facility_admin','["admin","it_admin"]','["in_app","email"]','high','send',false,'facility.provider_verification_failed'),
('annual_wellness_review_due','Annual wellness review due','scheduler','["patient"]','["in_app","push","sms","email"]','medium','delay',true,'wellness.annual_review'),
('vaccination_due','Vaccination due','scheduler','["patient"]','["in_app","push","sms"]','medium','delay',true,'wellness.vaccination_due'),
('screening_due','Preventive screening due','scheduler','["patient"]','["in_app","push","email"]','medium','delay',true,'wellness.screening_due'),
('health_tip_available','Personalized wellness tip available','wellness','["patient"]','["in_app","push"]','low','delay',true,'wellness.health_tip'),
('outbreak_alert','Public health outbreak alert','public_health','["patient","staff"]','["in_app","push","sms"]','critical','send',false,'public_health.outbreak_alert'),
('public_health_campaign','Public health campaign message','public_health','["patient"]','["in_app","push","sms","email"]','medium','delay',true,'public_health.campaign'),
('birthday_greeting_scheduled','Birthday greeting scheduled','scheduler','["patient"]','["in_app","email","push"]','low','delay',true,'greeting.birthday'),
('christmas_greeting_scheduled','Christmas greeting scheduled','scheduler','["patient"]','["in_app","email","push"]','low','delay',true,'greeting.christmas'),
('world_health_day_greeting','World Health Day greeting','scheduler','["patient"]','["in_app","email","push"]','low','delay',true,'greeting.world_health_day')
) AS v(event_name,description,trigger_source,audience,channels,priority,quiet_hours_behavior,opt_out,template_key)
ON CONFLICT (event_name) DO UPDATE SET description=EXCLUDED.description,trigger_source=EXCLUDED.trigger_source,audience=EXCLUDED.audience,channel_priority=EXCLUDED.channel_priority,priority_level=EXCLUDED.priority_level,quiet_hours_behavior=EXCLUDED.quiet_hours_behavior,opt_out_allowed=EXCLUDED.opt_out_allowed,template_key=EXCLUDED.template_key;