-- Reconcile frontend creation RPC contracts with the active canonical schema.
-- Retired specialist_nurse is intentionally excluded.

CREATE OR REPLACE FUNCTION public.create_emergency_case(_patient_id UUID,_chief_complaint TEXT,_acuity TEXT DEFAULT 'urgent',_arrival_mode TEXT DEFAULT 'walk_in',_assigned_officer UUID DEFAULT NULL) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid UUID:=auth.uid(); v_id UUID; v_assigned UUID; v_priority TEXT; BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF; IF NOT (public.has_role(uid,'admin') OR public.has_role(uid,'practitioner') OR public.has_role(uid,'nurse') OR public.has_role(uid,'midwife') OR public.has_role(uid,'front_desk')) THEN RAISE EXCEPTION 'Emergency operations role required'; END IF; IF _patient_id IS NULL OR NULLIF(trim(_chief_complaint),'') IS NULL THEN RAISE EXCEPTION 'Patient and chief complaint are required'; END IF; IF _acuity NOT IN ('resuscitation','emergency','urgent','less_urgent','non_urgent') THEN RAISE EXCEPTION 'Invalid emergency acuity'; END IF; IF _arrival_mode NOT IN ('walk_in','ambulance','referral','other') THEN RAISE EXCEPTION 'Invalid arrival mode'; END IF; IF _assigned_officer IS NOT NULL AND _assigned_officer<>uid AND NOT public.has_role(uid,'admin') THEN RAISE EXCEPTION 'Only an administrator may assign another officer during creation'; END IF; v_priority:=CASE _acuity WHEN 'resuscitation' THEN 'critical' WHEN 'emergency' THEN 'critical' WHEN 'urgent' THEN 'urgent' WHEN 'less_urgent' THEN 'moderate' ELSE 'routine' END; v_assigned:=COALESCE(_assigned_officer,uid); INSERT INTO public.emergency_cases(patient_id,arrival_mode,triage_priority,chief_complaint,assigned_officer,status) VALUES(_patient_id,_arrival_mode,v_priority,trim(_chief_complaint),v_assigned,'waiting') RETURNING id INTO v_id; RETURN v_id; END; $$;
CREATE OR REPLACE FUNCTION public.create_ward_unit(_name TEXT,_code TEXT,_specialty TEXT DEFAULT NULL,_gender_policy TEXT DEFAULT 'mixed') RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id UUID; BEGIN IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Administrator role required'; END IF; IF NULLIF(trim(_name),'') IS NULL OR NULLIF(trim(_code),'') IS NULL THEN RAISE EXCEPTION 'Ward name and code are required'; END IF; IF _gender_policy NOT IN ('mixed','male','female') THEN RAISE EXCEPTION 'Invalid gender policy'; END IF; INSERT INTO public.wards(name,code,department,gender_policy) VALUES(trim(_name),trim(_code),NULLIF(trim(_specialty),''),_gender_policy) RETURNING id INTO v_id; RETURN v_id; END; $$;
CREATE OR REPLACE FUNCTION public.create_transfusion_record(_patient_id UUID,_blood_product TEXT,_unit_identifier TEXT,_blood_group TEXT DEFAULT NULL,_consent_confirmed BOOLEAN DEFAULT FALSE) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id UUID; v_component TEXT; BEGIN IF auth.uid() IS NULL OR NOT (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'practitioner') OR public.has_role(auth.uid(),'nurse')) THEN RAISE EXCEPTION 'Clinical role required'; END IF; IF _patient_id IS NULL OR NULLIF(trim(_blood_product),'') IS NULL OR NULLIF(trim(_unit_identifier),'') IS NULL THEN RAISE EXCEPTION 'Patient, blood product and unit identifier are required'; END IF; v_component:=CASE lower(trim(_blood_product)) WHEN 'whole_blood' THEN 'whole_blood' WHEN 'red_cells' THEN 'red_cells' WHEN 'platelets' THEN 'platelets' WHEN 'plasma' THEN 'plasma' WHEN 'cryoprecipitate' THEN 'cryoprecipitate' ELSE 'other' END; INSERT INTO public.transfusion_records(patient_id,component,unit_identifier,blood_group,consent_confirmed,status) VALUES(_patient_id,v_component,trim(_unit_identifier),NULLIF(trim(_blood_group),''),COALESCE(_consent_confirmed,false),'planned') RETURNING id INTO v_id; RETURN v_id; END; $$;
CREATE OR REPLACE FUNCTION public.create_theatre_case(_patient_id UUID,_procedure_name TEXT,_scheduled_start TIMESTAMPTZ,_theatre_name TEXT DEFAULT NULL,_urgency TEXT DEFAULT 'elective',_surgeon_id UUID DEFAULT NULL) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id UUID; BEGIN IF auth.uid() IS NULL OR NOT (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'practitioner') OR public.has_role(auth.uid(),'nurse')) THEN RAISE EXCEPTION 'Clinical role required'; END IF; IF _patient_id IS NULL OR NULLIF(trim(_procedure_name),'') IS NULL OR _scheduled_start IS NULL THEN RAISE EXCEPTION 'Patient, procedure and scheduled start are required'; END IF; IF _urgency NOT IN ('emergency','urgent','elective') THEN RAISE EXCEPTION 'Invalid urgency'; END IF; INSERT INTO public.theatre_cases(patient_id,procedure_name,theatre,scheduled_at,status,surgeon_id,created_by) VALUES(_patient_id,trim(_procedure_name),NULLIF(trim(_theatre_name),''),_scheduled_start,'planned',COALESCE(_surgeon_id,auth.uid()),auth.uid()) RETURNING id INTO v_id; RETURN v_id; END; $$;
REVOKE ALL ON FUNCTION public.create_emergency_case(UUID,TEXT,TEXT,TEXT,UUID) FROM anon,PUBLIC; GRANT EXECUTE ON FUNCTION public.create_emergency_case(UUID,TEXT,TEXT,TEXT,UUID) TO authenticated;
REVOKE ALL ON FUNCTION public.create_ward_unit(TEXT,TEXT,TEXT,TEXT) FROM anon,PUBLIC; GRANT EXECUTE ON FUNCTION public.create_ward_unit(TEXT,TEXT,TEXT,TEXT) TO authenticated;
REVOKE ALL ON FUNCTION public.create_transfusion_record(UUID,TEXT,TEXT,TEXT,BOOLEAN) FROM anon,PUBLIC; GRANT EXECUTE ON FUNCTION public.create_transfusion_record(UUID,TEXT,TEXT,TEXT,BOOLEAN) TO authenticated;
REVOKE ALL ON FUNCTION public.create_theatre_case(UUID,TEXT,TIMESTAMPTZ,TEXT,TEXT,UUID) FROM anon,PUBLIC; GRANT EXECUTE ON FUNCTION public.create_theatre_case(UUID,TEXT,TIMESTAMPTZ,TEXT,TEXT,UUID) TO authenticated;
NOTIFY pgrst,'reload schema';
