ALTER FUNCTION public.claim_notification_queue(integer) SET search_path='';
ALTER FUNCTION public.create_discharge_insurance_claim(uuid,text,text) SET search_path='';
ALTER FUNCTION public.create_insurance_company(text,text,text,text,text,text,text) SET search_path='';
ALTER FUNCTION public.create_insurance_service_tariff(uuid,text,text,numeric,numeric,numeric,date,date) SET search_path='';
ALTER FUNCTION public.enqueue_external_notification_channels(uuid) SET search_path='';
ALTER FUNCTION public.enqueue_notification_v2(text,uuid,jsonb,text,jsonb,text,timestamptz,text,uuid,text,text,uuid) SET search_path='';
ALTER FUNCTION public.ensure_notification_preferences(uuid) SET search_path='';
ALTER FUNCTION public.erase_notification_history(uuid) SET search_path='';
ALTER FUNCTION public.initialize_facility_notification_onboarding(uuid) SET search_path='';
ALTER FUNCTION public.mark_facility_notification_production_ready(uuid) SET search_path='';
ALTER FUNCTION public.reconcile_insurance_claim_to_invoice(uuid) SET search_path='';
ALTER FUNCTION public.set_facility_notification_provider(uuid,text,text,text,text,text,text,jsonb) SET search_path='';
ALTER FUNCTION public.update_facility_notification_configuration(uuid,jsonb) SET search_path='';
ALTER FUNCTION public.update_insurance_company(uuid,text,text,text,text,text,text,text,boolean) SET search_path='';
ALTER FUNCTION public.update_insurance_service_tariff(uuid,numeric,numeric,numeric,date,date,boolean) SET search_path='';
ALTER FUNCTION public.verify_facility_notification_provider(uuid,text,text,boolean,text) SET search_path='';
REVOKE ALL ON FUNCTION public.claim_notification_queue(integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.enqueue_external_notification_channels(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.claim_notification_queue(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_external_notification_channels(uuid) TO service_role;