ALTER FUNCTION public.get_admission_workspace(integer) SET search_path='';
REVOKE ALL ON FUNCTION public.get_admission_workspace(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_admission_workspace(integer) TO authenticated;
ALTER FUNCTION public.get_billing_window(uuid,timestamptz) SET search_path='';
REVOKE ALL ON FUNCTION public.get_billing_window(uuid,timestamptz) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_billing_window(uuid,timestamptz) TO authenticated;
ALTER FUNCTION public.get_canteen_active_patient_orders() SET search_path='';
REVOKE ALL ON FUNCTION public.get_canteen_active_patient_orders() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_canteen_active_patient_orders() TO authenticated;
ALTER FUNCTION public.get_department_queue(text,integer) SET search_path='';
REVOKE ALL ON FUNCTION public.get_department_queue(text,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_department_queue(text,integer) TO authenticated;
ALTER FUNCTION public.get_emergency_workspace(integer) SET search_path='';
REVOKE ALL ON FUNCTION public.get_emergency_workspace(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_emergency_workspace(integer) TO authenticated;
ALTER FUNCTION public.get_patient_bmi_context(uuid) SET search_path='';
REVOKE ALL ON FUNCTION public.get_patient_bmi_context(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_patient_bmi_context(uuid) TO authenticated;
ALTER FUNCTION public.get_ward_management_workspace(integer) SET search_path='';
REVOKE ALL ON FUNCTION public.get_ward_management_workspace(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_ward_management_workspace(integer) TO authenticated;