-- Extend the facility reconciliation inventory and control-plane RPCs.
create or replace function public.list_unresolved_clinical_facility_records(_limit integer default 100)
returns table(entity_type text,entity_id uuid,patient_id uuid,created_at timestamptz,metadata jsonb)
language sql security definer set search_path='' as $$select x.* from(
select 'patients'::text,p.id,p.id,p.created_at,jsonb_build_object('patient_code',p.patient_code,'first_name',p.first_name,'last_name',p.last_name) from public.patients p where p.facility_id is null
union all select 'appointments',a.id,a.patient_id,a.created_at,jsonb_build_object('department',a.department,'consultation_type',a.consultation_type,'status',a.status,'scheduled_at',a.scheduled_at) from public.appointments a where a.facility_id is null
union all select 'encounters',e.id,e.patient_id,e.created_at,jsonb_build_object('encounter_type',e.encounter_type,'status',e.status,'appointment_id',e.appointment_id) from public.encounters e where e.facility_id is null
union all select 'admissions',a.id,a.patient_id,a.created_at,jsonb_build_object('status',a.status,'ward',a.ward,'bed',a.bed,'encounter_id',a.encounter_id) from public.admissions a where a.facility_id is null
union all select 'service_orders',s.id,s.patient_id,s.created_at,jsonb_build_object('department',s.department,'service_name',s.service_name,'status',s.status,'encounter_id',s.encounter_id) from public.service_orders s where s.facility_id is null
union all select 'department_queues',q.id,q.patient_id,q.created_at,jsonb_build_object('department',q.department,'status',q.status,'service_order_id',q.service_order_id) from public.department_queues q where q.facility_id is null
union all select 'lab_orders',l.id,l.patient_id,l.created_at,jsonb_build_object('test_name',l.test_name,'status',l.status,'encounter_id',l.encounter_id) from public.lab_orders l where l.facility_id is null
union all select 'lab_results',r.id,r.patient_id,r.created_at,jsonb_build_object('lab_order_id',r.lab_order_id,'status',r.status) from public.lab_results r where r.facility_id is null
union all select 'imaging_orders',i.id,i.patient_id,i.created_at,jsonb_build_object('modality',i.modality,'study_name',i.study_name,'status',i.status,'encounter_id',i.encounter_id) from public.imaging_orders i where i.facility_id is null
union all select 'prescriptions',rx.id,rx.patient_id,rx.created_at,jsonb_build_object('medication',coalesce(rx.medication_name,rx.medication),'status',rx.status,'encounter_id',rx.encounter_id) from public.prescriptions rx where rx.facility_id is null
union all select 'diagnoses',d.id,d.patient_id,d.created_at,jsonb_build_object('diagnosis',d.diagnosis,'icd_code',d.icd_code,'encounter_id',d.encounter_id) from public.diagnoses d where d.facility_id is null
union all select 'invoices',i.id,i.patient_id,i.created_at,jsonb_build_object('invoice_number',i.invoice_number,'status',i.status,'total_amount',i.total_amount,'encounter_id',i.encounter_id) from public.invoices i where i.facility_id is null
union all select 'invoice_items',ii.id,ii.patient_id,ii.created_at,jsonb_build_object('description',ii.description,'amount',ii.amount,'invoice_id',ii.invoice_id,'service_order_id',ii.service_order_id) from public.invoice_items ii where ii.facility_id is null
union all select 'payments',p.id,p.patient_id,p.created_at,jsonb_build_object('amount',p.amount,'status',p.status,'invoice_id',p.invoice_id,'payment_method',p.payment_method) from public.payments p where p.facility_id is null
union all select 'patient_documents',d.id,d.patient_id,d.created_at,jsonb_build_object('document_type',d.document_type,'file_name',d.file_name,'mime_type',d.mime_type) from public.patient_documents d where d.facility_id is null
union all select 'triage_assessments',t.id,t.patient_id,t.created_at,jsonb_build_object('priority',t.priority,'bmi',t.bmi) from public.triage_assessments t where t.facility_id is null
union all select 'vital_signs',v.id,v.patient_id,v.created_at,jsonb_build_object('systolic',v.systolic,'diastolic',v.diastolic,'temperature',v.temperature,'encounter_id',v.encounter_id) from public.vital_signs v where v.facility_id is null
union all select 'medication_administrations',m.id,m.patient_id,m.created_at,jsonb_build_object('medication_name',m.medication_name,'status',m.status,'prescription_id',m.prescription_id) from public.medication_administrations m where m.facility_id is null
)x where public.has_role(auth.uid(),'admin') or public.has_role(auth.uid(),'it_admin') order by x.created_at nulls last limit greatest(1,least(coalesce(_limit,100),500));$$;
revoke all on function public.list_unresolved_clinical_facility_records(integer) from public,anon;grant execute on function public.list_unresolved_clinical_facility_records(integer) to authenticated;
create or replace function public.reconcile_extended_clinical_facility_record(_entity_type text,_entity_id uuid,_target_facility_id uuid,_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=auth.uid();v_parent uuid;v_source uuid;v_patient uuid;v_exists boolean:=false;v_metadata jsonb:='{}'::jsonb;begin
if v_actor is null or not(public.has_role(v_actor,'admin') or public.has_role(v_actor,'it_admin')) then raise exception 'Only administrators can reconcile clinical facility attribution';end if;if _target_facility_id is null or nullif(btrim(_reason),'') is null then raise exception 'Target facility and reconciliation reason are required';end if;if not exists(select 1 from public.healthcare_facilities f where f.id=_target_facility_id and f.is_active) then raise exception 'Target facility is not active';end if;perform set_config('hms.facility_reconciliation','on',true);
if _entity_type='appointments' then select a.facility_id,a.patient_id,true,jsonb_build_object('department',a.department,'consultation_type',a.consultation_type,'status',a.status) into v_source,v_patient,v_exists,v_metadata from public.appointments a where a.id=_entity_id;
elsif _entity_type='admissions' then select a.facility_id,a.patient_id,true,jsonb_build_object('status',a.status,'ward',a.ward,'bed',a.bed) into v_source,v_patient,v_exists,v_metadata from public.admissions a where a.id=_entity_id;
elsif _entity_type='invoices' then select i.facility_id,i.patient_id,true,jsonb_build_object('invoice_number',i.invoice_number,'status',i.status,'total_amount',i.total_amount) into v_source,v_patient,v_exists,v_metadata from public.invoices i where i.id=_entity_id;
elsif _entity_type='invoice_items' then select ii.facility_id,ii.patient_id,true,jsonb_build_object('description',ii.description,'amount',ii.amount,'invoice_id',ii.invoice_id) into v_source,v_patient,v_exists,v_metadata from public.invoice_items ii where ii.id=_entity_id;
elsif _entity_type='payments' then select p.facility_id,p.patient_id,true,jsonb_build_object('amount',p.amount,'status',p.status,'invoice_id',p.invoice_id) into v_source,v_patient,v_exists,v_metadata from public.payments p where p.id=_entity_id;
elsif _entity_type='patient_documents' then select d.facility_id,d.patient_id,true,jsonb_build_object('document_type',d.document_type,'file_name',d.file_name) into v_source,v_patient,v_exists,v_metadata from public.patient_documents d where d.id=_entity_id;
elsif _entity_type='triage_assessments' then select t.facility_id,t.patient_id,true,jsonb_build_object('priority',t.priority,'bmi',t.bmi) into v_source,v_patient,v_exists,v_metadata from public.triage_assessments t where t.id=_entity_id;
elsif _entity_type='vital_signs' then select v.facility_id,v.patient_id,true,jsonb_build_object('systolic',v.systolic,'diastolic',v.diastolic,'temperature',v.temperature) into v_source,v_patient,v_exists,v_metadata from public.vital_signs v where v.id=_entity_id;
elsif _entity_type='medication_administrations' then select m.facility_id,m.patient_id,true,jsonb_build_object('medication_name',m.medication_name,'status',m.status,'prescription_id',m.prescription_id) into v_source,v_patient,v_exists,v_metadata from public.medication_administrations m where m.id=_entity_id;
else raise exception 'Unsupported extended clinical entity type';end if;
if not v_exists then raise exception 'Clinical record not found';end if;
if v_patient is not null then select p.facility_id into v_parent from public.patients p where p.id=v_patient;if v_parent is null then raise exception 'Reconcile the parent patient facility first';elsif v_parent<>_target_facility_id then raise exception 'Target facility conflicts with patient facility';end if;end if;
if _entity_type='invoice_items' then select i.facility_id into v_parent from public.invoices i where i.id=(select invoice_id from public.invoice_items where id=_entity_id);if v_parent is null then raise exception 'Reconcile the parent invoice facility first';elsif v_parent<>_target_facility_id then raise exception 'Target facility conflicts with invoice facility';end if;elsif _entity_type='payments' then select i.facility_id into v_parent from public.invoices i where i.id=(select invoice_id from public.payments where id=_entity_id);if v_parent is not null and v_parent<>_target_facility_id then raise exception 'Target facility conflicts with invoice facility';end if;end if;
execute format('update public.%I set facility_id=$1 where id=$2 and facility_id is null',_entity_type) using _target_facility_id,_entity_id;
insert into public.clinical_facility_reconciliation(entity_type,entity_id,source_facility_id,target_facility_id,reason,reviewed_by,metadata) values(_entity_type,_entity_id,v_source,_target_facility_id,btrim(_reason),v_actor,v_metadata) on conflict(entity_type,entity_id) do update set source_facility_id=excluded.source_facility_id,target_facility_id=excluded.target_facility_id,status='corrected',reason=excluded.reason,reviewed_by=excluded.reviewed_by,reviewed_at=now(),metadata=excluded.metadata;
perform public.record_system_audit('clinical_facility_reconciled','facility_control_plane',_entity_type,_entity_id,'warning',jsonb_build_object('source_facility_id',v_source,'target_facility_id',_target_facility_id,'reason',btrim(_reason),'actor_id',v_actor));return jsonb_build_object('ok',true,'entity_type',_entity_type,'entity_id',_entity_id,'target_facility_id',_target_facility_id);end$$;
revoke all on function public.reconcile_extended_clinical_facility_record(text,uuid,uuid,text) from public,anon;grant execute on function public.reconcile_extended_clinical_facility_record(text,uuid,uuid,text) to authenticated;