import { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, Plus, XCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';

type Facility={id:string;name:string;facility_code:string|null};
type Agreement={id:string;facility_a_id:string;facility_b_id:string;status:string;purpose:string;effective_from:string;effective_to:string|null;facility_a_approved_by:string|null;facility_b_approved_by:string|null};
const scopes=['patient_read','clinical_read','encounter_read','diagnosis_read','lab_read','imaging_read','medication_read','billing_read','document_read','care_coordination'];

export default function FacilityDataSharing(){
 const {user}=useAuth(); const system=user?.role==='system_superuser'; const canApprove=system||user?.role==='admin'||user?.role==='it_admin';
 const [facilities,setFacilities]=useState<Facility[]>([]); const [agreements,setAgreements]=useState<Agreement[]>([]); const [loading,setLoading]=useState(true);
 const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [a,setA]=useState(''); const [b,setB]=useState(''); const [purpose,setPurpose]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState('');
 const [selectedScopes,setSelectedScopes]=useState<string[]>(['patient_read','clinical_read','care_coordination']);
 const facilityName=useMemo(()=>new Map(facilities.map(f=>[f.id,f.name+(f.facility_code?' ('+f.facility_code+')':'')])),[facilities]);
 const load=useCallback(async()=>{setLoading(true);const [fr,ar]=await Promise.all([supabase.from('healthcare_facilities').select('id,name,facility_code').eq('is_active',true).order('name'),supabase.from('facility_data_sharing_agreements').select('id,facility_a_id,facility_b_id,status,purpose,effective_from,effective_to,facility_a_approved_by,facility_b_approved_by').order('created_at',{ascending:false})]);if(fr.error)toast.error(fr.error.message);else setFacilities((fr.data??[]) as Facility[]);if(ar.error)toast.error(ar.error.message);else setAgreements((ar.data??[]) as Agreement[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{if(!a||!b||a===b||!purpose||!selectedScopes.length)return toast.error('Select two different facilities, a purpose and at least one scope.');setSaving(true);const {error}=await supabase.rpc('create_facility_data_sharing_agreement',{_facility_a_id:a,_facility_b_id:b,_purpose:purpose,_effective_from:from?new Date(from).toISOString():null,_effective_to:to?new Date(to).toISOString():null,_scopes:selectedScopes});setSaving(false);if(error)return toast.error(error.message);toast.success('Agreement created and awaiting bilateral approval.');setOpen(false);setPurpose('');setFrom('');setTo('');setSelectedScopes(['patient_read','clinical_read','care_coordination']);void load()};
 const approve=async(id:string)=>{const {error}=await supabase.rpc('approve_facility_data_sharing_agreement',{_agreement_id:id});if(error)return toast.error(error.message);toast.success('Approval recorded.');void load()};
 const revoke=async(id:string)=>{const reason=window.prompt('Reason for revocation');if(!reason?.trim())return;const {error}=await supabase.rpc('revoke_facility_data_sharing_agreement',{_agreement_id:id,_reason:reason.trim()});if(error)return toast.error(error.message);toast.success('Agreement revoked.');void load()};
 if(!canApprove)return <div className="card-medical p-6 text-sm text-muted-foreground">Facility data-sharing governance is restricted to authorized administrators.</div>;
 return <div className="space-y-6 animate-fade-in">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><Building2 className="h-6 w-6 text-primary"/>Facility Data Sharing</h1><p className="text-sm text-muted-foreground mt-1">Clinical records remain facility-owned. Cross-facility access is deny-by-default and requires explicit scope, bilateral approval and time controls.</p></div>{system&&<button className="btn-primary inline-flex items-center gap-2" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Create agreement</button>}</header>
  <section className="card-medical p-5"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Active</p><p className="mt-1 text-2xl font-semibold">{agreements.filter(x=>x.status==='active').length}</p></div><div className="rounded-2xl border p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Pending</p><p className="mt-1 text-2xl font-semibold">{agreements.filter(x=>x.status==='pending').length}</p></div><div className="rounded-2xl border p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Facilities</p><p className="mt-1 text-2xl font-semibold">{facilities.length}</p></div></div></section>
  <section className="card-medical overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Facilities</th><th className="p-4">Purpose</th><th className="p-4">Status</th><th className="p-4">Approval</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td className="p-6 text-muted-foreground" colSpan={5}>Loading…</td></tr>:agreements.length?agreements.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-4 font-medium">{facilityName.get(row.facility_a_id)??row.facility_a_id}<div className="text-xs text-muted-foreground">↔ {facilityName.get(row.facility_b_id)??row.facility_b_id}</div></td><td className="p-4 max-w-xs">{row.purpose}</td><td className="p-4"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold capitalize">{row.status}</span></td><td className="p-4 text-xs">{row.facility_a_approved_by?'A approved':'A pending'} · {row.facility_b_approved_by?'B approved':'B pending'}</td><td className="p-4 text-right"><div className="flex justify-end gap-2">{row.status!=='revoked'&&canApprove&&<button className="btn-secondary inline-flex items-center gap-1 text-xs" onClick={()=>void approve(row.id)}><CheckCircle2 className="h-3.5 w-3.5"/>Approve</button>}{system&&row.status!=='revoked'&&<button className="btn-secondary inline-flex items-center gap-1 text-xs" onClick={()=>void revoke(row.id)}><XCircle className="h-3.5 w-3.5"/>Revoke</button>}</div></td></tr>):<tr><td className="p-8 text-center text-muted-foreground" colSpan={5}>No facility data-sharing agreements.</td></tr>}</tbody></table></div></section>
  {open&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-3xl border bg-card p-6 shadow-elevated"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Create bilateral agreement</h2><p className="text-xs text-muted-foreground mt-1">Both facilities must approve before access becomes active.</p></div><button className="btn-secondary" onClick={()=>setOpen(false)}><XCircle className="h-4 w-4"/></button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className="input-medical" value={a} onChange={e=>setA(e.target.value)}><option value="">Facility A</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select className="input-medical" value={b} onChange={e=>setB(e.target.value)}><option value="">Facility B</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input className="input-medical md:col-span-2" placeholder="Purpose" value={purpose} onChange={e=>setPurpose(e.target.value)}/><label className="text-xs text-muted-foreground">Effective from<input type="datetime-local" className="input-medical mt-1 w-full" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs text-muted-foreground">Effective to<input type="datetime-local" className="input-medical mt-1 w-full" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="mt-4"><p className="text-sm font-semibold mb-2">Access scopes</p><div className="grid gap-2 sm:grid-cols-2">{scopes.map(scope=><label key={scope} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={e=>setSelectedScopes(v=>e.target.checked?[...new Set([...v,scope])]:v.filter(x=>x!==scope))}/>{scope.replaceAll('_',' ')}</label>)}</div></div><div className="mt-5 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={()=>void create()}>{saving?'Creating…':'Create agreement'}</button></div></div></div>}
 </div>;
}
