import RefreshButton from '@/components/ui/RefreshButton';
// @ts-nocheck -- schema types lag behind live database functions; runtime unaffected
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, RefreshCw, ShieldCheck } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { listFacilities, type HealthcareFacility } from '@/lib/reportsCenter';

type RecordRow = { entity_type:string; entity_id:string; patient_id:string|null; created_at:string|null; metadata:Record<string,unknown>; };
const labels:Record<string,string>={patients:'Patient',appointments:'Appointment',encounters:'Encounter',admissions:'Admission',service_orders:'Service order',department_queues:'Department queue',lab_orders:'Laboratory order',lab_results:'Laboratory result',imaging_orders:'Imaging order',prescriptions:'Prescription',diagnoses:'Diagnosis',invoices:'Invoice',invoice_items:'Invoice item',payments:'Payment',patient_documents:'Patient document',triage_assessments:'Triage assessment',vital_signs:'Vital signs',medication_administrations:'Medication administration',wards:'Ward',beds:'Bed',anesthetic_assessments:'Anaesthetic assessment',billing_overrides:'Billing override',dental_records:'Dental record',inpatient_reviews:'Inpatient review',meal_orders:'Meal order',meal_plans:'Meal plan',ophthalmology_exams:'Ophthalmology examination',outside_lab_documents:'Outside laboratory document',patient_account_credits:'Patient account credit',patient_visit_authorizations:'Patient visit authorization',video_sessions:'Telemedicine session'};

export default function FacilityAttributionReview(){
 const {user}=useAuth(); const allowed=user?.role==='admin'||user?.role==='it_admin';
 const [rows,setRows]=useState<RecordRow[]>([]); const [facilities,setFacilities]=useState<HealthcareFacility[]>([]);
 const [selected,setSelected]=useState<Record<string,string>>({}); const [reasons,setReasons]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState<string|null>(null); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{ if(!allowed)return; setLoading(true); try{
   const [records,remaining,facilityList]=await Promise.all([supabase.rpc('list_unresolved_clinical_facility_records',{_limit:500}),supabase.rpc('list_unresolved_remaining_clinical_facility_records',{_limit:500}),listFacilities()]);
   if(records.error)throw new Error(records.error.message); if(remaining.error)throw new Error(remaining.error.message); setRows(([...(records.data??[]),...(remaining.data??[])]) as RecordRow[]); setFacilities(facilityList.filter(f=>f.is_active));
 }catch(e){toast.error(e instanceof Error?e.message:'Unable to load facility attribution review.');}finally{setLoading(false);}},[allowed]);
 useEffect(()=>{void load()},[load]);
 const counts=useMemo(()=>rows.reduce<Record<string,number>>((a,r)=>(a[r.entity_type]=(a[r.entity_type]??0)+1,a),{}),[rows]);
 async function reconcile(row:RecordRow){const target=selected[row.entity_id];const reason=(reasons[row.entity_id]??'').trim();if(!target)return toast.error('Select the confirmed facility before reconciling.');if(!reason)return toast.error('Enter the evidence/reason for the attribution decision.');setBusy(row.entity_id);try{const rpc=['appointments','admissions','invoices','invoice_items','payments','patient_documents','triage_assessments','vital_signs','medication_administrations'].includes(row.entity_type)?'reconcile_extended_clinical_facility_record':['wards','beds','anesthetic_assessments','billing_overrides','dental_records','inpatient_reviews','meal_orders','meal_plans','ophthalmology_exams','outside_lab_documents','patient_account_credits','patient_visit_authorizations','video_sessions'].includes(row.entity_type)?'reconcile_remaining_clinical_facility_record':'reconcile_clinical_facility_record'; const {error}=await supabase.rpc(rpc,{_entity_type:row.entity_type,_entity_id:row.entity_id,_target_facility_id:target,_reason:reason});if(error)throw new Error(error.message);toast.success('Facility attribution reconciled and audited.');setRows(p=>p.filter(x=>x.entity_id!==row.entity_id));}catch(e){toast.error(e instanceof Error?e.message:'Unable to reconcile this record.');}finally{setBusy(null);}}
 if(!allowed)return <div className="p-6 text-sm text-muted-foreground">Facility attribution review is restricted to administrators and IT administrators.</div>;
 if(loading)return <div className="p-6 text-sm text-muted-foreground">Loading unresolved clinical facility records…</div>;
 return <div className="space-y-6 animate-fade-in">
  <header className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h1 className="text-2xl font-heading font-bold flex items-center gap-2"><ShieldCheck className="h-6 w-6 text-primary"/>Facility Attribution Review</h1><p className="text-muted-foreground max-w-3xl">Governed reconciliation of historical clinical records that pre-date canonical facility attribution. No record is assigned automatically.</p></div><RefreshButton onClick={() => void load()} /></header>
  <section className="card-medical rounded-3xl p-5 border-warning/30"><div className="flex items-start gap-3"><AlertTriangle className="h-5 w-5 text-warning mt-0.5"/><div className="text-sm"><p className="font-semibold">Historical attribution is evidence-based.</p><p className="text-muted-foreground mt-1">The system intentionally leaves ambiguous legacy rows unresolved. Review records in lineage order where possible: patient → encounter/order → downstream result or queue.</p></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(labels).map(([key,label])=><div key={key} className="card-medical rounded-2xl p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="text-2xl font-semibold">{counts[key]??0}</div></div>)}</section>
  <section className="card-medical rounded-3xl overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2 font-semibold"><ClipboardCheck className="h-5 w-5"/>Unresolved records <span className="text-muted-foreground font-normal">({rows.length})</span></div></div>
  {rows.length===0?<div className="p-8 text-center text-sm text-muted-foreground"><CheckCircle2 className="h-8 w-8 mx-auto mb-2 text-success"/>All currently discovered legacy clinical rows have an explicit facility attribution.</div>:
  <div className="divide-y">{rows.map(row=>{const meta=row.metadata??{};const title=labels[row.entity_type]??row.entity_type;const display=String(meta.patient_code??meta.test_name??meta.study_name??meta.medication??meta.diagnosis??meta.service_name??meta.department??row.entity_id);return <article key={row.entity_type+row.entity_id} className="p-5 space-y-4">
   <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between"><div><div className="text-sm font-semibold">{title} · {display}</div><div className="text-xs text-muted-foreground mt-1">ID: {row.entity_id} · Created {row.created_at?new Date(row.created_at).toLocaleString():'unknown'}</div></div><span className="rounded-full bg-warning/10 px-2.5 py-1 text-xs text-warning">Unresolved</span></div>
   <pre className="max-h-28 overflow-auto rounded-xl bg-muted p-3 text-xs">{JSON.stringify(meta,null,2)}</pre>
   <div className="grid gap-3 md:grid-cols-[1fr_1.5fr_auto] md:items-end"><label className="text-sm space-y-1"><span>Confirmed facility</span><select className="input-medical w-full" value={selected[row.entity_id]??''} onChange={e=>setSelected({...selected,[row.entity_id]:e.target.value})}><option value="">Select facility…</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}{f.facility_code ? ` (${f.facility_code})` : ''}</option>)}</select></label>
   <label className="text-sm space-y-1"><span>Evidence / reason</span><input className="input-medical w-full" value={reasons[row.entity_id]??''} onChange={e=>setReasons({...reasons,[row.entity_id]:e.target.value})} placeholder="e.g. source register, facility code, encounter documentation"/></label>
   <button type="button" className="btn-primary inline-flex items-center justify-center gap-2" disabled={busy===row.entity_id} onClick={()=>void reconcile(row)}>{busy===row.entity_id?'Saving…':'Reconcile'}</button></div>
  </article>})}</div>}</section>
 </div>;
}
