import { useEffect, useState } from 'react';
import { applyAccessibilityPreferences, getAccessibilityPreferences, isModuleEnabled, nextGenModules, setAccessibilityPreferences, setModuleEnabled, type AccessibilityPreferences } from '@/lib/nextGenPlatform';

const stateLabels: Record<string, string> = { available: 'Available', validated: 'Validated', planned: 'Planned', disabled: 'Disabled' };

export default function NextGenPlatformControlCenter() {
  const [preferences, setPreferences] = useState<AccessibilityPreferences>(getAccessibilityPreferences);
  const [revision, setRevision] = useState(0);
  const enabledCount = nextGenModules.filter((module) => isModuleEnabled(module.id)).length;
  useEffect(() => applyAccessibilityPreferences(preferences), [preferences]);

  const updatePreference = <K extends keyof AccessibilityPreferences>(key: K, value: AccessibilityPreferences[K]) => {
    const next = { ...preferences, [key]: value }; setPreferences(next); setAccessibilityPreferences(next);
  };
  const toggleModule = (id: string) => { setModuleEnabled(id, !isModuleEnabled(id)); setRevision((value) => value + 1); };
  void revision;

  return <main className="mx-auto w-full max-w-7xl space-y-8 p-4 md:p-6" aria-labelledby="platform-title">
    <header className="rounded-2xl border bg-card p-6 shadow-sm"><p className="text-sm font-medium text-primary">Next-generation HIMS reference architecture</p><h1 id="platform-title" className="mt-1 text-2xl font-semibold tracking-tight">Platform Control Center</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Configuration is deliberately local and reversible on this proving-ground branch. Production enablement remains gated by security, clinical safety, accessibility, integration, performance and deployment verification.</p><div className="mt-4 flex flex-wrap gap-3 text-sm" aria-label="Platform summary"><span className="rounded-full border px-3 py-1">{nextGenModules.length} registered modules</span><span className="rounded-full border px-3 py-1">{enabledCount} enabled</span><span className="rounded-full border px-3 py-1">AI human oversight required</span></div></header>
    <section className="rounded-2xl border bg-card p-6 shadow-sm" aria-labelledby="accessibility-title"><h2 id="accessibility-title" className="text-lg font-semibold">Accessibility preferences</h2><p className="mt-1 text-sm text-muted-foreground">Preferences are applied immediately and persist on this device.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label className="flex items-center justify-between gap-4 rounded-xl border p-4"><span>Text scale</span><select className="rounded-md border bg-background px-2 py-1" value={preferences.textScale} onChange={(event) => updatePreference('textScale', event.target.value as AccessibilityPreferences['textScale'])}><option value="100">100%</option><option value="110">110%</option><option value="125">125%</option><option value="150">150%</option></select></label>{([['highContrast', 'High contrast'], ['reducedMotion', 'Reduced motion'], ['captions', 'Captions'], ['readAloud', 'Read aloud'], ['voiceNavigation', 'Voice navigation']] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between gap-4 rounded-xl border p-4"><span>{label}</span><input type="checkbox" checked={preferences[key]} onChange={(event) => updatePreference(key, event.target.checked)} aria-label={label} /></label>)}</div></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm" aria-labelledby="modules-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="modules-title" className="text-lg font-semibold">Module registry</h2><p className="mt-1 text-sm text-muted-foreground">Only modules explicitly registered by the reference architecture can be toggled.</p></div><span className="text-xs text-muted-foreground">Production default: disabled until validated</span></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{nextGenModules.map((module) => { const enabled = isModuleEnabled(module.id); const planned = module.state === 'planned'; return <article key={module.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{module.id}</h3><p className="text-xs text-muted-foreground">{module.domain} · {module.tier}</p></div><span className="rounded-full border px-2 py-1 text-[11px]">{stateLabels[module.state]}</span></div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{module.safetyCritical ? 'Safety-critical' : 'Operational'}</span><span>{module.offlineCapable ? 'Offline capable' : 'Online required'}</span></div><button type="button" disabled={planned} aria-pressed={enabled} onClick={() => toggleModule(module.id)} className="mt-4 w-full rounded-lg border px-3 py-2 text-sm font-medium transition hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50">{planned ? 'Awaiting implementation' : enabled ? 'Disable module' : 'Enable module'}</button></article>; })}</div></section>
  </main>;
}
